<div class="row-fluid">
<div class="span12">
<div class="alert alert-block alert-error fade in">
<h4 class="alert-heading">Remoção de Cadastro</h4>
								<p>Atenção, você esta prestes a remover um cadastro so sistema</p>
								<p>Esta é a última confirmação que você verá e os dados removidos não poderão ser recuperados</p>
								<p>Todas as Informações referentes a esta pessoa serão excluídas do sistema, deseja realmente continuar?</p>
								<p><a href="javascript:void(0)" class="btn btn-inverse" onclick="removecad()"> <i class="splashy-check"></i> Confirmar </a>
								<a href="javascript:hitory.back(-1)" class="btn btn-inverse" > <i class="splashy-check"></i> Cancelar </a>
								</p>
								</div>
						</div>
						</div>

<?php echo $this->form ?>