<div class="row-fluid">
<div class="span12">
<h3 class="heading">Consulta movimentos de estoque</h3>
<table id="listaclientes" class="table table-striped table-bordered">
<thead>
<tr>
<th width="3%">ID</th>
<th width="10%">Local</th>
<th width="30%">Produto</th>
<th width="5%">Quantidade</th>
<th width="25%">Histórico</th>
<th width="10%">Data</th>
<th width="10%">Usuário</th>
</tr>
</thead>
<tbody>
<tr>
<td class="dataTables_empty" colspan="7">Não existem dados nessa consulta!</td>
</tr>
</tbody>
</table>
</div>
</div>
<script>
$().ready(function(){

	$('#listaclientes').dataTable({
		"oLanguage": {
		"sUrl": "/js/datatable_ptbr.txt"
		},
		"sPaginationType": "bootstrap",
		"bProcessing": true,
		"bServerSide": true,
		"sAjaxSource": "/system/datatables/movimento-estoque"


	});


});


	</script>