<?php if(Cadastros_Model_Produtos::countProdutosAlerta() > 0){ ?>							
							<div class="row-fluid">
							 <div class="span12">
							<div class="heading clearfix">
								<h3 class="pull-left">Produtos em Aleta: <small>Quantidade menor que a mínima</small></h3>
								<span class="pull-right label label-important ttip_t" title="Quantidade menor que a minima!"><?php echo Cadastros_Model_Produtos::countProdutosAlerta() ?></span>
							</div>
							<table id="listaclientes" class="table table-striped table-bordered">
<thead>
<tr>
<th width="5%">ID</th>
<th width="5%">Cod Int</th>
<th width="10%">Categoria</th>
<th width="10%">Sub-Categoria</th>
<th width="45%">Produto</th>
<th width="15%">Referência</th>
<th width="5%">Estoque</th>
<th width="5%">Minimio</th>

</tr>
</thead>
<tbody>
<?php 
$produtosalerta = Cadastros_Model_Produtos::getProdutosAlerta();
foreach($produtosalerta as $prodale){ 
?>
<tr>
<td width="5%"><?php echo $prodale['id_produto'] ?></td>
<td width="5%"><?php echo $prodale['codigointerno'] ?></td>
<td width="10%"><?php echo $prodale['nomecategoria'] ?></td>
<td width="10%"><?php echo $prodale['nomesubcategoria'] ?></td>
<td width="45%"><?php echo $prodale['nomeproduto'] ?></td>
<td width="15%"><?php echo $prodale['referenciaproduto'] ?></td>
<td width="5%"><?php echo number_format($prodale['estoqueatual'],3,',','') ?></td>
<td width="5%"><?php echo number_format($prodale['estoqueminimo'],3,',','') ?></td>
</tr>
<?php  } ?>
</tbody>
</table>

				
							</div>
							
							</div>
							<?php } ?>
							
							<script>
$().ready(function(){

	$('#listaclientes').dataTable({
		"sPaginationType": "bootstrap",
		"oLanguage": {
			"sUrl": "/js/datatable_ptbr.txt"
		}
                    
    });


});


</script>
							