<div class="row-fluid">
<div class="span12">
<h3 class="heading">Lista de locais de estoque</h3>
<table id="listaclientes" class="table table-striped table-bordered">
<thead>
<tr>
<th width="5%"></th>
<th width="5%">ID</th>
<th width="25%">Tipo</th>
<th width="60%">Local</th>
<th width="5%">Opções</th>

</tr>
</thead>
<tbody>
<?php foreach($this->locais as $dado) {?>
<tr>
<td width="5%"><i  idregistro="<?php echo $dado->id_registro ?>" class="<?php if($dado->is_default == 1){  echo "splashy-star_full"; }else{  echo "splashy-star_empty\" style=\"cursor:pointer\" title=\"Marcar como padrão\"  "; }?>"></i></td>
<td><?php echo $dado->id_registro ?></td>
<td><?php echo System_Model_Tiposestoques::getNome($dado->tipoestoque) ?></td>
<td><?php echo $dado->localestoque ?></td>
<td><a href="/erp/estoque/edita-local/id/<?php echo $dado->id_registro ?>"><i class="splashy-hcards_edit"></i></a>
	<i class="splashy-hcards_remove removelocal" idregistro="<?php echo $dado->id_registro ?>" style="cursor:pointer" ></i> </td>
</tr>
<?php } ?>
</tbody>
</table>
</div>
</div>


<!-- MODAL PARA REMOVER LOCAL -->

<div class="modal hide fade" id="RemoveLocalEstoque">
   <div class="modal-header">
                        <button class="close" data-dismiss="modal"></button>
                        <h3>Excluir Local:</h3>
                    </div>
<form id="newreply" name="newreply" enctype="id_note" class="form-horizontal" method="post" action="/erp/estoque/remover-local">
<input type="hidden" name="localantigo" value="0" id="id_registroLocal">
<div class="modal-body">
<div class="row-fluid formSep">
		<div class="span12">
		<h4>Para excluir um local o estoque cadastrado nele deve ser transferido para um novo local:</h4>
		</div>
			
		</div>
		
		
		<div class="row-fluid formSep">
		
		<div class="span12">
		<label for="assuntoticket" class="optional">Selecione um local para o estoque ser transferido:</label>
		<select name="novolocal" class="span12" id="novolocal">
		<?php
		$deptos = Erp_Model_Estoque_Locais::getCombo();
		foreach($deptos as $key=>$value){
		echo "<option value=\"$key\"> $value </otion>";
		}
		?>
		</select>
		</div>
			
		</div>
  
</div>
<div class="modal-footer">
<div style="text-align:right">
<a href="javascript:void(0)" class="btn btn-large btn-warning" data-dismiss="modal">Cancelar</a>
<input type="submit" name="submit" id="submiteditnote" value="Remover Local >>" class="btn btn-large btn-primary">
</div>		
</form>
</div>
</div>


<script>
$().ready(function(){

	$('#listaclientes').dataTable({
		"oLanguage": {
			"sUrl": "/js/datatable_ptbr.txt"
		},
		"sPaginationType": "bootstrap"
    });


    $(".splashy-star_empty").live('click',function(){
        if(confirm("Deseja tornar esse local como padrão?")){
          id = $(this).attr('idregistro');
			that = $(this);
          $.ajax({
				type: "GET",
				url: "/erp/estoque/setdefaultlocation",
				data: "id="+id ,
				beforeSend: function() {

		 		},
				success: function(txt) {
					$('.splashy-star_full').addClass('splashy-star_empty').removeClass("splashy-star_full");
					$.sticky("Local definido como padrão", { type: 'st-success' });
					 that.addClass('splashy-star_full').removeClass('splashy-star_empty');
				},
				error: function(txt) {
					 $(this).addClass('splashy-star_full').removeClass('splashy-star_empty');
					$.sticky("Um erro ocorreu.", { type: 'st-error' });
				}
			});

        }

        });

    $(".removelocal").live('click',function(){
    	$("#RemoveLocalEstoque").modal('show');
    	id = $(this).attr('idregistro');
		that = $(this);
		$("#id_registroLocal").val(id);
        

    })


});


</script>