<div class="row-fluid">
<div class="span12">
<h3 class="heading">Planilha de Movimentos: <small>Selecione a categoria e subcategoria de produtos a movimentar</small> <div id="ajaxforms"></div></h3>
</div>
</div>
<form id="produtos" name="produtos" enctype="application/x-www-form-urlencoded" class="form-horizontal" method="post" action="/erp/estoque/getprodutos">
<div class="row-fluid formSep">
<div class="span4">
<?php echo $this->form->localestoque ?>
</div>
<div class="span4">
<?php echo $this->form->categoriaproduto ?>
</div>
<div class="span4">
<?php echo $this->form->subcategoriaproduto ?>
</div>
</div>
<div class="row-fluid ">
<fieldset id="fieldset-botoes">
<div style="text-align:right">
<input type="reset" name="limpar" id="limpar" value="Limpar" class="btn btn-large btn-warning">
<input type="submit" name="submit" id="submit" value="Carregar >>" class="btn btn-large btn-primary">
</div>
</fieldset>
</div>
</form>

<div id="planilhadeprodutos-lines">
<hr>

<form id="planilhaprodutos"  name="planilhaprodutos" enctype="application/x-www-form-urlencoded" class="form-horizontal" method="post" action="/erp/estoque/movimenta-planilha">
<div class="row-fluid ">
<table class="table table-striped table-bordered" id="tableprodutos">
<thead>
<th width="10%">Produto</th>
<th width="10%">Atual:</th>
<th width="10%">Entradas:</th>
<th width="10%">Saídas:</th>
<th width="10%">Transferência:</th>
<th width="25%">Local Transferência:</th>
<th width="25%">Histórico:</th>
</thead>
<tbody>
<tr>
<td></td>
<td></td>
<td></td>
<td></td>
<td></td>
<td></td>
<td></td>
</tr>

</tbody>
</table>
</div>
<div class="row-fluid formSep">
<fieldset id="fieldset-botoes">
<div style="text-align:right">
<input type="reset" name="limpar" id="limpar" value="Limpar" class="btn btn-large btn-warning">
<input type="submit" name="submit" id="submit" value="Salvar" class="btn btn-large btn-primary">
</div>
</fieldset>
</div>
</form>


</div>
<script>
$.fn.chosenDestroy = function () {
	$(this).show().removeClass('chzn-done')
	$(this).next().remove()

	  return $(this);
	}

$().ready(function(){	
	$("#planilhadeprodutos-lines").hide();
	$("#categoriaproduto").chosen();
	$("#subcategoriaproduto").chosen();

	$('#categoriaproduto').change(function(){
		$("#subcategoriaproduto").chosenDestroy();

         $('#subcategoriaproduto')
	    .find('option')
	    .remove()
	    .end()
	    .append('<option value="whatever">Carregando ... </option>')
	    .val('0');


    	y = 1;
    	$.getJSON("/cadastros/produtos/getsubcategorias/id/"+ $('#categoriaproduto').val(), function(data) {

    		 $('#subcategoriaproduto')
	     	    .find('option')
	     	    .remove()
	     	    .end()
	     	    .append('<option value="0">- Selecione -</option>')
	     	    .val('0')
	     	;

    		$.each(data, function(i,item){
    			document.getElementById('subcategoriaproduto').options[y] = new Option( item.nomesubcategoria , item.id_registro );
    			y++;
    		});

    		$("#subcategoriaproduto").chosen();
    	});

    })

	$('#produtos').validate({
		onkeyup: false,
		errorClass: 'error',
		validClass: 'valid',
		highlight: function(element) {
			$(element).closest('div').addClass("f_error");
		},
		unhighlight: function(element) {
			$(element).closest('div').removeClass("f_error");
		},
        errorPlacement: function(error, element) {
            $(element).closest('div').append(error);
        },
      
        invalidHandler: function(form, validator) {
			$.sticky("Existem campos obrigatórios não preenchidos no formulário, corrija estes erros e tente novamente.", {autoclose : 5000, position: "top-right", type: "st-error" });
		},
		submitHandler: function(form) {
			jQuery(form).ajaxSubmit({
				target: "#ajaxforms",
				beforeSubmit:   function(){ 
					$.sticky("Localizando Produtos.", {autoclose : 5000, position: "top-right", type: "st-info" });
					$('#tableprodutos > tbody >tr').remove();
					
				}, 
			error: function(txt) { 
				$.sticky("Ocorreu um erro com sua solicitação: "+ txt, {autoclose : 5000, position: "top-right", type: "st-error" });
				$("#ajaxforms").html('');

				
			},
			success: function(txt){
				
				$.sticky("Produtos Localizados.", {autoclose : 5000, position: "top-right", type: "st-success" });
				$("#ajaxforms").html("");
				$("#planilhadeprodutos-lines").show("slow");
				var retorno = jQuery.parseJSON(txt);	
				$.each(retorno, function(i,item){
					if(item.travatransf){
						var row = "<tr><td><input type='hidden' name='localatual[]' value='"+item.localatual+"'><input type='hidden' name='idproduto[]' value='"+item.id_registro+"'>"+item.nomeproduto+"</td><td>"+item.estoqueatual+"</td><td><input type='text' name='entradas[]' class='span6'></td><td><input type='text' name='saidas[]' class='span6'></td><td><input type='text' name='transferencias[]' class='span6' readonly='readonly'></td><td><select name='novolocal[]' class='span6' id='novolocal' readonly='readonly'><?php $deptos = Erp_Model_Estoque_Locais::getCombo();foreach($deptos as $key=>$value){ echo "<option value='$key'> $value </otion>"; }?></select></td><td><input type='text' name='historico[]'></td></tr>";
					}else{
						var row = "<tr><td><input type='hidden' name='localatual[]' value='"+item.localatual+"'><input type='hidden' name='idproduto[]' value='"+item.id_registro+"'>"+item.nomeproduto+"</td><td>"+item.estoqueatual+"</td><td><input type='text' name='entradas[]' class='span6'></td><td><input type='text' name='saidas[]' class='span6'></td><td><input type='text' name='transferencias[]' class='span6'></td><td><select name='novolocal[]' class='span6' id='novolocal'><?php $deptos = Erp_Model_Estoque_Locais::getCombo();foreach($deptos as $key=>$value){ echo "<option value='$key'> $value </otion>"; }?></select></td><td><input type='text' name='historico[]'></td></tr>";
					}
	    			$("#tableprodutos > tbody").append(row);
	    		});
				
		
			},
		        clearForm: false
				
			});
		}
    });

})



</script>

