<?php if($this->osfound){ ?>
<script src="/lib/datatables/jquery.dataTables.min.js"></script>
<h3 class="heading">Ordem de Serviços: <?php echo $this->dados->cod_os ?> <span class="pull-right"> <a href="/default/consulta/print-os/id/<?php echo $this->dados->id_registro?>" target="_blank"><i class="splashy-printer" title="Imprimir"></i></a></span></h3>
<div class="tabbable tabs-left">
	 	<ul class="nav nav-tabs">
			<li class="active"><a href="#tab_l1" data-toggle="tab">Dados: </a></li>
			<li><a href="#tab_l2" data-toggle="tab">Itens </a></li>
			<li><a href="#tab_l3" data-toggle="tab">Notas </a></li>
		</ul>
	<div class="tab-content">
		<div class="tab-pane active" id="tab_l1">


<fieldset id="fieldset-clientes" class="form-horizontal">
<div class="row-fluid">
<div class="span2">
<div class="w-box" id="w_sort02">
<div class="w-box-header"><strong>Código</strong></div>
<div class="w-box-content">
<?php echo $this->dados->cod_os; ?>
</div>
</div>
</div>
<div class="span6">
<div class="w-box" id="w_sort02">
<div class="w-box-header"><strong>Cliente</strong></div>
<div class="w-box-content">
<?php echo Cadastros_Model_Pessoas::getNomeEmpresa($this->dados->id_cliente) ?>
</div>
</div>
</div>
<div class="span4">
<div class="w-box" id="w_sort02">
<div class="w-box-header"><strong>Contato</strong></div>
<div class="w-box-content">
<?php echo Cadastros_Model_Contatos::getNomeContato($this->dados->id_contato)?>
</div>
</div>
</div>
</div>
<div class="row-fluid">
<div class="span3">
<div class="w-box" id="w_sort02">
<div class="w-box-header"><strong>Tipo</strong></div>
<div class="w-box-content">
<?php echo Crm_Model_Os_Tipos::getNomeTipo($this->dados->tipo_os)  ?>
</div>
</div>
</div>
<div class="span3">
<div class="w-box" id="w_sort02">
<div class="w-box-header"><strong>Status:</strong></div>
<div class="w-box-content">
<?php echo Crm_Model_Os_Status::getNomeTipo($this->dados->status_os) ?>
</div>
</div>
</div>
<?php $Totais =  Crm_Model_Os_Basicos::totalOs($this->dados->id_registro ) ?>
<div class="span3">
<div class="w-box" id="w_sort02">
<div class="w-box-header"><strong>Total Serviços</strong></div>
<div class="w-box-content">
R$<?php echo $Totais[0]['totalservicos']?>
</div>
</div>
</div>
<div class="span3">
<div class="w-box" id="w_sort02">
<div class="w-box-header"><strong>Total Produtos:</strong></div>
<div class="w-box-content">
R$<?php echo $Totais[0]['totalprodutos']?>
</div>
</div>

</div>
</div>
<div class="row-fluid formSep">
<div class="span12">
<div class="w-box" id="w_sort02">
<div class="w-box-header"><strong>Relato Cliente:</strong></div>
<div class="w-box-content">
<?php echo nl2br($this->dados->relato_cliente)?>
</div>
</div>
</div>
</div>
<div class="row-fluid formSep">
<div class="span12">
<div class="w-box" id="w_sort02">
<div class="w-box-header"><strong>Relato Técnico:</strong></div>
<div class="w-box-content">
<?php echo nl2br($this->dados->relato_tecnico)?>
</div>
</div>

</div>
</div>
</fieldset>



</div>
		<div class="tab-pane " id="tab_l2">
<div class="row-fluid">
<div class="span6">
<h3 class="heading">Serviços</h3>
	
<table id="servicos-table" class="table table-striped table-bordered table-condensed">
		<thead>
		<tr>
			<th>Serviço</th>
			<th>Qtd</th>
			<th>Vl Un.</th>
			<th>Total</th>
			<th></th>
			</tr>
		</thead>
		<tbody>
		</tbody>
</table>
</div>
<div class="span6">
<h3 class="heading">Produtos</h3>

<table id="produtos-table" class="table table-striped table-bordered table-condensed">
		<thead>
		<tr>
			<th>Produto</th>
			<th>Qtd</th>
			<th>Vl Un.</th>
			<th>Total</th>
			<th></th>
			</tr>
		</thead>
		<tbody>
		</tbody>
</table>
</div>
</div>
</div>
		<div class="tab-pane" id="tab_l3">
		<div class="span10">
		<h3>Anotações</h3>
		
		
		<div id="Anotacoes_Info" class="span10">
	<?php foreach($this->datanotes as $note){?>
	
		<div id="data_anotacao_<?php echo $note->id_registro ?>" class="row-fluid formSep">
		<div class="span12">
		<div class="w-box" id="w_sort02">
									<div class="w-box-header">
									<?php if($note->usuario_note == 0){ ?>
									<i class="splashy-group_grey" title="Cliente OS"></i>
									<?php }else{ ?>
									<i class="splashy-group_blue" title="Usuário do Sistema"></i>
									<?php } ?>
										<?php echo $note->nome_usuario ?> em <?php echo Functions_Datas::MyDateTime($note->data_note,true) ?>
										<div class="pull-right">
											<div class="btn-group">
												<a class="btn dropdown-toggle btn-mini" data-toggle="dropdown" href="#">
													<i class="icon-cog"></i> <span class="caret"></span>
												</a>
												<ul class="dropdown-menu">
													<li><a href="#" onclick="removeanotacao(<?php echo $note->id_registro?>)">Excluir</a></li>
												</ul>
											</div>
										</div>
									</div>
									<div class="w-box-content">
									<?php echo nl2br($note->anotacao)?>
									</div>
								</div>
							</div>
							</div>
						
						<?php } ?>
						</div>
		</div>
		</div>
			
</div>
</div>



<div id="ajaxforms"></div>

<script>


	
$().ready(function(){
	



	$('#servicos-table').dataTable({
		"oLanguage": {
			"sUrl": "/js/datatable_ptbr.txt"
		},
		"sPaginationType": "bootstrap",
    "bProcessing": true,
	"bServerSide": true,
    "sAjaxSource": "/default/datatables/servicos-os/id/<?php echo $this->dados->id_registro ?>"             	
                    
    });

	$('#produtos-table').dataTable({
		"oLanguage": {
			"sUrl": "/js/datatable_ptbr.txt"
		},
		"sPaginationType": "bootstrap",
    "bProcessing": true,
	"bServerSide": true,
	  "sAjaxSource": "/default/datatables/produtos-os/id/<?php echo $this->dados->id_registro ?>"           	
                    
    });


});


    </script>

<style>
input[type=checkbox], input.checkbox { 
 float:left;
 clear:none; 
 margin: 2px 0 0 2px; 
}
label[for=opcoes_os-SendMail] { 
 float:left; 
 clear:none; 
 display:block; 
 padding: 2px 1em 0 0; 
}
label[for=opcoes_os-SendSMS] { 
 float:left; 
 clear:none; 
 display:block; 
 padding: 2px 1em 0 0; 
}
label[for=opcoes_os-ClientCheck] { 
 float:left; 
 clear:none; 
 display:block; 
 padding: 2px 1em 0 0; 
}
</style>




<?php }else{?>
<h3 class="heading">Ordem de Serviços não localizada!</h3>
<h3><small>O Localizador: <?php echo $this->localizador?> não foi encontrado em nosso banco de dados!</small></h3>
<?php } ?>