<div class="row-fluid">
<div class="span12">
<h3 class="heading">Fila de Mensagens
<span class="pull-right"><i style="cursor:pointer" class="splashy-document_a4_new newdepto ttip_b" title="Nova Fila"></i></span></h3>
<table id="listaclientes" class="table table-striped table-bordered">
<thead>
<tr>
<th width="5%">ID</th>
<th width="5%">Email</th>
<th width="30%">Tipo</th>
<th width="10%">Departamento</th>
<th width="5%">Opções</th>
</tr>
</thead>
<tbody>
<?php foreach($this->dados as $dado){ ?>
<tr>
<td width="5%"><?php echo $dado->id_registro ?></td>
<td width="5%"><?php echo $dado->user ?></td>
<td width="30%"><?php if($dado->parsertype == '1'){ echo "Tickets"; }else{ echo "Prospects"; };  ?></td>
<td width="10%"><?php echo Crm_Model_TicketsDeptos::getNomeDepto($dado->depto_id) ?></td>
<td width="5%"><i class="splashy-hcards_edit editdepto"  idreg="<?php echo  $dado->id_registro ?>" style="cursor:pointer" ></i> <i class="splashy-hcards_remove removedepto" idreg="<?php echo $dado->id_registro ?>" style="cursor:pointer" ></i></span></td>
</tr>
<?php }; ?>
</tbody>
</table>
</div>
</div>

<div class="modal hide fade" id="NewDepto">
   <div class="modal-header">
                        <button class="close" data-dismiss="modal">×</button>
                        <h3>Fila de Mensagens:</h3>
                    </div>
<form id="newreply" name="newreply" enctype="id_note" class="form-horizontal" method="post" action="/system/configurator/newparser">
<input type="hidden" name="id_registro" value="0" id="id_registro">
<div class="modal-body">
		
		<div class="row-fluid formSep">
		<div class="span4">
		<label for="parsertype" class="optional">Tipo de Parser</label>
		<select name="parsertype" class="span12" id="parsertype">
	    <option value="1"> Tickets </otion>
	    <option value="2"> Prospects </otion>
		</select>
		</div>
		<div class="span4">
		<label for="ssl" class="optional">SSL?</label>
		<select name="ssl" class="span12" id="ssl">
	    <option value="1"> Sim </otion>
	    <option value="2"> Não </otion>
		</select>
		</div>
		<div class="span4">
		<label for="host" class="optional">Host (Servidor):</label>
		<input type="text" name="host" id="host" class="span12" >
		</div>
		</div>
		
		<div class="row-fluid formSep">
		<div class="span4">
		<label for="user" class="optional">Usuário (Email):</label>
		<input type="text" name="user" id="user" class="span12" >
		</div>				
		<div class="span4">
		<label for="password" class="optional">Senha</label>
		<input type="text" name="password" id="password" class="span12" >
		</div>
		<div class="span4">
		<label for="port" class="optional">Porta (110)</label>
		<input type="text" name="port" id="port" class="span12" >
		</div>
		</div>
		<div class="row-fluid formSep">
		<div class="span4">
		<label for="depto_id" class="optional">Departamento</label>
		<select name="depto_id" class="span12" id="depto_id">
		<?php
		$deptos = Crm_Model_TicketsDeptos::renderCombo();
		foreach($deptos as $key=>$value){
		echo "<option value=\"$key\"> $value </otion>";
		}
		?>
		</select>
		</div>
		<div class="span4">
		<label for="tipo_ticket" class="optional">Tipo Ticket</label>
		<select name="tipo_ticket" class="span12" id="tipo_ticket">
		<?php
		$deptos = Crm_Model_TicketsTipos::renderCombo();
		foreach($deptos as $key=>$value){
		echo "<option value=\"$key\"> $value </otion>";
		}
		?>
		</select>
		</div>
		<div class="span4">
		<label for="statusticket" class="optional">Status Padrão</label>
		<select name="statusticket" class="span12" id="statusticket">
		<?php
		$deptos = Crm_Model_TicketsStatus::renderCombo();
		foreach($deptos as $key=>$value){
		echo "<option value=\"$key\"> $value </otion>";
		}
		?>
		</select>
		</div>
		</div>
		
		<div class="row-fluid formSep">
		<div class="span4">
		<label for="prioridadeticket" class="optional">Prioridade</label>
		<select name="prioridadeticket" class="span12" id="prioridadeticket">
		<?php
		$deptos = Crm_Model_TicketsPrioridades::renderCombo();
		foreach($deptos as $key=>$value){
		echo "<option value=\"$key\"> $value </otion>";
		}
		?>
		</select>
		</div>
		<div class="span4">
		<label for="sendemail" class="optional">Envia Respsota?</label>
		<select name="sendemail" class="span12" id="sendemail">
	    <option value="1"> Sim </otion>
	    <option value="2"> Não </otion>
		</select>
		</div>
		<div class="span4">
		<label for="deleteemail" class="optional">Deletar Email?</label>
		<select name="deleteemail" class="span12" id="deleteemail">
	    <option value="1"> Sim </otion>
	    <option value="2"> Não </otion>
		</select>
		</div>
		</div>

		</div>

<div class="modal-footer">
<div style="text-align:right">
<a href="javascript:void(0)" class="btn btn-large btn-warning" data-dismiss="modal">Cancelar</a>
<input type="submit" name="submit" id="submiteditnote" value="Salvar" class="btn btn-large btn-primary">
</div>		
</form>
</div>
</div>

<script>
$().ready(function(){

	$('#listaclientes').dataTable({
		"oLanguage": {
			"sUrl": "/js/datatable_ptbr.txt"
		},
		"sPaginationType": "bootstrap"
                     	
                    
    });

    $(".newdepto").click(function(){
	    $("#NewDepto").modal('show');    
		
    });

    $(".editdepto").click(function(){
        id = $(this).attr('idreg');

   	 $.ajax({ 
			type: "GET", 
			url: "/system/configurator/getparserdata/id/"+ id , 
			data: "undo="+ id,
			beforeSend: function() {
								
	 		}, 
			success: function(txt) {
			
				var retorno = jQuery.parseJSON(txt);	
				$("#id_registro").val(retorno.id_registro);
				$("#parsertype").val(retorno.parsertype);
				$("#ssl").val(retorno.ssl);
				$("#host").val(retorno.host);
			    $("#user").val(retorno.user);
				$("#password").val(retorno.password);
				$("#port").val(retorno.port);
				$("#depto_id").val(retorno.depto_id);
				$("#tipo_ticket").val(retorno.tipo_ticket);
				$("#statusticket").val(retorno.statusticket);
				$("#prioridadeticket").val(retorno.prioridadeticket);
				$("#sendemail").val(retorno.sendemail);
				$("#deleteemail").val(retorno.deleteemail);
				$("#NewDepto").modal('show');  	

														
			}, 
			error: function(txt) { 
				$.sticky("UM ERRO DE SISTEMA OCORREU.", { type: 'st-error' });
			} 
		}); 

    });

    $(".removedepto").click(function(){
  	  	id = $(this).attr('idreg');
  	  	if(confirm("Deseja Realmente excluir este parser?")){
    	 document.location.href="/system/configurator/removeparser/id/"+id;
  	  	}
  	  

    });

    


});


</script>
