 <script src="/lib/tiny_mce/jquery.tinymce.js"></script>
<div class="row-fluid">
<div class="span12">
<h3 class="heading">Mensagens do Sistema
<span class="pull-right"><i style="cursor:pointer" class="splashy-document_a4_new newdepto ttip_b" title="Novo Tipo de Cadastro"></i></span></h3>
<table id="listaclientes" class="table table-striped table-bordered">
<thead>
<tr>
<th width="5%">ID</th>
<th width="85%">Nome</th>
<th width="5%">Opções</th>
</tr>
</thead>
<tbody>
<?php foreach($this->dados as $dado){ ?>
<tr>
<td width="5%"><?php echo $dado->id_registro ?></td>
<td width="85%"><?php echo $dado->nomemensagem ?></td>
<td width="5%"><i class="splashy-hcards_edit editdepto"  idreg="<?php echo  $dado->id_registro ?>" style="cursor:pointer" ></i> <i class="splashy-hcards_remove removedepto" idreg="<?php echo $dado->id_registro ?>" style="cursor:pointer" ></i></span></td>
</tr>
<?php }; ?>
</tbody>
</table>
</div>
</div>

<div class="modal hide fade" id="NewDepto">
   <div class="modal-header">
                        <button class="close" data-dismiss="modal">×</button>
                        <h3>Nova Mensagem:</h3>
                    </div>
<form id="newreply" name="newreply" enctype="id_note" class="form-horizontal" method="post" action="/system/configurator/newmensagemsistema">
<input type="hidden" name="id_registro" value="0" id="id_registro">
<div class="modal-body">
<div class="row-fluid formSep">
		<div class="span12">
		<label for="tipoticket" class="optional">Nome Amigável:</label>
		<input type="text" name="nomemensagem" id="nomemensagem" class="span12" >
		</div>
		</div>
		<div class="row-fluid formSep">
		<div class="span12">
		<label for="tipoticket" class="optional">Mensagem HTML:</label>
		<textarea class="span12" name="htmlmensagem" id="htmlmensagem"></textarea>
		</div>
		</div>
		<div class="row-fluid formSep">
		<div class="span12">
		<label for="tipoticket" class="optional">Mensagem Texto:</label>
		<textarea class="span12" name="textmensagem" id="textmensagem"></textarea>
		</div>
		</div>
		<div class="row-fluid formSep">
		<div class="span12">
		<label for="tipoticket" class="optional">Mensagem SMS</label>
		<textarea class="span12" name="smsmensagem" id="smsmensagem"></textarea>
		</div>						
		</div>
		
					  
</div>
<div class="modal-footer">
<div style="text-align:right">
<a href="javascript:void(0)" class="btn btn-large btn-warning" data-dismiss="modal" id="cancelamodal">Cancelar</a>
<input type="submit" name="submit" id="submiteditnote" value="Salvar" class="btn btn-large btn-primary">
</div>		
</form>
</div>
</div>

<script>
$().ready(function(){

	$("#htmlmensagem").tinymce({
        // Location of TinyMCE script
        script_url 							: '/lib/tiny_mce/tiny_mce.js',
        // General options
        theme 								: "advanced",
        plugins 							: "autoresize,style,table,advhr,advimage,advlink,emotions,inlinepopups,preview,media,contextmenu,paste,fullscreen,noneditable,xhtmlxtras,template,advlist",
        // Theme options
        theme_advanced_buttons1 			: "undo,redo,|,bold,italic,underline,strikethrough,|,justifyleft,justifycenter,justifyright,justifyfull,fontselect,fontsizeselect",
        theme_advanced_buttons2 			: "forecolor,backcolor,|,cut,copy,paste,pastetext,|,bullist,numlist,link,image,media,|,code,preview,fullscreen",
        theme_advanced_buttons3 			: "",
        theme_advanced_toolbar_location 	: "top",
        theme_advanced_toolbar_align 		: "left",
        theme_advanced_statusbar_location 	: "bottom",
        theme_advanced_resizing 			: false,
        font_size_style_values 				: "8pt,10px,12pt,14pt,18pt,24pt,36pt"
        });

	$('#listaclientes').dataTable({
		"oLanguage": {
			"sUrl": "/js/datatable_ptbr.txt"
		},
		"sPaginationType": "bootstrap"
                     	
                    
    });

    $(".newdepto").click(function(){
	    $("#NewDepto").modal('show');    
		
    });

    $(".editdepto").click(function(){
        id = $(this).attr('idreg');

   	 $.ajax({ 
			type: "GET", 
			url: "/system/configurator/getmensagemsistema/id/"+ id , 
			data: "undo="+ id,
			beforeSend: function() {
								
	 		}, 
			success: function(txt) {
			
				var retorno = jQuery.parseJSON(txt);	
				$("#id_registro").val(retorno.id_registro);
				$("#nomemensagem").val(retorno.nomemensagem);
				$("#htmlmensagem").val(retorno.htmlmensagem);
				$("#textmensagem").val(retorno.textmensagem);
				$("#smsmensagem").val(retorno.smsmensagem);
				$("#NewDepto").modal('show');  	

														
			}, 
			error: function(txt) { 
				$.sticky("UM ERRO DE SISTEMA OCORREU.", { type: 'st-error' });
			} 
		}); 

    });
    $("#cancelamodal").click(function(){
    	$("#id_registro").val("0");
		$("#nomemensagem").val("");
		$("#htmlmensagem").val("");
		$("#textmensagem").val("");
		$("#smsmensagem").val("");

     });

    $(".removedepto").click(function(){
  	  	id = $(this).attr('idreg');
  	  	if(confirm("Deseja Realmente excluir esta mensagem?")){
    	 document.location.href="/system/configurator/removemensagemsistema/id/"+id;
  	  	}
  	  

    });

    


});


</script>
