<div class="row-fluid">
<div class="span12">
<h3 class="heading">Menus do Sistema <span class="pull-right"><i class="splashy-document_letter_new novomenu"></i></span><div id="ajaxrequest"></div></h3>
<table id="listaclientes" class="table table-striped table-bordered">
<thead>
<tr>
<th width="5%">ID</th>
<th width="10%">Modulo</th>
<th width="10%">Controlador</th>
<th width="20%">Ação</th>
<th width="10%">Parametros</th>
<th width="20%">Nome</th>
<th width="5%">Pos</th>
<th width="5%"></th>
</tr>
</thead>
<tbody>
<tr>
<td class="dataTables_empty" colspan="9">Não existem dados nessa consulta!</td>
</tr>
</tbody>
</table>
</div>
</div>


 <div class="modal hide fade" id="NovoRecurso">
 <form id="Fnovorecurso" name="novorecurso" method="post" action="/sistema/configuracoes/salva-menu">
 <input type="hidden" name="id_registro" id="id_registro" value='' class="span12" >
 <div class="modal-header">
   <button class="close" data-dismiss="modal">×</button>
   <h3>Novo Recurso:</h3>
   </div>
 <div class="modal-body">
 <div class="row-fluid formSep">
 <div class="span4">
 <label for="resource" class="optional">Modulo:</label>
<input type="text" name="module" id="module" class="span12" >
 </div>
 <div class="span4">
  <label for="description" class="optional">Controlador:</label>
<input type="text" name="controller" id="controller" class="span12" >
 </div>
 <div class="span4">
  <label for="description" class="optional">Ação:</label>
<input type="text" name="action" id="action" class="span12" >
 </div>
 </div>
 
 <div class="row-fluid formSep">
 <div class="span4">
 <label for="resource" class="optional">Parametros:</label>
<input type="text" name="parans" id="parans" class="span12" >
 </div>
 <div class="span6">
  <label for="description" class="optional">Nome:</label>
<input type="text" name="nome" id="nome" class="span12" >
 </div>
 <div class="span2">
  <label for="description" class="optional">Posição:</label>
<input type="text" name="position" id="position" class="span12" >
 </div>
 </div>
 
 </div>
  <div class="modal-footer">
<input type="submit" name="submit" id="submiteditnote" value="Salvar" class="btn btn-large btn-primary">
</div>
</form>
 </div> 

<script>
$().ready(function(){

	$('#listaclientes').dataTable({
		"oLanguage": {
			"sUrl": "/js/datatable_ptbr.txt"
		},
		"sPaginationType": "bootstrap",
        "bProcessing": true,
		"bServerSide": true,
		 "sAjaxSource": "/system/datatables-sistema/menus"
               	
                    
    });

	$(".novomenu").click(function(){

		$("#NovoRecurso").modal('show');

	});

	$('#Fnovorecurso').validate({
		onkeyup: false,
		errorClass: 'error',
		validClass: 'valid',
		highlight: function(element) {
			$(element).closest('div').addClass("f_error");
		},
		unhighlight: function(element) {
			$(element).closest('div').removeClass("f_error");
		},
  errorPlacement: function(error, element) {
      $(element).closest('div').append(error);
  },

  invalidHandler: function(form, validator) {
			$.sticky("Existem campos obrigatórios não preenchidos no formulário, corrija estes erros e tente novamente.", {autoclose : 5000, position: "top-right", type: "st-error" });
		},
		submitHandler: function(form) {
			jQuery(form).ajaxSubmit({
				target: "#ajaxrequest",
				beforeSubmit:   function(){ 
					$.sticky("Salvando informações.", {autoclose : 5000, position: "top-right", type: "st-info" });
					
				}, 
			error: function(txt) { 
				$.sticky("Ocorreu um erro com sua solicitação: "+ txt, {autoclose : 5000, position: "top-right", type: "st-error" });
				$("#ajaxrequest").html("Erro" + txt);
				//reloadtable();
				
			},
			success: function(txt){
				$.sticky("Menu Cadastrado.", {autoclose : 5000, position: "top-right", type: "st-success" });
				$("#id").val('');
				$("#NovoRecurso").modal('hide');  
				reloadtable();
				
				
		
			},
		        clearForm: true
				
			});
		}
});

	$(".editar").live('click',function(){
		 idr = $(this).attr('idr');
		 	 
		 $("#id_registro").val(idr);
		 $("#module").val($(this).attr('module'));
		 $("#controller").val($(this).attr('controller'));
		 $("#action").val($(this).attr('action'));
		 $("#parans").val($(this).attr('parans'));
		 $("#nome").val($(this).attr('nomemenu'));
		 $("#position").val($(this).attr('position'));
		 $("#NovoRecurso").modal('show');  

	});

	
});

function reloadtable(){
	$("#listaclientes").dataTable().fnDraw(); 
}

	</script>