<div class="row-fluid">
<div class="span12">
<h3 class="heading">Status de Tickets
<span class="pull-right"><i style="cursor:pointer" class="splashy-document_a4_new newdepto ttip_b" title="Novo Status"></i></span></h3>
<table id="listaclientes" class="table table-striped table-bordered">
<thead>
<tr>
<th width="5%">ID</th>
<th width="30%">Nome</th>
<th width="10%">Cor</th>
<th width="5%">Aberto</th>
<th width="5%">Fechado</th>
<th width="5%">Suspenso</th>
<th width="5%">Pendente</th>
<th width="5%">Opções</th>
</tr>
</thead>
<tbody>
<?php foreach($this->dados as $dado){ ?>
<tr>
<td ><?php echo $dado->id_registro ?></td>
<td ><?php echo $dado->descritivo ?></td>
<td ><?php echo $dado->color ?></td>
<td ><i style="cursor:pointer" class="<?php if($dado->isdefault == 1){  echo "splashy-star_full"; }else{  echo "splashy-star_empty"; }?> toggledefault"></i></td>
<td><i style="cursor:pointer" class="<?php if($dado->isclosed == 1){  echo "splashy-star_full"; }else{  echo "splashy-star_empty"; }?> toggleclosed"></i></td>
<td ><i style="cursor:pointer" class="<?php if($dado->issuspended == 1){  echo "splashy-star_full"; }else{  echo "splashy-star_empty"; }?> togglesuspended"></i></td>
<td><i style="cursor:pointer" class="<?php if($dado->ispendent == 1){  echo "splashy-star_full"; }else{  echo "splashy-star_empty"; }?> togglependent"></i></td>
<td ><i class="splashy-hcards_edit editdepto"  idreg="<?php echo  $dado->id_registro ?>" style="cursor:pointer" ></i> <i class="splashy-hcards_remove removedepto" idreg="<?php echo $dado->id_registro ?>" style="cursor:pointer" ></i></span></td>
</tr>
<?php }; ?>
</tbody>
</table>
</div>
</div>

<div class="modal hide fade" id="NewDepto">
   <div class="modal-header">
                        <button class="close" data-dismiss="modal">×</button>
                        <h3>Status:</h3>
                    </div>
<form id="newreply" name="newreply" enctype="id_note" class="form-horizontal" method="post" action="/system/configurator/newticketstatus">
<input type="hidden" name="id_registro" value="0" id="id_registro">
<div class="modal-body">
<div class="row-fluid formSep">
		<div class="span4">
		<label for="assuntoticket" class="optional">Nome:</label>
		<input type="text" name="descritivo" id="descritivo" class="span12" >
		</div>
		<div class="span4">
		<label for="assuntoticket" class="optional">Cor</label>
		<input type="text" name="color" id="color" class="span12" >
		</div>
		<div class="span4">
		<label for="assuntoticket" class="optional">Tipo Status</label>
		<select name="typestatus" class="span12" id="typestatus">
	    <option value="1"> Aberto </otion>
	    <option value="2"> Fechado </otion>
	    <option value="3"> Suspenso </otion>
	    <option value="4"> Pendente </otion>
		</select>
		</div>
		</div>
				  
</div>
<div class="modal-footer">
<div style="text-align:right">
<a href="javascript:void(0)" class="btn btn-large btn-warning" data-dismiss="modal">Cancelar</a>
<input type="submit" name="submit" id="submiteditnote" value="Salvar" class="btn btn-large btn-primary">
</div>		
</form>
</div>
</div>

<script>
$().ready(function(){

	$('#color').colorpicker();

	$('#listaclientes').dataTable({
		"oLanguage": {
			"sUrl": "/js/datatable_ptbr.txt"
		},
		"sPaginationType": "bootstrap"
                     	
                    
    });

    $(".newdepto").click(function(){
	    $("#NewDepto").modal('show');    
		
    });

    $(".editdepto").click(function(){
        id = $(this).attr('idreg');

   	 $.ajax({ 
			type: "GET", 
			url: "/system/configurator/getstatusticketdata/id/"+ id , 
			data: "undo="+ id,
			beforeSend: function() {
								
	 		}, 
			success: function(txt) {
			
				var retorno = jQuery.parseJSON(txt);	
				$("#id_registro").val(retorno.id_registro);
				$("#descritivo").val(retorno.descritivo);
				$("#color").val(retorno.color);
				$("#NewDepto").modal('show');  	

														
			}, 
			error: function(txt) { 
				$.sticky("UM ERRO DE SISTEMA OCORREU.", { type: 'st-error' });
			} 
		}); 

    });

    $(".removedepto").click(function(){
  	  	id = $(this).attr('idreg');
  	  	if(confirm("Deseja Realmente excluir este Status?")){
    	 document.location.href="/system/configurator/removestatusticket/id/"+id;
  	  	}
  	  

    });

    


});


</script>
