<div class="row-fluid">
<div class="span12">
<h3 class="heading">Status de Tickets
<span class="pull-right"><i style="cursor:pointer" class="splashy-document_a4_new newdepto ttip_b" title="Novo Status"></i></span></h3>
<table id="listaclientes" class="table table-striped table-bordered">
<thead>
<tr>
<th width="5%">ID</th>
<th width="5%">Nome</th>
<th width="30%">Cor</th>
<th width="10%">Aberto</th>
<th width="10%">Fechado</th>
<th width="10%">Suspenso</th>
<th width="10%">Pendente</th>
<th width="5%">Opções</th>
</tr>
</thead>
<tbody>
<?php foreach($this->dados as $dado){ ?>
<tr>
<td width="5%"><?php echo $dado->id_registro ?></td>
<td width="5%"><?php echo $dado->descritivo ?></td>
<td width="30%"><?php echo $dado->color ?></td>
<td width="10%"><i style="cursor:pointer" class="<?php if($dado->isdefault == 1){  echo "splashy-star_full"; }else{  echo "splashy-star_empty"; }?>"></i></td>
<td width="10%"><i style="cursor:pointer" class="<?php if($dado->idclosed == 1){  echo "splashy-star_full"; }else{  echo "splashy-star_empty"; }?>"></i></td>
<td width="10%"><i style="cursor:pointer" class="<?php if($dado->issuspended == 1){  echo "splashy-star_full"; }else{  echo "splashy-star_empty"; }?>"></i></td>
<td width="10%"><i style="cursor:pointer" class="<?php if($dado->ispendent == 1){  echo "splashy-star_full"; }else{  echo "splashy-star_empty"; }?>"></i></td>
<td width="5%"><i class="splashy-hcards_edit editdepto"  idreg="<?php echo  $dado->id_registro ?>" style="cursor:pointer" ></i> <i class="splashy-hcards_remove removedepto" idreg="<?php echo $dado->id_registro ?>" style="cursor:pointer" ></i></span></td>
</tr>
<?php }; ?>
</tbody>
</table>
</div>
</div>

<div class="modal hide fade" id="NewDepto">
   <div class="modal-header">
                        <button class="close" data-dismiss="modal">×</button>
                        <h3>Departamentos:</h3>
                    </div>
<form id="newreply" name="newreply" enctype="id_note" class="form-horizontal" method="post" action="/system/configurator/newdepto">
<input type="hidden" name="id_registro" value="0" id="id_registro">
<div class="modal-body">
<div class="row-fluid formSep">
		<div class="span4">
		<label for="assuntoticket" class="optional">Nome Departamento:</label>
		<input type="text" name="nomedepto" id="nomedepto" class="span12" >
		</div>
		<div class="span4">
		<label for="assuntoticket" class="optional">Gerente</label>
		<select name="deptolider" class="span12" id="deptolider">
		<?php
		$deptos = System_Model_Users::renderCombo();
		foreach($deptos as $key=>$value){
		echo "<option value=\"$key\"> $value </otion>";
		}
		?>
		</select>
		</div>
		<div class="span4">
		<label for="assuntoticket" class="optional">Tipo de Departamento</label>
		<select name="deptotype" class="span12" id="deptotype">
	    <option value="1"> Público </otion>
	    <option value="2"> Privado </otion>
		</select>
		</div>
		</div>
		
		
		<div class="row-fluid formSep">
		
		
		<div class="span4">
		<label for="assuntoticket" class="optional">Email</label>
		<input type="text" name="deptoemail" id="deptoemail" class="span12" >
		</div>
		<div class="span3">
		<label for="assuntoticket" class="optional">Servidor</label>
		<input type="text" name="deptomailserver" id="deptomailserver" class="span12" >
		</div>
		<div class="span3">
		<label for="assuntoticket" class="optional">Senha</label>
		<input type="text" name="deptomailpassword" id="deptomailpassword" class="span12" >
		</div>
		
		<div class="span1">
		<label for="assuntoticket" class="optional">Porta</label>
		<input type="text" name="deptomailserverport" id="deptomailserverport" class="span12" >
		</div>
			
		</div>
  
</div>
<div class="modal-footer">
<div style="text-align:right">
<a href="javascript:void(0)" class="btn btn-large btn-warning" data-dismiss="modal">Cancelar</a>
<input type="submit" name="submit" id="submiteditnote" value="Salvar" class="btn btn-large btn-primary">
</div>		
</form>
</div>
</div>

<script>
$().ready(function(){

	$('#listaclientes').dataTable({
		"oLanguage": {
			"sUrl": "/js/datatable_ptbr.txt"
		},
		"sPaginationType": "bootstrap"
                     	
                    
    });

    $(".newdepto").click(function(){
	    $("#NewDepto").modal('show');    
		
    });

    $(".editdepto").click(function(){
        id = $(this).attr('idreg');

   	 $.ajax({ 
			type: "GET", 
			url: "/system/configurator/getdeptodata/id/"+ id , 
			data: "undo="+ id,
			beforeSend: function() {
								
	 		}, 
			success: function(txt) {
			
				var retorno = jQuery.parseJSON(txt);	
				$("#id_registro").val(retorno.id_registro);
				$("#nomedepto").val(retorno.nomedepto);
				$("#deptoemail").val(retorno.deptoemail);
				$("#deptomailserver").val(retorno.deptomailserver);
			    $("#deptomailpassword").val(retorno.deptomailpassword);
				$("#deptomailserverport").val(retorno.deptomailserverport);
				$("#NewDepto").modal('show');  	

														
			}, 
			error: function(txt) { 
				$.sticky("UM ERRO DE SISTEMA OCORREU.", { type: 'st-error' });
			} 
		}); 

    });

    $(".removedepto").click(function(){
  	  	id = $(this).attr('idreg');
  	  	if(confirm("Deseja Realmente excluir este Status?")){
    	 document.location.href="/system/configurator/removedepto/id/"+id;
  	  	}
  	  

    });

    


});


</script>
