<div class="row-fluid">
<div class="span12">
<h3 class="heading">Tipos de Pessoas
<span class="pull-right"><i style="cursor:pointer" class="splashy-document_a4_new newdepto ttip_b" title="Novo Tipo de Cadastro"></i></span></h3>
<table id="listaclientes" class="table table-striped table-bordered">
<thead>
<tr>
<th width="5%"></th>
<th width="5%">ID</th>
<th width="85%">Tipo</th>
<th width="5%">Opções</th>
</tr>
</thead>
<tbody>
<?php foreach($this->dados as $dado){ ?>
<tr>
<td width="5%"><i style="cursor:pointer" class="<?php if($dado->isdefault == 1){  echo "splashy-star_full"; }else{  echo "splashy-star_empty"; }?>"></i></td>
<td width="5%"><?php echo $dado->id_registro ?></td>
<td width="85%"><?php echo $dado->descricao ?></td>
<td width="5%"><i class="splashy-hcards_edit editdepto"  idreg="<?php echo  $dado->id_registro ?>" style="cursor:pointer" ></i> <i class="splashy-hcards_remove removedepto" idreg="<?php echo $dado->id_registro ?>" style="cursor:pointer" ></i></span></td>
</tr>
<?php }; ?>
</tbody>
</table>
</div>
</div>

<div class="modal hide fade" id="NewDepto">
   <div class="modal-header">
                        <button class="close" data-dismiss="modal">×</button>
                        <h3>Tipos de Pessoas:</h3>
                    </div>
<form id="newreply" name="newreply" enctype="id_note" class="form-horizontal" method="post" action="/system/configurator/newtipopessoa">
<input type="hidden" name="id_registro" value="0" id="id_registro">
<div class="modal-body">
<div class="row-fluid formSep">
		<div class="span12">
		<label for="tipoticket" class="optional">Tipo de Pessoa:</label>
		<input type="text" name="descricao" id="descricao" class="span12" >
		</div>		
					  
</div>
<div class="modal-footer">
<div style="text-align:right">
<a href="javascript:void(0)" class="btn btn-large btn-warning" data-dismiss="modal">Cancelar</a>
<input type="submit" name="submit" id="submiteditnote" value="Salvar" class="btn btn-large btn-primary">
</div>		
</form>
</div>
</div>

<script>
$().ready(function(){

	$('#listaclientes').dataTable({
		"oLanguage": {
			"sUrl": "/js/datatable_ptbr.txt"
		},
		"sPaginationType": "bootstrap"
                     	
                    
    });

    $(".newdepto").click(function(){
	    $("#NewDepto").modal('show');    
		
    });

    $(".editdepto").click(function(){
        id = $(this).attr('idreg');

   	 $.ajax({ 
			type: "GET", 
			url: "/system/configurator/gettipopessoadata/id/"+ id , 
			data: "undo="+ id,
			beforeSend: function() {
								
	 		}, 
			success: function(txt) {
			
				var retorno = jQuery.parseJSON(txt);	
				$("#id_registro").val(retorno.id_registro);
				$("#descricao").val(retorno.descricao);
				$("#NewDepto").modal('show');  	

														
			}, 
			error: function(txt) { 
				$.sticky("UM ERRO DE SISTEMA OCORREU.", { type: 'st-error' });
			} 
		}); 

    });

    $(".removedepto").click(function(){
  	  	id = $(this).attr('idreg');
  	  	if(confirm("Deseja Realmente excluir este tipo de pessoa?")){
    	 document.location.href="/system/configurator/removetipopessoa/id/"+id;
  	  	}
  	  

    });

    


});


</script>
