<form id="servicos" name="servicos" enctype="application/x-www-form-urlencoded" class="form-horizontal" method="post" action="">


<fieldset id="fieldset-clientes" class="form-horizontal">
<div class="row-fluid">
<div class="span3">
<?php 
echo $this->form->tiposervico;
?>
</div>


<div class="span3">
<?php 
echo $this->form->nomeservico;
?>
</div>

<div class="span3">
<?php
 echo $this->form->valorservico;
?>
</div>

<div class="span3">
<?php
 echo $this->form->iss;
?>
</div>
</div>
</fieldset>
<div class="row-fluid">
<fieldset id="fieldset-botoes">
<div style="text-align:right">
<input type="reset" name="limpar" id="limpar" value="Limpar" class="btn btn-large btn-warning">
<input type="submit" name="submit" id="submit" value="Salvar" class="btn btn-large btn-primary">
</div>
</fieldset>
</div>

</form>
<script>
$().ready(function(){
	$('#servicos').validate({
		onkeyup: false,
		errorClass: 'error',
		validClass: 'valid',
		highlight: function(element) {
			$(element).closest('div').addClass("f_error");
		},
		unhighlight: function(element) {
			$(element).closest('div').removeClass("f_error");
		},
        errorPlacement: function(error, element) {
            $(element).closest('div').append(error);
        },
      
        invalidHandler: function(form, validator) {
			$.sticky("Existem campos obrigatórios não preenchidos no formulário, corrija estes erros e tente novamente.", {autoclose : 5000, position: "top-right", type: "st-error" });
		}
    });

    $("#tiposervico").chosen();
    $("#iss").chosen();

});

    </script>