<div class="row-fluid">
<div class="span12">
<h3 class="heading">Produtos Compostos <small>Nesta listagem somente os produtos que já possuem um composto são exibidos!</small></h3>
<table id="listaclientes" class="table table-striped table-bordered">
<thead>
<tr>
<th width="5%">ID</th>
<th width="5%">Cod Int</th>
<th width="10%">Categoria</th>
<th width="10%">Sub-Categoria</th>
<th width="45%">Produto</th>
<th width="15%">Referência</th>
<th width="5%">Estoque</th>
<th width="5%">Opções</th>
</tr>
</thead>
<tbody>
<tr>
<td class="dataTables_empty" colspan="6">Não existem dados nessa consulta!</td>
</tr>
</tbody>
</table>
</div>
</div>
<script>
$().ready(function(){

	$('#listaclientes').dataTable({
		"oLanguage": {
			"sUrl": "/js/datatable_ptbr.txt"
		},
		"sPaginationType": "bootstrap",
        "bProcessing": true,
		"bServerSide": true,
		 "sAjaxSource": "/system/datatables/lista-produtos-compostos"
               	
                    
    });


});


</script>