
<?php
/**
 * Este arquivo é parte do projeto SysAdmin - ERP em PHP
 *
 * Este programa é um software livre: você pode redistribuir e/ou modificá-lo
 * sob os termos da Licença Pública Geral GNU (GPL)como é publicada pela Fundação
 * para o Software Livre, na versão 3 da licença, ou qualquer versão posterior
 * e/ou 
 * sob os termos da Licença Pública Geral Menor GNU (LGPL) como é publicada pela Fundação
 * para o Software Livre, na versão 3 da licença, ou qualquer versão posterior.
 *
 *
 * Este programa é distribuído na esperança que será útil, mas SEM NENHUMA
 * GARANTIA; nem mesmo a garantia explícita definida por qualquer VALOR COMERCIAL
 * ou de ADEQUAÇÃO PARA UM PROPÓSITO EM PARTICULAR,
 * veja a Licença Pública Geral GNU para mais detalhes.
 *
 * Você deve ter recebido uma cópia da Licença Publica GNU e da 
 * Licença Pública Geral Menor GNU (LGPL) junto com este programa.
 * Caso contrário consulte <http://www.fsfla.org/svnwiki/trad/GPLv3> ou
 * <http://www.fsfla.org/svnwiki/trad/LGPLv3>. 
 *
 * @package   SysAdmin
 * @name      
 * @version   1.0.0
 * @license   http://www.gnu.org/licenses/gpl.html GNU/GPL v.3
 * @copyright 2009-2012 &copy; SysAdmin
 * @link      http://www.cepheros.com.br
 * @author    Daniel R. Chaves <dchaves at 32dll dot com dot br>
 *
 */
 
/**
 * Nesta função iremos baixar a imagem do captcha
 *
 * Parametro $url:
 *   Coloque a url que o captcha usa para reproduzir a imagem
 * Parametro $arquivo:
 *   Coloque o arquivo para salvar a imagem.
 *   IMPORTANTE que o arquivo já exista e tenha permissão CHMOD 777
 */
//unlink("receita.gif");
function recebe_imagem($url, $arquivo) {
	
	$cookie = APPLICATION_PATH.'/data/temp/receita.txt'; //Importantissimo que o caminho esteja correto e com permissão CHMOD 777

	$ch = curl_init ();

	curl_setopt_array($ch, array(
	CURLOPT_URL => $url, //url que produz a imagem do captcha.
	CURLOPT_COOKIEFILE => $cookie, //esse mais o debaixo fazem a mágica do captcha
	CURLOPT_COOKIEJAR => $cookie,  //esse mais o de cima fazem a mágica do.. ah já falei isso;
	CURLOPT_FOLLOWLOCATION => 1, //não sei, mas funciona :D
	CURLOPT_RETURNTRANSFER => 1, //retorna o conteúdo.
	CURLOPT_BINARYTRANSFER => 1, //essa tranferencia é binária.
	CURLOPT_HEADER => 0, //não imprime o header.
	));

	$data = curl_exec($ch);

	curl_close ($ch);

	//salva a imagem
	$fp = fopen($arquivo,'w');
	fwrite($fp, $data);
	fclose($fp);

	//retorna a imagem
	return $arquivo;
}

//Então vamos pegar a imagem
$img = recebe_imagem("http://www.receita.fazenda.gov.br/scripts/srf/intercepta/captcha.aspx?opt=image", "receita.gif");

//E criar o formulário que mostra a imagem + o campo de inserção do CNPJ
print "<img src='{$img}' />" .
'<form action="/default/index/receitarespond" method="POST">
         captcha
         <input size="8" maxlength="4" name="captcha">
         cnpj
         <input size="16" maxlength="14" name="cnpj">
         <input type="submit">
      </form>';

?>