<div class="row-fluid">
<div class="span12">
<h3 class="heading">Lista de Usuários </h3>
<table id="listaclientes" class="table table-striped table-bordered">
<thead>
<tr>
<th width="5%">ID</th>
<th width="30%">Nome Completo</th>
<th width="20%">Email</th>
<th width="30%">Celular</th>
<th width="30%">Tipo</th>
<th width="5%">Opções</th>
</tr>
</thead>
<tbody>
<tr>
<td class="dataTables_empty" colspan="6">Não existem dados nessa consulta!</td>
</tr>
</tbody>
</table>
</div>
</div>
<script>
$().ready(function(){

	$('#listaclientes').dataTable({
		"oLanguage": {
		"sUrl": "/js/datatable_ptbr.txt"
		},
		 "aaSorting": [[1,'asc']],
		"sPaginationType": "bootstrap",
		"bProcessing": true,
		"bServerSide": true,
		"sAjaxSource": "/system/datatables/usuarios"


	});


	
});


	</script>