<div class="row-fluid">
<div class="span12">
<h3 class="heading">Etapas de Produção
<span class="pull-right"><i style="cursor:pointer" class="splashy-document_a4_new newdepto ttip_b" title="Nova Etapa de Produção"></i></span></h3>
<table id="listaclientes" class="table table-striped table-bordered">
<thead>
<tr>
<th width="10%">ID</th>
<th width="40%">Nome</th>
<th width="40%">Tipo</th>
<th width="10%">Opções</th>
</tr>
</thead>
<tbody>
<?php foreach($this->dados as $dado){ ?>
<tr>
<td width="10%"><?php echo $dado->id_registro ?></td>
<td width="40%"><?php echo $dado->nomeetapa ?></td>
<td width="40%"><?php echo $dado->tipoetapa ?></td>
<td width="10%"><a data-toggle="modal" href="/system/producao/edita-etapa/id/<?php echo $dado->id_registro ?>" data-target="#EditarMod">
<i class="splashy-hcards_edit editdepto"  idreg="<?php echo  $dado->id_registro ?>" ></i></a> <i class="splashy-hcards_remove removedepto" idreg="<?php echo $dado->id_registro ?>" style="cursor:pointer" ></i></td>
</tr>
<?php }; ?>
</tbody>
</table>
</div>
</div>


  <div class="modal hide fade" id="editaModal">
 <form id="cancelalancamento" name="cancelalancamento" method="post" action="/system/producao/salva-etapa">
 <div class="modal-header">
   <button class="close" data-dismiss="modal">×</button>
   <h3>Editar Etapa</h3>
   </div>
 <div class="modal-body">
 </div>
 
  <div class="modal-footer">
<input type="submit" name="submit" id="submiteditnote" value="CONFIRMAR" class="btn btn-large btn-primary">
</div>
</form>
 </div>

<div class="modal hide fade" id="NewDepto">
   <div class="modal-header">
   <button class="close" data-dismiss="modal">×</button>
   <h3>Etapas de Produção:</h3>
   </div>
<form id="newreply" name="newreply" enctype="id_note" class="form-horizontal" method="post" action="/system/producao/salva-etapa">
<input type="hidden" name="id_registro" value="0" id="id_registro">
<div class="modal-body">
<div class="row-fluid formSep">
		<div class="span6">
		<label for="assuntoticket" class="optional">Nome:</label>
		<input type="text" name="nomeetapa" id="nomeetapa" class="span12" >
		</div>
		
		<div class="span6">
		<label for="tipoetapa" class="optional">Tipo:</label>
		<select name="tipoetapa" id="tipoetapa">
		<option value="Interna">Interna</option>
		<option value="Externa">Externa</option>
		<option value="Outros">Outros</option>
		
		</select>
		</div>
		</div>
		  
</div>

<div class="modal-footer">
<div style="text-align:right">
<a href="javascript:void(0)" class="btn btn-large btn-warning" data-dismiss="modal">Cancelar</a>
<input type="submit" name="submit" id="submiteditnote" value="Salvar" class="btn btn-large btn-primary">
</div>	</div>	
</form>
</div>


<div class="modal hide fade" id="DeletaModal">
 <form id="cancelalancamento" name="cancelalancamento" method="post" action="/system/producao/etapas">
 <div class="modal-header">
   <button class="close" data-dismiss="modal">×</button>
   <h3>Confirmar Cancelamento:</h3>
   </div>
 <div class="modal-body">
 
 <div class="alert alert-error"><strong>Para excluir a etapa digite as palavras na caixa abaixo:</strong></div>
  <input type="hidden" name="id_registro" id="iddeleta" value="">
 	<div id="ModelPre"><?php 
 echo Functions_Auxilio::renderCaptcha()->getHtml();
 ?></div>
 

 </div>
  <div class="modal-footer">
<input type="submit" name="submit" id="submiteditnote" value="CONFIRMAR" class="btn btn-large btn-primary">
</div>
</form>
 </div>


<script>
$().ready(function(){

	$('#listaclientes').dataTable({
		"oLanguage": {
			"sUrl": "/js/datatable_ptbr.txt"
		},
		"sPaginationType": "bootstrap"
                     	
                    
    });

    $(".newdepto").click(function(){
	    $("#NewDepto").modal('show');    
		
    });

   

    $(".removedepto").click(function(){
    	id= $(this).attr('idreg');
		$("#iddeleta").val(id);
		 showRecaptcha('ModelPre');
		$("#DeletaModal").modal('show');
  	});

    $("a[data-target=#EditarMod]").live('click',function(ev) {
	    ev.preventDefault();
	    var target = $(this).attr("href");

	    // load the url and show modal on success
	    $("#editaModal .modal-body").load(target, function() { 
	         $("#editaModal").modal("show"); 
	    });
	});	


});

function showRecaptcha(element) {
    Recaptcha.create("6Ldk6-ISAAAAALqcpxh2182Y0Yd8ZqHr2p_QIGoO", element, {
      theme: "white",
      lang :"pt",
      callback: Recaptcha.focus_response_field});
  }

</script>
