<div class="row-fluid">
 <div class="span12">
<div class="heading clearfix">
<h3>Processameto de Comissões <span class="pull-right"><div id="ajax_proccess"></div></span></h3>
</div>
<form id="ProcessaComissoes" action="/erp/financeiro/processa-comissoes" method="post">
<div class="row-fluid formSep">
<div class="span2">
<label>Data Inicial</label>
<input type="text" name="datainicial" id="datainicial" class="span12 required" placeholder="dd/mm/yyyy">
</div>
<div class="span2">
<label>Data Final</label>
<input type="text" name="datafinal" id="datafinal" class="span12 required" placeholder="dd/mm/yyyy">
</div>

<div class="span2">
<label>Data Pagamento</label>
<input type="text" name="datapagamento" id="datapagamento" class="span12 required" placeholder="dd/mm/yyyy">
</div>

<div class="span1">
<label> <a class="pop_over" data-placement="top" data-original-title="Processa Devoluções" data-content="Debita da comissão os valores de vendas devolvidas ou canceladas pelo cliente, bem como adiantamentos realizados" href="#"> Devoluções?</a></label>
<input type="hidden" name="processadev" value="0">
<div id="processadev_toggle">
<input type="checkbox" value="1" name="processadev" id="processadev" checked="checked">
</div>
</div>

<div class="span1">
<label><a class="pop_over" data-placement="top" data-original-title="Somente Recebidos" data-content="Processa somente as comissões de parcelas já recebidas pelo sistema" href="#"> Recebidos? </a></label>
<input type="hidden" name="somenterecebidos" value="0">
<div id="somenterecebidos_toggle">
<input type="checkbox" value="1" name="somenterecebidos" id="somenterecebidos" checked="checked">
</div>
</div>

<div class="span1">
<label><a class="pop_over" data-placement="top" data-original-title="Efetuar Lançamentos?" data-content="Efetua o lançamento no contas a pagar do valor total apurado de comissoes" href="#">Lançar?</a></label>
<input type="hidden" name="lancarpagamentos" value="0">
<div id="lancarpagamenbtos_toggle">
<input type="checkbox" value="1" name="lancarpagamentos" id="lancarpagamenbtos" checked="checked">
</div>
</div>

<div class="span3">
<label> </label>
<input type="submit" name="submit" value="Processar" class="btn-large btn-gebo" >
</div>

</div>
							
</form>
</div>
							
</div>


<div class="row-fluid">
 <div class="span12">
 <div class="heading clearfix">
<h3 class="pull-left">Comissões Processadas</h3>
</div>
<div class="row-fluid formSep">

<div class="span3">
<label for="datainicial">Data Inicial</label>
<div class="input-append">
<input type="text" name="datainicial" id="datainicial_table" class="span8">
<span class="add-on"><i class="splashy-error_do_not_small limpadatainicial" title="Limpar"></i></span>
</div>
</div>

<div class="span3">
<label for="datafinal">Data Final</label>
<div class="input-append">
<input type="text" name="datafinal" id="datafinal_table" class="span8">
<span class="add-on"><i class="splashy-error_do_not_small limpadatafinal" title="Limpar"></i></span>
</div>
</div>

<div class="span3">
<label for="datafinal">Representante</label>
<select name="conta" id="conta_table"><?php 
$empresas = Cadastros_Model_Pessoas::renderCombo('4');
	foreach($empresas as $key=>$value){
		echo "<option value=\"$key\"> $value </otion>";
	} ?>
</select>
</div>


</div>
<table id="tablecomissoes" class="table table-striped">
<thead>
<tr>
<th width="2%">Seq</th>
<th width="15%">Vendedor/Representante</th>
<th width="5%">Data</th>
<th width="2%">Pedido</th>
<th width="40%">Observações:</th>
<th width="10%">Vl Comissao:</th>
<th width="10%">Saldo:</th>
<th width="2%">Opt</th>
</tr>
</thead>
<tbody>
<tr>
<td class="dataTables_empty" colspan="8">Não existem dados nessa consulta!</td>
</tr>
</tbody>
</table>

</div>
							
</div>

<script>

$().ready(function(){

	var oTable = $('#tablecomissoes').dataTable({
		"oLanguage": {
			"sUrl": "/js/datatable_ptbr.txt"
		},
		"sPaginationType": "bootstrap",
		"bProcessing": true,
		"bServerSide": true,
		"sAjaxSource": "/system/datatables-financeiro/fluxo-comissoes",
		"aoColumns": [
		              { "bSortable": true },
		              { "bSortable": true },
		              { "bSortable": true },
		              { "bSortable": true },
		              { "bSortable": true },
		              { "bSortable": false },
		              { "bSortable": false, "bSearchable": false },
		              { "bSortable": false, "bSearchable": false },              
		            ],
	    "fnServerData": function ( sSource, aoData, fnCallback ) {
	            /* Add some data to send to the source, and send as 'POST' */
	            aoData.push( { "name": "datainicial", "value": $('#datainicial_table').val() } );
	            aoData.push( { "name": "datafinal", "value": $('#datafinal_table').val() } );
	            aoData.push( { "name": "vendedor", "value": $('#conta_table').val() } );
	           $.ajax( {
	                "dataType": 'json',
	                "type": "GET",
	                "url":  "/system/datatables-financeiro/fluxo-comissoes",
	                "data": aoData,
	                "success": fnCallback
	            } );
	        }
	  } );
	
	$('#datainicial_table').change( function () { oTable.fnFilter( $(this).val(), 0 );} );
    $('#datafinal_table').change( function () { oTable.fnFilter( $(this).val(), 0 );} );
    $('#conta_table').change( function () { oTable.fnFilter( $(this).val(), 0 );} );
    
	$('#ProcessaComissoes').validate({
		onkeyup: false,
		errorClass: 'error',
		validClass: 'valid',
		highlight: function(element) {
			$(element).closest('div').addClass("f_error");
		},
		unhighlight: function(element) {
			$(element).closest('div').removeClass("f_error");
		},
  errorPlacement: function(error, element) {
      $(element).closest('div').append(error);
  },

  invalidHandler: function(form, validator) {
			$.sticky("Existem campos obrigatórios não preenchidos no formulário, corrija estes erros e tente novamente.", {autoclose : 5000, position: "top-right", type: "st-error" });
		},
		submitHandler: function(form) {
			jQuery(form).ajaxSubmit({
				target: "#ajax_proccess",
				beforeSubmit:   function(){ 
					$("#ajax_proccess").html("<img src='/img/ajax_loader.gif'>");
					$.sticky("Salvando informações.", {autoclose : 5000, position: "top-right", type: "st-info" });
					
				}, 
			error: function(txt) { 
				$.sticky("Ocorreu um erro com sua solicitação: "+ txt, {autoclose : 5000, position: "top-right", type: "st-error" });
				$("#ajax_proccess").html("");
				//reloadtable();
				
			},
			success: function(txt){
				$.sticky(txt, {autoclose : 5000, position: "top-right", type: "st-success" });
				$("#ajax_proccess").html("");
			//	$("#NovoLancamentoModal").modal('hide');  
				reloadtable();
				
				
		
			},
		        clearForm: false
				
			});
		}
});

$('#datapagamento').datepicker({language:"br", format: "dd/mm/yyyy"});

$('#datainicial').datepicker({language:"br", format: "dd/mm/yyyy"}).on('changeDate', function(ev){
	var dateText = $(this).val();
	
	var endDateTextBox = $('#datafinal');
	if (endDateTextBox.val() != '') {
		var testStartDate = new Date(dateText);
		var testEndDate = new Date(endDateTextBox.val());
		if (testStartDate > testEndDate) {
			endDateTextBox.val(dateText);
		}
	}
	else {
		endDateTextBox.val(dateText);
	};
	$('#datafinal').datepicker('setStartDate', dateText);
	$('#datainicial').datepicker('hide');
});
$('#datafinal').datepicker({language:"br", format: "dd/mm/yyyy"}).on('changeDate', function(ev){
	var dateText = $(this).val();
	var startDateTextBox = $('#datainicial');
	if (startDateTextBox.val() != '') {
		var testStartDate = new Date(startDateTextBox.val());
		var testEndDate = new Date(dateText);
		if (testStartDate > testEndDate) {
			startDateTextBox.val(dateText);
		}
	}
	else {
		startDateTextBox.val(dateText);
	};

	
	$('#datainicial').datepicker('setEndDate', dateText);
	$('#datafinal').datepicker('hide');
});


$("#lancarpagamenbtos_toggle").toggleButtons({
    label: {
	 enabled: "Sim",
	 disabled: "Não"
    }
	 });

$("#somenterecebidos_toggle").toggleButtons({
    label: {
	 enabled: "Sim",
	 disabled: "Não"
    }
	 });

$("#processadev_toggle").toggleButtons({
    label: {
	 enabled: "Sim",
	 disabled: "Não"
    }
	 });


$('#datainicial_table').datepicker({language:"br", format: "dd/mm/yyyy"}).on('changeDate', function(ev){
	var dateText = $(this).val();
	
	var endDateTextBox = $('#datafinal_table');
	if (endDateTextBox.val() != '') {
		var testStartDate = new Date(dateText);
		var testEndDate = new Date(endDateTextBox.val());
		if (testStartDate > testEndDate) {
			endDateTextBox.val(dateText);
		}
	}
	else {
		endDateTextBox.val(dateText);
	};
	$('#datafinal_table').datepicker('setStartDate', dateText);
	$('#datainicial_table').datepicker('hide');
});
$('#datafinal_table').datepicker({language:"br", format: "dd/mm/yyyy"}).on('changeDate', function(ev){
	var dateText = $(this).val();
	var startDateTextBox = $('#datainicial_table');
	if (startDateTextBox.val() != '') {
		var testStartDate = new Date(startDateTextBox.val());
		var testEndDate = new Date(dateText);
		if (testStartDate > testEndDate) {
			startDateTextBox.val(dateText);
		}
	}
	else {
		startDateTextBox.val(dateText);
	};

	
	$('#datainicial_table').datepicker('setEndDate', dateText);
	$('#datafinal_table').datepicker('hide');
});

$("#conta_table").chosen();

$(".limpadatainicial").live('click',function(){
	$('#datainicial_table').val('');
	oTable.fnFilter( $('#datainicial_table').val(), 0 );
});
$(".limpadatafinal").live('click',function(){
	$('#datafinal_table').val('');
	oTable.fnFilter( $('#datafinal_table').val(), 0 );
});

});

function reloadtable(){
	$("#listalancamentos").dataTable().fnDraw(); 
}

</script>
