<?php echo $this->form->id_registro ?>
<?php echo $this->form->id_pessoa ?>
<div class="row-fluid formSep">
<div class="span2">
<?php echo $this->form->id_empresa ?>
</div>
<div class="span10">
<?php echo $this->form->nomelancamento ?>
</div>
<div class="row-fluid formSep">
<div class="span6">
<?php echo $this->form->pessoapagamento ?>
</div>
<div class="span3">
<?php echo $this->form->categoria ?>
</div>

<div class="span3">
<?php echo $this->form->contapadrao ?>
</div>
</div>

<div class="row-fluid formSep">
<div class="span3 well">
<?php echo $this->form->totalgeral ?>
</div>
<div class="span3 well">
<?php echo $this->form->primeirovencimento ?>
</div>
<div class="span3 well">
<?php echo $this->form->tipodocumento ?>
</div>
<div class="span3 well">
<?php echo $this->form->numerodocumento ?>
</div>

</div>

<div class="row-fluid">
<div class="span12">
<h3 class="heading">Parcela</h3>
</div>
<? foreach($this->dadosL as $parcela){ ?>
<div class="row-fluid formsep">
<div class="span2">
<label for="lanc_numerodocumento">Número Documento:</label>
<input type="hidden" name="lanc_id_registro[]" value="<?php echo $parcela->id_registro ?>">
<input type="text" name="lanc_numerodocumento[]" value="<?php echo $parcela->numerodocumento ?>"  class="span12">
</div>
<div class="span2">
<label for="lanc_valororiginal">Valor:</label>
<input type="text" name="lanc_valororiginal[]" value="<?php echo number_format($parcela->valororiginal,2,',','') ?>" class="span12">
</div>
<div class="span2">
<label for="lanc_datavencimento">Vencimento:</label>
<input type="text" name="lanc_datavencimento[]" value="<?php echo Functions_Datas::MyDateTime($parcela->datavencimento) ?>" class="span12">
</div>
<div class="span2">
<label for="lanc_numeroparcela">Parcela:</label>
<input type="text" name="lanc_numeroparcela[]" value="<?php echo $parcela->numeroparcela ?>" class="span6">/<?php echo $parcela->quantidadeparcelas ?>
</div>
<div class="span4">
<label for="lanc_linhadigitavel">Linha Digitavel:</label>
<input type="text" name="lanc_linhadigitavel[]" value="<?php echo $parcela->linhadigitavel ?>" class="span12">
</div>
</div>
<?php } ?>