<div class="row-fluid">
<div class="span12">
<h3 class="heading">Fluxo de Caixa <span class="pull-right"><a data-toggle="modal" href="/erp/financeiro/novo-lancamento-caixa" data-target="#NovoLancamentoModal"><button class="btn btn-gebo">
      Novo Lançamento
    </button></a></span></h3>
</div>
</div>

<div class="row-fluid formSep">

<div class="span3">
<label for="datainicial">Data Inicial</label>
<div class="input-append">
<input type="text" name="datainicial" id="datainicial" class="span8">
<span class="add-on"><i class="splashy-error_do_not_small limpadatainicial" title="Limpar"></i></span>
</div>
</div>

<div class="span3">
<label for="datafinal">Data Final</label>
<div class="input-append">
<input type="text" name="datafinal" id="datafinal" class="span8">
<span class="add-on"><i class="splashy-error_do_not_small limpadatafinal" title="Limpar"></i></span>
</div>
</div>

<div class="span3">
<label for="datafinal">Conta</label>
<select name="conta" id="conta"><?php 
$empresas = Erp_Model_Financeiro_ContaCorrente::getCombo();
	foreach($empresas as $key=>$value){
		echo "<option value=\"$key\" $selected> $value </otion>";
	} ?>
</select>
</div>

<div class="span3">
<label for="somenteconciliados">So Conciliados</label>
<div id="toggle-conciliados" class="toggletbns">
 <input type="checkbox" name="somenteconciliados" id="somenteconciliados" value="">
 </div>
</div>

</div>


<div class="row-fluid">
<div class="span12">
<table id="listalancamentos" class="table table-striped">
<thead>
<tr>
<th width="2%">Cod</th>
<th width="5%">Conta</th>
<th width="2%">Data</th>
<th width="5%">Categoria:</th>
<th width="10%">Pessoa</th>
<th width="5%">Valor:</th>
<th width="5%">Saldo:</th>
<th width="15%">Observações:</th>
<th width="5%">Opções:</th>
</tr>
</thead>
<tbody>
<tr>
<td class="dataTables_empty" colspan="9">Não existem dados nessa consulta!</td>
</tr>
</tbody>
</table>
</div>
</div>



<div class="modal hide fade modal-large" id="NovoLancamentoModal">
 <form id="LancamentoNovo" name="LancamentoNovo" method="post" action="/erp/financeiro/novo-lancamento-caixa">
 <div class="modal-header">
   <button class="close" data-dismiss="modal">×</button>
   <h3>Novo Lancamento:</h3>
   </div>
 <div class="modal-body"></div>
  <div class="modal-footer">
<input type="submit" name="submit" id="submiteditnote" value="Salvar" class="btn btn-large btn-primary">
</div>
</form>
 </div>
 
 
 


<div id="AjaxRequest"></div>

<script>
$().ready(function(){

	 $("a[data-target=#NovoLancamentoModal]").live('click',function(ev) {
		    ev.preventDefault();
		    var target = $(this).attr("href");

		    // load the url and show modal on success
		    $("#NovoLancamentoModal .modal-body").load(target, function() { 
		         $("#NovoLancamentoModal").modal("show"); 
		    });
		});

	$('#LancamentoNovo').validate({
		onkeyup: false,
		errorClass: 'error',
		validClass: 'valid',
		highlight: function(element) {
			$(element).closest('div').addClass("f_error");
		},
		unhighlight: function(element) {
			$(element).closest('div').removeClass("f_error");
		},
  errorPlacement: function(error, element) {
      $(element).closest('div').append(error);
  },

  invalidHandler: function(form, validator) {
			$.sticky("Existem campos obrigatórios não preenchidos no formulário, corrija estes erros e tente novamente.", {autoclose : 5000, position: "top-right", type: "st-error" });
		},
		submitHandler: function(form) {
			jQuery(form).ajaxSubmit({
				target: "#AjaxRequest",
				beforeSubmit:   function(){ 
					$.sticky("Salvando informações.", {autoclose : 5000, position: "top-right", type: "st-info" });
					
				}, 
			error: function(txt) { 
				$.sticky("Ocorreu um erro com sua solicitação: "+ txt, {autoclose : 5000, position: "top-right", type: "st-error" });
				$("#AjaxRequest").html("");
				//reloadtable();
				
			},
			success: function(txt){
				$.sticky(txt, {autoclose : 5000, position: "top-right", type: "st-success" });
				
				$("#NovoLancamentoModal").modal('hide');  
				reloadtable();
				
				
		
			},
		        clearForm: true
				
			});
		}
});



	var oTable = $('#listalancamentos').dataTable({
		"oLanguage": {
			"sUrl": "/js/datatable_ptbr.txt"
		},
		"sPaginationType": "bootstrap",
		"bProcessing": true,
		"bServerSide": true,
		"sAjaxSource": "/system/datatables-financeiro/fluxo-caixa",
	    "fnServerData": function ( sSource, aoData, fnCallback ) {
	            /* Add some data to send to the source, and send as 'POST' */
	            aoData.push( { "name": "datainicial", "value": $('#datainicial').val() } );
	            aoData.push( { "name": "datafinal", "value": $('#datafinal').val() } );
	            aoData.push( { "name": "conta", "value": $('#conta').val() } );
	            aoData.push( { "name": "conciliados", "value": $('#somenteconciliados').val() } );
	            $.ajax( {
	                "dataType": 'json',
	                "type": "GET",
	                "url":  "/system/datatables-financeiro/fluxo-caixa",
	                "data": aoData,
	                "success": fnCallback
	            } );
	        }
	  } );

	 $('#datainicial').change( function () { oTable.fnFilter( $(this).val(), 0 );} );
     $('#datafinal').change( function () { oTable.fnFilter( $(this).val(), 0 );} );
     $('#conta').change( function () { oTable.fnFilter( $(this).val(), 0 );} );
     $('#somenteconciliados').change( function () { oTable.fnFilter( $(this).val(), 0 );} );
                   	
     $('#datainicial').datepicker({language:"br", format: "dd/mm/yyyy"}).on('changeDate', function(ev){
  		var dateText = $(this).val();
  		
  		var endDateTextBox = $('#datafinal');
  		if (endDateTextBox.val() != '') {
  			var testStartDate = new Date(dateText);
  			var testEndDate = new Date(endDateTextBox.val());
  			if (testStartDate > testEndDate) {
  				endDateTextBox.val(dateText);
  			}
  		}
  		else {
  			endDateTextBox.val(dateText);
  		};
  		$('#datafinal').datepicker('setStartDate', dateText);
  		$('#datainicial').datepicker('hide');
  	});
  	$('#datafinal').datepicker({language:"br", format: "dd/mm/yyyy"}).on('changeDate', function(ev){
  		var dateText = $(this).val();
  		var startDateTextBox = $('#datainicial');
  		if (startDateTextBox.val() != '') {
  			var testStartDate = new Date(startDateTextBox.val());
  			var testEndDate = new Date(dateText);
  			if (testStartDate > testEndDate) {
  				startDateTextBox.val(dateText);
  			}
  		}
  		else {
  			startDateTextBox.val(dateText);
  		};

  		
  		$('#datainicial').datepicker('setEndDate', dateText);
  		$('#datafinal').datepicker('hide');
  	});

 	$(".limpadatainicial").live('click',function(){
 		$('#datainicial').val('');
 		oTable.fnFilter( $('#datainicial').val(), 0 );
 	})
 	$(".limpadatafinal").live('click',function(){
 		$('#datafinal').val('');
 		oTable.fnFilter( $('#datafinal').val(), 0 );
 	})

  	$(".validarlanc").live('click',function(){
		 id_lancamento = $(this).attr('idlanc');
		 if(confirm("Deseja Conciliar esse lançamento?")){
			 $.ajax({ 
	    			type: "POST", 
	    			url: "/erp/financeiro/conciliar-lancamento/id/"+id_lancamento, 
	    			data: "other="+id_lancamento,
	    			beforeSend: function() {
	    				$.sticky("CONCILIANDO LANCAMENTO.", { type: 'st-info' });				
	    	 		}, 
	    			success: function(txt) {
	    				$.sticky("LANÇAMENTO CONCILIADO.", { type: 'st-success' });
	    				reloadtable();
	    			}, 
	    			error: function(txt) { 
	    				$.sticky("UM ERRO DE SISTEMA OCORREU.", { type: 'st-error' });
	    			} 
	    		}); 
			 
		 }
	 });

  	$("#toggle-conciliados").toggleButtons({
	     label: {
		 enabled: "Sim",
		 disabled: "Não"
	     },
		 onChange: function ($el, status, e) {
			   if(status){
				   $('#somenteconciliados').val('');
			  }else{
				  $('#somenteconciliados').val('1');
			 }
		 }
		 });

	 $("#conta").chosen();
	

})

function reloadtable(){
	$("#listalancamentos").dataTable().fnDraw(); 
}

</script>