<div class="row-fluid">
 <div class="span6">
							<div class="heading clearfix">
								<h3 class="pull-left">Faturamento <small>Emitir uma Venda</small></h3>
								<span class="pull-right label label-info ttip_t" title="Here is a sample info tooltip">Info</span>
							</div>
							sdfsdfsdf
							</div>
							
							 <div class="span6">
							<div class="heading clearfix">
								<h3 class="pull-left">Saldo Atual <small>Financeiro</small></h3>
								<span class="pull-right label label-info ttip_t" title="Here is a sample info tooltip">Info</span>
							</div>
							sdfsdfsdf
							</div>


</div>

<div class="row-fluid">
 <div class="span6">
							<div class="heading clearfix">
								<h3 class="pull-left">Contas a Receber <small>X</small></h3>
								<span class="pull-right label label-info ttip_t" title="Here is a sample info tooltip">X</span>
							</div>
							sdfsdfsdf
							</div>
							
							 <div class="span6">
							<div class="heading clearfix">
								<h3 class="pull-left">Contas a Pagar <small>X</small></h3>
								<span class="pull-right label label-important ttip_t" title="Here is a sample info tooltip">X</span>
							</div>
							sdfsdfsdf
							</div>


</div>