
<?php
$tipo = $this->tipo;
				switch($tipo){
					case 'abertos':
						$type = 'Em Aberto';
						break;
					case 'liberados':
						$type = 'Recusados';
						break;
					case 'baixados':
						$type = 'Baixados';
						break;
					case 'cancelados':
						$type = 'Cancelados';
					break;
					default:
						$type = 'Em Aberto';
						$tipo = 'abertos';
					break;
				}
				?>
<style>
.modal > form {
    margin-bottom: 0;
}
</style>
<div class="row-fluid">
<div class="span12">
<h3 class="heading">Lançamentos a Receber <small>( <?php echo $type ?> )</small><span class="pull-right"><div class="btn-group">
                                        <button data-toggle="dropdown" class="btn dropdown-toggle">Selecione <span class="caret"></span></button>
                                        <ul class="dropdown-menu">
                                            <li><a href="/erp/financeiro/lista-conta-receber/tipo/abertos">Em Aberto</a></li>
                                            <li><a href="/erp/financeiro/lista-conta-receber/tipo/baixados">Baixados</a></li>
                                            <li class="divider"></li>
                                            <li><a href="/erp/financeiro/lista-conta-receber/tipo/liberados">Recusados</a></li>
                                            <li><a href="/erp/financeiro/lista-conta-receber/tipo/cancelados">Cancelados</a></li>
                                        </ul>
                                    </div></span></h3>
</div>
</div>
<div class="row-fluid">
<div class="span12">
<table id="listalancamentos" class="table table-striped table-bordered">
<thead>
<tr>
<th width="5%">Cod</th>
<th width="5%">Empresa</th>
<th width="15%">Pessoa</th>
<th width="8%">Categoria:</th>
<th width="5%">Parcela</th>
<th width="5%">Valor:</th>
<th width="5%">Vencimento:</th>
<th width="8%">Documento:</th>
<th width="5%">Opções:</th>
</tr>
</thead>
<tbody>
<tr>
<td class="dataTables_empty" colspan="9">Não existem dados nessa consulta!</td>
</tr>
</tbody>
</table>
</div>
</div>

<!-- Modal Window -->

<!-- Printer Modal -->
<div class="modal hide fade" id="PrintLancamento">
 <form id="impressao" name="impressao" method="post" action="/erp/financeiro/imprimir-recebimento" target="_blank">
   <div class="modal-header">
   <button class="close" data-dismiss="modal">×</button>
   <h3>Imprimir:</h3>
   </div>

 <div class="modal-body">
 <div class="alert alert-info">O que você deseja imprimir?.</div>
 <input type="hidden" name="id_lancamento" id="print_id_lancamento" value="">
 <label><input type="radio" name="typeprinter" value="recibo">  Recibo</label>
 <label><input type="radio" name="typeprinter" value="formlib">  Formulário de Liberação</label>
 <label><input type="radio" name="typeprinter" value="parcela">  Esta Parcela</label>
 <label><input type="radio" name="typeprinter" value="lancamento"> Lançamento</label>
 </div>
 <div class="modal-footer">
<input type="submit" name="submit" id="submiteditnote" value="Imprimir" class="btn btn-large btn-primary">
</div>		
</form>
</div>

	<div id="ModelPre"><?php 
 $captcha = new Zend_Service_ReCaptcha('6Ldk6-ISAAAAALqcpxh2182Y0Yd8ZqHr2p_QIGoO','6Ldk6-ISAAAAAHpOarrRAqW6S9uvJEdERs2MgP6h');
 echo $captcha->getHTML() ?></div>

<div class="modal hide fade" id="AllModal">
 <form id="baixaLancamento" name="baixaLancamento" method="post" action="/erp/financeiro/baixar-recebimento">
 <div class="modal-header">
   <button class="close" data-dismiss="modal">×</button>
   <h3>Baixar Lançamento:</h3>
   </div>
 <div class="modal-body"></div>
  <div class="modal-footer">
<input type="submit" name="submit" id="submiteditnote" value="Baixar" class="btn btn-large btn-primary">
</div>
</form>
 </div>
 
 
 <div class="modal hide fade modal-large" id="EditParcModal">
 <form id="editaParcela" name="editaParcela" method="post" action="/erp/financeiro/edita-parcela-receber">
 <div class="modal-header">
   <button class="close" data-dismiss="modal">×</button>
   <h3>Editar Parcela:</h3>
   </div>
 <div class="modal-body"></div>
  <div class="modal-footer">
<input type="submit" name="submit" id="submiteditnote" value="Salvar" class="btn btn-large btn-primary">
</div>
</form>
 </div>
 
  <div class="modal hide fade modal-large" id="EditLancModal">
 <form id="editaLancamento" name="editaLancamento" method="post" action="/erp/financeiro/edita-lancamento-receber">
 <div class="modal-header">
   <button class="close" data-dismiss="modal">×</button>
   <h3>Editar Lançamento:</h3>
   </div>
 <div class="modal-body"></div>
  <div class="modal-footer">
<input type="submit" name="submit" id="submiteditnote" value="Salvar" class="btn btn-large btn-primary">
</div>
</form>
 </div>
 
 
  <div class="modal hide fade" id="CancelModal">
 <form id="cancelalancamento" name="cancelalancamento" method="post" action="/erp/financeiro/cancela-recebimento">
 <div class="modal-header">
   <button class="close" data-dismiss="modal">×</button>
   <h3>Confirmar Cancelamento:</h3>
   </div>
 <div class="modal-body">

 </div>
  <div class="modal-footer">
<input type="submit" name="submit" id="submiteditnote" value="CONFIRMAR" class="btn btn-large btn-primary">
</div>
</form>
 </div>


<div id="ajaxrequest"></div>
<script>
$().ready(function(){

	$("#ModelPre").hide();
	 $(".liberaparcela").live('click',function(){
		 id_parcela = $(this).attr('id_parcela');
		 if(confirm("Deseja Liberar essa parcela para pagamento?")){
			 $.ajax({ 
	    			type: "POST", 
	    			url: "/erp/financeiro/liberar-recebimento/tipo/parcela/id/"+id_parcela, 
	    			data: "other="+id_parcela,
	    			beforeSend: function() {
	    				$.sticky("SOLICITANDO LIBERAÇÃO DE PARCELA.", { type: 'st-info' });				
	    	 		}, 
	    			success: function(txt) {
	    				$.sticky("PARCELA LIBERADA PARA PAGAMENTO.", { type: 'st-success' });
	    			
	    				reloadtable();
	    			}, 
	    			error: function(txt) { 
	    				$.sticky("UM ERRO DE SISTEMA OCORREU.", { type: 'st-error' });
	    			} 
	    		}); 
		 }
	 });

	 $(".liberalancamento").live('click',function(){
		 id_lancamento = $(this).attr('id_lancamento');
		 if(confirm("Deseja Liberar todas as parcelas deste lançamento para pagamento?")){
			 $.ajax({ 
	    			type: "POST", 
	    			url: "/erp/financeiro/liberar-recebimento/tipo/lancamento/id/"+id_lancamento, 
	    			data: "other="+id_parcela,
	    			beforeSend: function() {
	    				$.sticky("SOLICITANDO LIBERAÇÃO DE LANÇAMENTO.", { type: 'st-info' });				
	    	 		}, 
	    			success: function(txt) {
	    				$.sticky("PARCELAS LIBERADAS PARA PAGAMENTO.", { type: 'st-success' });
	    				    				reloadtable();
	    			}, 
	    			error: function(txt) { 
	    				$.sticky("UM ERRO DE SISTEMA OCORREU.", { type: 'st-error' });
	    				alert(txt);
	    			} 
	    		}); 
		 }
	 });

	 $(".recusaparcela").live('click',function(){
		 id_parcela = $(this).attr('id_parcela');
		 if(confirm("Deseja recusar essa parcela para pagamento?")){
			  $.ajax({ 
		    			type: "POST", 
		    			url: "/erp/financeiro/bloqueia-recebimento/tipo/parcela/id/"+id_parcela, 
		    			data: "other="+id_parcela,
		    			beforeSend: function() {
		    				$.sticky("SOLICITANDO BLOQUEIO DE PARCELA.", { type: 'st-info' });				
		    	 		}, 
		    			success: function(txt) {
		    				$.sticky("PARCELA BLOQUEADA PARA PAGAMENTO.", { type: 'st-success' });
		    				reloadtable();
		    			}, 
		    			error: function(txt) { 
		    				$.sticky("UM ERRO DE SISTEMA OCORREU.", { type: 'st-error' });
		    			} 
		    		}); 
			 
		 }
	 });
	 
	 $(".recusalancamento").live('click',function(){
		 id_lancamento = $(this).attr('id_lancamento');
		 if(confirm("Deseja recusar todas as parcelas deste lançamento?")){
			 $.ajax({ 
	    			type: "POST", 
	    			url: "/erp/financeiro/bloqueia-recebimento/tipo/lancamento/id/"+id_lancamento, 
	    			data: "other="+id_parcela,
	    			beforeSend: function() {
	    				$.sticky("SOLICITANDO BLOQUEIO DE LANÇAMENTO.", { type: 'st-info' });				
	    	 		}, 
	    			success: function(txt) {
	    				$.sticky("LANÇAMENTO BLOQUEADO PARA PAGAMENTO.", { type: 'st-success' });
	    				reloadtable();
	    			}, 
	    			error: function(txt) { 
	    				$.sticky("UM ERRO DE SISTEMA OCORREU.", { type: 'st-error' });
	    			} 
	    		}); 
		 }
	 });

	 $(".cancelaparcela").live('click',function(){
		 id_parcela = $(this).attr('id_parcela');
		 if(confirm("Deseja cancelar essa parcela?")){
			 $.ajax({ 
	    			type: "POST", 
	    			url: "/erp/financeiro/cancela-recebimento/tipo/parcela/id/"+id_parcela, 
	    			data: "other="+id_parcela,
	    			beforeSend: function() {
	    				$.sticky("SOLICITANDO CANCELAMENTO DE PARCELA.", { type: 'st-info' });				
	    	 		}, 
	    			success: function(txt) {
	    				$.sticky("PARCELA CANCELADA.", { type: 'st-success' });
	    				reloadtable();
	    			}, 
	    			error: function(txt) { 
	    				$.sticky("UM ERRO DE SISTEMA OCORREU.", { type: 'st-error' });
	    			} 
	    		}); 

			 }
	 });

	 $(".reincluir").live('click',function(){
		 id_lancamento = $(this).attr('id_parcela');
		 if(confirm("Deseja reincluir esta parcela?")){
			 $.ajax({ 
	    			type: "POST", 
	    			url: "/erp/financeiro/reativa-recebimento/tipo/parcela/id/"+id_lancamento, 
	    			data: "other="+id_lancamento,
	    			beforeSend: function() {
	    				$.sticky("SOLICITANDO RE-INCLUSÃO DE PARCELA.", { type: 'st-info' });				
	    	 		}, 
	    			success: function(txt) {
	    				$.sticky("PARCELA RE-INCLUSA.", { type: 'st-success' });
	    				reloadtable();
	    			}, 
	    			error: function(txt) { 
	    				$.sticky("UM ERRO DE SISTEMA OCORREU.", { type: 'st-error' });
	    			} 
	    		}); 
			 
		 }
	 });


	 $(".reincluirlancado").live('click',function(){
		 id_lancamento = $(this).attr('id_parcela');
		 if(confirm("Deseja Cancelar este registro e reincluir a parcela como \"Em Aberto?\"")){
			 $.ajax({ 
	    			type: "POST", 
	    			url: "/erp/financeiro/cancela-recebimento-lancado/tipo/parcela/id/"+id_lancamento, 
	    			data: "other="+id_lancamento,
	    			beforeSend: function() {
	    				$.sticky("SOLICITANDO RE-INCLUSÃO DE PARCELA.", { type: 'st-info' });				
	    	 		}, 
	    			success: function(txt) {
	    				$.sticky("PARCELA RE-INCLUSA.", { type: 'st-success' });
	    				reloadtable();
	    			}, 
	    			error: function(txt) { 
	    				$.sticky("UM ERRO DE SISTEMA OCORREU.", { type: 'st-error' });
	    			} 
	    		}); 
			 
		 }
	 });

	

	
		 $(".printerbutton").live('click',function(){
			 id_parcela = $(this).attr('id_parcela');
			 $("#print_id_lancamento").val(id_parcela);
			 $("#PrintLancamento").modal('show');
		 });

		 $(".combobox").chosen();


		 $("a[data-target=#AllModal]").live('click',function(ev) {
			    ev.preventDefault();
			    var target = $(this).attr("href");

			    // load the url and show modal on success
			    $("#AllModal .modal-body").load(target, function() { 
			         $("#AllModal").modal("show"); 
			    });
			});

		 $("a[data-target=#EditParcModal]").live('click',function(ev) {
			    ev.preventDefault();
			    var target = $(this).attr("href");
			    $('.modal-large').css('width', '950px');
			    // load the url and show modal on success
			    $("#EditParcModal .modal-body").load(target, function() { 
			         $("#EditParcModal").modal("show"); 
			    });
			});	

		 $("a[data-target=#EditLancModal]").live('click',function(ev) {
			    ev.preventDefault();
			    var target = $(this).attr("href");
			    $('.modal-large').css('width', '950px');
			    // load the url and show modal on success
			    $("#EditLancModal .modal-body").load(target, function() { 
			         $("#EditLancModal").modal("show"); 
			    });
			});	

		 $("a[data-target=#CancelModal]").live('click',function(ev) {
			    ev.preventDefault();
			    var target = $(this).attr("href");

			    // load the url and show modal on success
			    $("#CancelModal .modal-body").load(target, function() {
			         showRecaptcha('captchadiv');
			         $("#CancelModal").modal("show"); 
			         showRecaptcha('captchadiv');
			    });
			});	

	$('#listalancamentos').dataTable({
		"oLanguage": {
			"sUrl": "/js/datatable_ptbr.txt"
		},
		"sPaginationType": "bootstrap",
        "bProcessing": true,
		"bServerSide": true,
		 "sAjaxSource": "/system/datatables-financeiro/lancamentos-receber/tipo/<?php echo $tipo ?>"
               	
                    
    });

	$('#baixaLancamento').validate({
		onkeyup: false,
		errorClass: 'error',
		validClass: 'valid',
		highlight: function(element) {
			$(element).closest('div').addClass("f_error");
		},
		unhighlight: function(element) {
			$(element).closest('div').removeClass("f_error");
		},
  errorPlacement: function(error, element) {
      $(element).closest('div').append(error);
  },

  invalidHandler: function(form, validator) {
			$.sticky("Existem campos obrigatórios não preenchidos no formulário, corrija estes erros e tente novamente.", {autoclose : 5000, position: "top-right", type: "st-error" });
		},
		submitHandler: function(form) {
			jQuery(form).ajaxSubmit({
				target: "#ajaxrequest",
				beforeSubmit:   function(){ 
					$.sticky("Salvando informações.", {autoclose : 5000, position: "top-right", type: "st-info" });
					
				}, 
			error: function(txt) { 
				$.sticky("Ocorreu um erro com sua solicitação: "+ txt, {autoclose : 5000, position: "top-right", type: "st-error" });
				$("#ajaxrequest").html("Erro" + txt);
				//reloadtable();
				
			},
			success: function(txt){
				$.sticky("Lançamento baixado com sucesso.", {autoclose : 5000, position: "top-right", type: "st-success" });
				
				$("#AllModal").modal('hide');  
				reloadtable();
				
				
		
			},
		        clearForm: true
				
			});
		}
});


	$('#cancelalancamento').validate({
		onkeyup: false,
		errorClass: 'error',
		validClass: 'valid',
		highlight: function(element) {
			$(element).closest('div').addClass("f_error");
		},
		unhighlight: function(element) {
			$(element).closest('div').removeClass("f_error");
		},
  errorPlacement: function(error, element) {
      $(element).closest('div').append(error);
  },

  invalidHandler: function(form, validator) {
			$.sticky("Existem campos obrigatórios não preenchidos no formulário, corrija estes erros e tente novamente.", {autoclose : 5000, position: "top-right", type: "st-error" });
		},
		submitHandler: function(form) {
			jQuery(form).ajaxSubmit({
				target: "#ajaxrequest",
				beforeSubmit:   function(){ 
					$.sticky("Validando Solicitação.", {autoclose : 5000, position: "top-right", type: "st-info" });
					
				}, 
			error: function(txt) { 
				$.sticky("Ocorreu um erro com sua solicitação: "+ txt, {autoclose : 5000, position: "top-right", type: "st-error" });
				$("#ajaxrequest").html("Erro" + txt);
				//reloadtable();
				
			},
			success: function(txt){
				if(txt == "ERRO"){
					$.sticky("CARACTERES INCORRETOS TENTE NOVAMENTE.", {autoclose : 10000, position: "top-right", type: "st-error" });
					showRecaptcha('captchadiv');
					$("#ajaxrequest").html('');
				}else{
				$.sticky("Lançamento baixado com sucesso.", {autoclose : 5000, position: "top-right", type: "st-success" });
				$("#CancelModal").modal('hide');  
				reloadtable();
				$("#ajaxrequest").html('');
				}
				
				
		
			},
		        clearForm: true
				
			});
		}
});



	$('#editaParcela').validate({
		onkeyup: false,
		errorClass: 'error',
		validClass: 'valid',
		highlight: function(element) {
			$(element).closest('div').addClass("f_error");
		},
		unhighlight: function(element) {
			$(element).closest('div').removeClass("f_error");
		},
  errorPlacement: function(error, element) {
      $(element).closest('div').append(error);
  },

  invalidHandler: function(form, validator) {
			$.sticky("Existem campos obrigatórios não preenchidos no formulário, corrija estes erros e tente novamente.", {autoclose : 5000, position: "top-right", type: "st-error" });
		},
		submitHandler: function(form) {
			jQuery(form).ajaxSubmit({
				target: "#ajaxrequest",
				beforeSubmit:   function(){ 
					$.sticky("Validando Solicitação.", {autoclose : 5000, position: "top-right", type: "st-info" });
					
				}, 
			error: function(txt) { 
				$.sticky("Ocorreu um erro com sua solicitação: "+ txt, {autoclose : 5000, position: "top-right", type: "st-error" });
				$("#ajaxrequest").html("Erro" + txt);
				//reloadtable();
				
			},
			success: function(txt){
				$.sticky(txt, {autoclose : 5000, position: "top-right", type: "st-success" });
				$("#EditParcModal").modal('hide');  
				reloadtable();
				$("#ajaxrequest").html('');
			
				
				
		
			},
		        clearForm: true
				
			});
		}
});


	$('#editaLancamento').validate({
		onkeyup: false,
		errorClass: 'error',
		validClass: 'valid',
		highlight: function(element) {
			$(element).closest('div').addClass("f_error");
		},
		unhighlight: function(element) {
			$(element).closest('div').removeClass("f_error");
		},
  errorPlacement: function(error, element) {
      $(element).closest('div').append(error);
  },

  invalidHandler: function(form, validator) {
			$.sticky("Existem campos obrigatórios não preenchidos no formulário, corrija estes erros e tente novamente.", {autoclose : 5000, position: "top-right", type: "st-error" });
		},
		submitHandler: function(form) {
			jQuery(form).ajaxSubmit({
				target: "#ajaxrequest",
				beforeSubmit:   function(){ 
					$.sticky("Validando Solicitação.", {autoclose : 5000, position: "top-right", type: "st-info" });
					
				}, 
			error: function(txt) { 
				$.sticky("Ocorreu um erro com sua solicitação: "+ txt, {autoclose : 5000, position: "top-right", type: "st-error" });
				$("#ajaxrequest").html("Erro" + txt);
				//reloadtable();
				
			},
			success: function(txt){
				$.sticky(txt, {autoclose : 5000, position: "top-right", type: "st-success" });
				$("#EditLancModal").modal('hide');  
				reloadtable();
				$("#ajaxrequest").html('');
			
				
				
		
			},
		        clearForm: true
				
			});
		}
});
	
})

function showRecaptcha(element) {
           Recaptcha.create("6Ldk6-ISAAAAALqcpxh2182Y0Yd8ZqHr2p_QIGoO", element, {
             theme: "red",
             callback: Recaptcha.focus_response_field});
         }

function reloadtable(){
	$("#listalancamentos").dataTable().fnDraw(); 
}
</script>
