<?php if($this->tipo = 'New'){ 
	echo "<input type=\"hidden\" name=\"operacao\" value=\"new\">";
}else{
	echo "<input type=\"hidden\" name=\"operacao\" value=\"update\">";
}?>
<?php echo $this->form->id_registro ?>
<div class="row-fluid">

<div class="span6">
<?php echo $this->form->id_conta ?>
</div>

<div class="span6">
<?php echo $this->form->tipolancamento ?>
</div>
</div>

<div id="transferencia">
<div class="row-fluid">
<div class="span12">
<?php echo $this->form->contatransferencia ?>
</div>
</div>

</div>

<div class="row-fluid">

<div class="span6">
<?php echo $this->form->categoria ?>
</div>

<div class="span6">
<?php echo $this->form->nomelancamento ?>
</div>

</div>

<div class="row-fluid">

<div class="span6">
<?php echo $this->form->valorregistro ?>
</div>

<div class="span6">
<?php echo $this->form->datalancamento ?>
</div>

</div>

<div class="row-fluid">
<div class="span12">
<?php echo $this->form->observacoes ?>
</div>

</div>

<script>
$().ready(function(){
	$("#id_conta").chosen();
	$("#tipolancamento").chosen();
	$("#categoria").chosen();

	$("#transferencia").hide();

	$("#tipolancamento").change(function(){
		valor = $("#tipolancamento").val();
		if(valor == 3){
			$("#transferencia").show();
		}else{
			$("#transferencia").hide();
		}

		});

	$("#nomelancamento").autocomplete({
		 
	    source: "/system/auto-complete/pessoas",
			minLength: 0,
			focus: function( event, ui ) {
		//	$( "#nomerepresentante" ).val( ui.item.razaosocial );
			return false;
		},

	    select: function(event, ui) {
	        $('#id_pessoa').val(ui.item.id_registro);
	        $( "#nomelancamento" ).val( ui.item.razaosocial );
	         return false;

	    }
	});
})

</script>