<div class="row-fluid">
<div class="span12">
<h3 class="heading">Lançamento a Receber <small>Código: <?php echo $this->id_lancamento?></small></h3>
</div>
</div>
<div class="row-fluid">
<div class="span12">
<h3 class="heading">O Lançamento Código: <?php echo $this->id_lancamento?> foi incluído com sucesso!</h3>
</div>
</div>

<div class="row-fluid">
<div class="span12">
<h3 class="heading"><a href="/erp/financeiro/nova-conta-receber">Clique para efetuar um novo lançamento</a> ou <a href="/erp/financeiro/abre-lanc-completo/id/<?php echo $this->id_lancamento?>">edite esse lançamento</a></vh3>
</div>
</div>