<?php if($this->basicosData['liberaprod'] == 1){
 	$cadastrobloqueado = true; ?>
 <div class="row-fluid">
<div class="span12">
<div class="alert alert-block alert-error fade in">
<h4 class="alert-heading">Pedido Bloqueado</h4>
								<p>Este pedido foi liberado para produção por <?php echo System_Model_Users::whoIs($this->basicosData['userlibera'])?> em <?php echo Functions_Datas::MyDateTime($this->basicosData['datalibera'],true)?>.</p>
								<p>Por este motivo o pedido não pode ser mais alterado</p>
						</div>
						</div>
						</div>

<?php }else{
	$cadastrobloqueado = false;
} ?>
<div class="row-fluid">
<div class="span12">
<h3 class="heading">Pedido de Venda <span class="pull-right"> <small>Número: <?php echo $this->basicosData['id_registro']?></small> <a href='/erp/faturamento/abrir-pedido/id/<?php echo $this->basicosData['id_registro']?>' class='ttip_b' title='Faturar Pedido'><i class='splashy-document_a4_add' title='Faturar Pedido'></i></a></span></h3>
</div>
</div>
<div id="ajaxrequest"></div>
<div class="tabbable tabs-left">
	 	<ul class="nav nav-tabs">
			<li class="active"><a href="#tab_l1" data-toggle="tab">Pedido: </a></li>
			<li><a href="#tab_l2" data-toggle="tab">Itens</a></li>
			<li><a href="#tab_l3" data-toggle="tab">Opções</a></li>
		</ul>
	<div class="tab-content">
	<div class="tab-pane active" id="tab_l1">
		<h3 class="heading">Dados do Pedido: </h3>
						<form id="vendas" class="form-horizontal" name="vendas" method="post" action="">
			<?php echo $this->form->id_pessoa ?><?php echo $this->form->id_registro ?>
			<div class="row-fluid formSep">
			<div class="span12">
			<?php echo $this->form->nomepessoa ?>
			</div>
			</div>
			<div class="row-fluid formSep">
			<div class="span6">
			<div class="row-fluid formSep">
			<div class="span6">
			<?php echo $this->form->tipo_pedido?>
			</div>
			<div class="span6">
			<?php echo $this->form->pedido_cliente?>
			</div>
			</div>
			<?php echo $this->form->id_vendedor ?>
			<div class="row-fluid formSep">
			<div class="span6">
			<?php echo $this->form->nomevendedor?>
			</div>
			<div class="span6">
			<?php echo $this->form->comissao?>
			</div>
			</div>
			</div>
			<div class="span6 form-horizontal well">
			<div class="span6">
			<?php echo $this->form->datainspecao?>
			</div>
			<div class="span6">
			<?php echo $this->form->tipo_inspecao?>
			</div>
			<div class="row-fluid formSep">
			<div class="span6">
			<?php echo $this->form->entrega_de?>
			</div>
			<div class="span6">
			<?php echo $this->form->entrega_ate?>
			</div>
			</div>
			<div class="row-fluid formSep">
			<div class="span6">
			<?php echo $this->form->agendamento_entrega?>
			</div>
			<div class="span6">
			<?php echo $this->form->agendamento_entrega_hora?>
			</div>
			</div>
			</div>
			</div>
			<div class="row-fluid formSep">
			<div class="span6">
			<div class="span11">
			<?php echo $this->form->obspedido ?>
			</div>
			</div>
			<div class="span6">
			<div class="span11">
			<?php echo $this->form->obsfaturamento ?>
			</div>
			</div>
			</div>
			<div class="row-fluid">
			<fieldset id="fieldset-botoes">
			<div style="text-align:right">
			<input type="reset" name="limpar" id="limpar" value="Limpar" class="btn btn-large btn-warning">
			<input type="submit" name="submit" id="submit" value="Editar Informações" class="btn btn-large btn-primary">
			</div>
			</fieldset>
			</div>
			</form>
	
			</div>
			
	<div class="tab-pane" id="tab_l2">
	<h3 class="heading">Itens: <span class="pull-right"> <input type="button" class="btn btn-success" id="AddProduto" value="Adicionar Produto"> </span></h3>
	
	<table id="table-1"  class="table table-striped table-bordered table-condensed">
	<thead>
		<tr>
			<th width="20%">Produto:</th>
			<th width="5%">Qtd</th>
			<th width="5%">Vl Unit.</th>
			<th width="5%">Vl Total:</th>
			<th width="5%">Comissao:</th>
			<th width="8%">Faturado:</th>
			<th width="8%">A Faturar:</th>
			<th width="10%">Adicional:</th>
			<th width="7%">Adicional:</th>
			<th width="7%">Observações:</th>
			<th width="5%"></th>
			</tr>
		</thead>
		<tbody>
		</tbody>
	
	</table>
	
	</div>
	<div class="tab-pane" id="tab_l3">
	<div class="row-fluid">
	<div class="span6">
	<form class="form-horizontal well" method="post">
										<fieldset>
											<p class="f_legend">Opções do Pedido</p>
											<div class="control-group">
												<label class="control-label">Enviar email ao cliente?:</label>
												<div class="controls">
													 <div id="toggle-sendmail" class="toggletbns">
          											<input type="checkbox" name="sendEmail" value="1" <?php if($this->basicosData['enviaremail'] == 1){ echo "checked=\"checked\""; }; ?> >
      												</div>
												</div>
											</div>
											
											
											<div class="control-group">
												<label class="control-label">Faturamento Parcial?:</label>
												<div class="controls">
													 <div id="toggle-faturaparcial" class="toggletbns">
          											<input type="checkbox" name="faturamentoparcial" value="1" <?php if($this->basicosData['faturaparcial'] == 1){ echo "checked=\"checked\""; }; ?> >
      												</div>
												</div>
											</div>
											
												<div class="control-group">
												<label class="control-label">Forma de Pagamento:</label>
												<div class="controls">
													<select name="perfilpagamento" id="perfilpagamento">
												<?php
												$empresas = Erp_Model_Financeiro_Perfil::getCombo();
													foreach($empresas as $key=>$value){
														if($key == $this->basicosData['formapagamento'] ){
															$selected = 'selected="selected"';
														}else{
															$selected = '';
														}
														echo "<option value=\"$key\" $selected> $value </otion>";
												} ?>
												</select>
													
												</div>
											</div>
											
												<div class="control-group">
												<label class="control-label">Perfil NFe:</label>
												<div class="controls">
												<select name="perfilfaturamento" id="perfilfaturamento">
												<?php
												$empresas = Erp_Model_Faturamento_Perfil::getCombo();
													foreach($empresas as $key=>$value){
														if($key == $this->basicosData['perfilnfe'] ){
															$selected = 'selected="selected"';
														}else{
															$selected = '';
														}
														echo "<option value=\"$key\" $selected> $value </otion>";
												} ?>
												</select>
												</div>
											</div>
											
											
											</fieldset>
											</form>

	</div>
	
	
	<div class="span6">
	<form class="form-horizontal well" method="post">
										<fieldset>
											<p class="f_legend">Configurações do Pedido</p>
											<div class="control-group">
												<label class="control-label">Liberar para produção?:</label>
												<div class="controls">
													 <div id="toggle-liberaprod" class="toggletbns">
          											<input type="checkbox" name="liberaproducao" value="1" <?php if($this->basicosData['liberaprod'] == 1){ echo "checked=\"checked\""; }; ?> >
      												</div>
												</div>
											</div>
											
											
											<div class="control-group">
												<label class="control-label">Agrupar itens no faturamento?:</label>
												<div class="controls">
													 <div id="toggle-agrupafat" class="toggletbns">
          											<input type="checkbox" name="agrupafat" value="1" <?php if($this->basicosData['agruparfaturamento'] == 1){ echo "checked=\"checked\""; }; ?> >
      												</div>
												</div>
											</div>
											
											</fieldset>
											</form>

	</div>
	</div>
	<div class="row-fluid">
	<div class="span12">
	<?php echo Functions_Messages::renderAlert("Aqui você pode alterar o comportamento padrão do sistema para este pedido",'info');?>
	</div>
	</div>
	
</div>

</div>



<!-- MODAL PARA ADICIONAR / Editar PRODUTOS -->



<div class="modal hide fade" id="AddProdutoModal">
   <div class="modal-header">
   <button class="close" data-dismiss="modal">×</button>
   <h3>Produtos:</h3>
   </div>
<form id="addproduto" name="addproduto" class="form-horizontal" method="post" action="/erp/vendas/add-produto-pedido">
<input type="hidden" name="id_registro" value="0" id="id_registro_produto">
<input type="hidden" name="id_produto" class="required" value="0" id="id_produto_add">
<input type="hidden" name="id_venda" value="<?php echo $this->basicosData['id_registro'] ?>" id="id_venda">
<div class="modal-body">
<div class="row-fluid formSep">
<div class="span6">
<label for="assuntoticket" class="optional">Produto:</label>
<input type="text" name="nomeproduto" id="nomeproduto_add" class="span12 required" title="Informe um Produto" >
</div>
<div class="span2">
<label for="assuntoticket" class="optional">Quantidade:</label>
<input type="text" name="qtdproduto" id="qtdprotudo_add" class="span12 required" title="Informe a quantidade do produto" >
</div>

<div class="span2">
<label for="assuntoticket" class="optional">Valor Un:</label>
<input type="text" name="valorun" id="valorun_add" class="span12 required" title="Informe o valor unitário" > 
</div>
<div class="span2">
<label for="assuntoticket" class="optional">Comissão:</label>
<input type="text" name="comissaoprod" id="comissaoprod" class="span12" >
</div>
</div>
<div class="row-fluid formSep">
<div class="span4">
		<label for="assuntoticket" class="optional">Adicional:</label>
		<input type="text" name="adicional_1" id="adicional_1" class="span12" >
		</div>
		<div class="span4">
		<label for="assuntoticket" class="optional">Adicional:</label>
		<input type="text" name="adicional_2" id="adicional_2" class="span12" >
		</div>
		<div class="span4">
		<label for="assuntoticket" class="optional">Observações Fat.</label>
		<input type="text" name="adicional_3" id="adicional_3" class="span12" >
		</div>
</div>
</div>
<div class="modal-footer">
<div style="text-align:right">
<a href="javascript:void(0)" class="btn btn-large btn-warning" data-dismiss="modal">Cancelar</a>
<input type="submit" name="submit" id="submiteditnote" value="Salvar" class="btn btn-large btn-primary">
</div>	
</div>	
</form>
</div>
</div>


<script>
function processtogle(tipo,valor){
	  $.ajax({ 
			type: "POST", 
			url: "/erp/vendas/proccess-togle", 
			data: "tipo="+ tipo +"&valor="+valor+"&id_venda=<?php echo  $this->basicosData['id_registro'] ?>",
			beforeSend: function() {
								
	 		}, 
			success: function(txt) {
				$.sticky(txt, { type: 'st-success' });
																
			}, 
			error: function(txt) { 
				$.sticky("UM ERRO DE SISTEMA OCORREU.", { type: 'st-error' });
			} 
		}); 
	
}
$().ready(function(){

	$("#perfilfaturamento").live('change',function(){
		valor = $("#perfilfaturamento").val();
		processtogle("perfilfaturamento",valor);
	});

	
	 $("#perfilfaturamento").chosen();

	 $("#perfilpagamento").live('change',function(){
			valor = $("#perfilpagamento").val();
			processtogle("perfilpagamento",valor);
		});

		
		 $("#perfilpagamento").chosen();

	$("#toggle-liberaprod").toggleButtons({
	    onChange: function ($el, status, e) {
			   if(status){
				   processtogle("liberaprod",1);
			   }else{
				   processtogle("liberaprod",0);
			   }
			     
			  },
		 label: {
		 enabled: "Sim",
		 disabled: "Não"
		 }
		 });

	$("#toggle-sendmail").toggleButtons({
	    onChange: function ($el, status, e) {
			   if(status){
				   processtogle("enviaemail",1);
			   }else{
				   processtogle("enviaemail",0);
			   }
			     
			  },
		 label: {
		 enabled: "Sim",
		 disabled: "Não"
		 }
		 });


	$("#toggle-agrupafat").toggleButtons({
	    onChange: function ($el, status, e) {
			   if(status){
				   processtogle("agrupafat",1);
			   }else{
				   processtogle("agrupafat",0);
			   }
			     
			  },
		 label: {
		 enabled: "Sim",
		 disabled: "Não"
		 }
		 });


	$("#toggle-faturaparcial").toggleButtons({
	    onChange: function ($el, status, e) {
			   if(status){
				   processtogle("faturaparcial",1);
			   }else{
				   processtogle("faturaparcial",0);
			   }
			     
			  },
		 label: {
		 enabled: "Sim",
		 disabled: "Não"
		 }
		 });

	
	 



	$('#vendas').validate({
		onkeyup: false,
		errorClass: 'error',
		validClass: 'valid',
		highlight: function(element) {
			$(element).closest('div').addClass("f_error");
		},
		unhighlight: function(element) {
			$(element).closest('div').removeClass("f_error");
		},
        errorPlacement: function(error, element) {
            $(element).closest('div').append(error);
        },

        invalidHandler: function(form, validator) {
			$.sticky("Existem campos obrigatórios não preenchidos no formulário, corrija estes erros e tente novamente.", {autoclose : 5000, position: "top-right", type: "st-error" });
		}
    });

    $("#tipo_inspecao").chosen();
    $("#tipo_pedido").chosen();
  
	$('#datainspecao').datepicker({language:"br", format: "dd/mm/yyyy"});

	$('#agendamento_entrega').datepicker({language:"br", format: "dd/mm/yyyy"});
	
	$('#entrega_de').datepicker({language:"br", format: "dd/mm/yyyy"}).on('changeDate', function(ev){
		var dateText = $(this).val();
		
		var endDateTextBox = $('#entrega_ate');
		if (endDateTextBox.val() != '') {
			var testStartDate = new Date(dateText);
			var testEndDate = new Date(endDateTextBox.val());
			if (testStartDate > testEndDate) {
				endDateTextBox.val(dateText);
			}
		}
		else {
			endDateTextBox.val(dateText);
		};
		$('#entrega_ate').datepicker('setStartDate', dateText);
		$('#entrega_de').datepicker('hide');
	});
	$('#entrega_ate').datepicker({language:"br", format: "dd/mm/yyyy"}).on('changeDate', function(ev){
		var dateText = $(this).val();
		var startDateTextBox = $('#entrega_de');
		if (startDateTextBox.val() != '') {
			var testStartDate = new Date(startDateTextBox.val());
			var testEndDate = new Date(dateText);
			if (testStartDate > testEndDate) {
				startDateTextBox.val(dateText);
			}
		}
		else {
			startDateTextBox.val(dateText);
		};

		
		$('#entrega_de').datepicker('setEndDate', dateText);
		$('#entrega_ate').datepicker('hide');
	});

	$('#agendamento_entrega_hora').timepicker({
		defaultTime: false,
		setTime: '<?php echo $this->basicosData['agendamento_entrega_hora'] ?>',
		minuteStep: 10,
		disableFocus: true,
		template: 'dropdown',
		showMeridian: false
	});


	$("#nomepessoa").autocomplete({
		 
	    source: "/system/auto-complete/pessoas",
			minLength: 0,
			focus: function( event, ui ) {
		//	$( "#nomerepresentante" ).val( ui.item.razaosocial );
			return false;
		},

	    select: function(event, ui) {
	        $('#id_pessoa').val(ui.item.id_registro);
	        $( "#nomepessoa" ).val( ui.item.razaosocial );
	         return false;

	    }
	});

	$("#nomevendedor").autocomplete({
		 
	    source: "/system/auto-complete/pessoas/tipo/4",
			minLength: 0,
			focus: function( event, ui ) {
		//	$( "#nomerepresentante" ).val( ui.item.razaosocial );
			return false;
		},

	    select: function(event, ui) {
	        $('#id_vendedor').val(ui.item.id_registro);
	        $( "#nomevendedor" ).val( ui.item.razaosocial );
	         return false;

	    }
	});


	$('#table-1').dataTable({
		"oLanguage": {
			"sUrl": "/js/datatable_ptbr.txt"
		},
		
		"sPaginationType": "bootstrap",
        "bProcessing": true,
		"bServerSide": true,
		 "sAjaxSource": "/system/datatables/produtos-pedido-venda/pedido/<?php echo $this->basicosData['id_registro']?>/blockpedido/<?php echo $this->basicosData['liberaprod'] ?>"
               	
                    
    });


	 $("#AddProduto").click(function(){
		    $("#AddProdutoModal").modal('show');    
		    $("#comissaoprod").val($("#comissao").val());
			
	    });

	$("#nomeproduto_add").autocomplete({
			 
		    source: "/system/auto-complete/produtos/id/0",
				minLength: 0,
				focus: function( event, ui ) {
			//	$( "#nomerepresentante" ).val( ui.item.razaosocial );
				return false;
			},

		    select: function(event, ui) {
		        $('#id_produto_add').val(ui.item.id_registro);
		        $( "#nomeproduto_add" ).val( ui.item.nomeproduto );
		        $( "#valorun_add" ).val( ui.item.precovenda );
		        <?php if(System_Model_SysConfigs::getConfig("TravaPrecoVendaProduto") == 1){?>
		        $( "#valorun_add" ).attr("readonly",true);
		        <?php } ?>
		                  
		        return false;

		    }

		    
		});


	$('#addproduto').validate({
		onkeyup: false,
		errorClass: 'error',
		validClass: 'valid',
		highlight: function(element) {
			$(element).closest('div').addClass("f_error");
		},
		unhighlight: function(element) {
			$(element).closest('div').removeClass("f_error");
		},
        errorPlacement: function(error, element) {
            $(element).closest('div').append(error);
        },
      
        invalidHandler: function(form, validator) {
			$.sticky("Existem campos obrigatórios não preenchidos no formulário, corrija estes erros e tente novamente.", {autoclose : 5000, position: "top-right", type: "st-error" });
		},
		submitHandler: function(form) {
			jQuery(form).ajaxSubmit({
				target: "#ajaxrequest",
				beforeSubmit:   function(){ 
					$.sticky("Incluindo produto no pedido de vendas -->>.", {autoclose : 5000, position: "top-right", type: "st-info" });
					
				}, 
			error: function(txt) { 
				$.sticky("Ocorreu um erro com sua solicitação: "+ txt, {autoclose : 5000, position: "top-right", type: "st-error" });
				$("#ajaxrequest").html('');
				reloadtable();
				
			},
			success: function(txt){
				$.sticky("Produto incluído com sucesso.", {autoclose : 5000, position: "top-right", type: "st-success" });
				
				$("#AddProdutoModal").modal('hide');  
				reloadtable();
				$("#id_registro_produto").val("0");
				$("#id_venda").val("<?php echo $this->basicosData['id_registro']?>");
				
		
			},
		        clearForm: true
				
			});
		}
    });

    $(".editproduto").live('click',function(){
    	idmessage =  $(this).attr('idregistro');
    	  $.ajax({ 
    			type: "POST", 
    			url: "/erp/vendas/get-produto-pedido", 
    			data: "id="+ idmessage,
    			beforeSend: function() {
    								
    	 		}, 
    			success: function(txt) {
        			
    				var retorno = jQuery.parseJSON(txt);	
    				$("#id_registro_produto").val(retorno.id_registro);
    				$("#id_produto_add").val(retorno.id_produto);
    				$("#id_venda").val(retorno.id_venda);
    				$("#nomeproduto_add").val(retorno.nomeproduto);
    				$("#qtdprotudo_add").val(retorno.quantidade);
    				$("#valorun_add").val(retorno.vl_unitario);
    				$("#comissaoprod").val(retorno.comissao);
    				$("#adicional_1").val(retorno.adicional_1);
    				$("#adicional_2").val(retorno.adicional_2);	
    				$("#adicional_3").val(retorno.adicional_3);
					$("#AddProdutoModal").modal('show');  
    														
    			}, 
    			error: function(txt) { 
    				$.sticky("UM ERRO DE SISTEMA OCORREU.", { type: 'st-error' });
    			} 
    		}); 


    })

     $(".removeproduto").live('click',function(){
  	    	idmessage =  $(this).attr('idregistro');
			if(confirm("Deseja Realmente remover este produto do pedido de venda?")){
  	    	  $.ajax({ 
  	    			type: "POST", 
  	    			url: "/erp/vendas/remove-produto-pedido", 
  	    			data: "id="+ idmessage,
  	    			beforeSend: function() {
  	    								
  	    	 		}, 
  	    			success: function(txt) {
  	    				$.sticky("PRODUTO REMOVIDO DO PEDIDO.", { type: 'st-success' });
  	    				reloadtable();
  	    			}, 
  	    			error: function(txt) { 
  	    				$.sticky("UM ERRO DE SISTEMA OCORREU.", { type: 'st-error' });
  	    			} 
  	    		}); 
			}
     });


    $(".block").live('click',function(){
		  alert("Pedido Liberado para produção e bloqueado");
	  })
	    

});

function reloadtable(){
	$("#table-1").dataTable().fnDraw(); 
}
<?php if($this->basicosData['liberaprod'] == 1){ ?>

$().ready(function(){
	$('#vendas :input').attr('disabled', 'disabled');
	$('#addproduto :input').attr('disabled', 'disabled');
//	$('#clientescontatos :input').attr('disabled', 'disabled');
//	$('#clientesoutros :input').attr('disabled', 'disabled');
//	$('#clientesfiles :input').attr('disabled', 'disabled');
});

<?php } ?>

</script>