<h3 class="heading">Cadastro de Empresa: <?php echo $this->dados['razaosocial'] ?></h3>


	<div class="tabbable tabs-left">
	 	<ul class="nav nav-tabs">
			<li class="active"><a href="#tab_l1" data-toggle="tab">Básicos</a></li>
			<li><a href="#tab_l2" data-toggle="tab">Nota Fiscal</a></li>
			<li><a href="#tab_l3" data-toggle="tab">Logos</a></li>
			<li><a href="#tab_l4" data-toggle="tab">Documentos</a></li>
					</ul>
	<div class="tab-content">
		<div class="tab-pane active" id="tab_l1">
		<?php echo $this->form ?>
		</div>
		
		<div class="tab-pane " id="tab_l2">
		<h3 class="heading">Certificado Digital</h3>
		<form id="logodanfe" name="logodanfe" enctype="multipart/form-data" class="form-horizontal" method="post" action="/sistema/empresas/certificadodigital">
		<input type="hidden" name="id_empresa"  id="id_empresa" value="<?php echo $this->dados['id_registro']?>">
		<fieldset id="fieldset-clientesfiles" class="form-horizontal">
		<div class="row-fluid formSep">
		<?php if($this->dadosnf['certificadodigital'] <> ''){ ?>
		<div class="span4">Certificado Encontrado válido até <?php echo Functions_Datas::MyDateTime($this->dadosnf['validadecertificado'])?><br>
		<img src="/img/Certificado-Digital1.png" width="50%"></div>
		<?php } ?>
		<div class="span3">
		<label for="arquivo" class="optional">Selecione o Documento:</label>
		<input type="hidden" name="MAX_FILE_SIZE" value="104857600" id="MAX_FILE_SIZE">
		<input type="file" name="arquivo" id="arquivo"  class="uni_style">
		</div>
		</div>
		</fieldset>
		<fieldset id="fieldset-botoes">
		<div style="text-align:right">
		<input type="submit" name="submitoutros" id="submitoutros" value="Salvar Certificado" class="btn btn-large btn-primary">
		</div>
		</fieldset>
		</form>	
		
		<?php echo $this->formnfe ?>
		</div>
		<div class="tab-pane " id="tab_l3">
		
		<h3 class="heading">Logotipo do Sistema</h3>	
		<form id="logosistema" name="logosistema" enctype="multipart/form-data" class="form-horizontal" method="post" action="/sistema/empresas/logosistema">
		<input type="hidden" name="id_empresa" id="id_empresa" value="<?php echo $this->dados['id_registro']?>">
		<fieldset id="fieldset-clientesfiles" class="form-horizontal">
		<div class="row-fluid formSep">
		<?php if($this->dados['logotipo'] <> ''){ ?>
		<div class="span4"><img src="/default/arquivos/get-logo-report/id/<?php echo $this->dados['id_registro']?>"></div>
		<?php } ?>
		<div class="span3">
		<label for="arquivo" class="optional">Selecione o Documento:</label>
		<input type="hidden" name="MAX_FILE_SIZE" value="104857600" id="MAX_FILE_SIZE">
		<input type="file" name="arquivo" id="arquivo"  class="uni_style">
		</div>
		</div>
		</fieldset>
		<fieldset id="fieldset-botoes">
		<div style="text-align:right">
		<input type="reset" name="limparoutros" id="limparoutros" value="Limpar" class="btn btn-large btn-warning">
		<input type="submit" name="submitoutros" id="submitoutros" value="Salvar" class="btn btn-large btn-primary">
		</div>
		</fieldset>
		</form>	
		<h3 class="heading">Logotipo Danfe</h3>
		<form id="logodanfe" name="logodanfe" enctype="multipart/form-data" class="form-horizontal" method="post" action="/sistema/empresas/logodanfe">
		<input type="hidden" name="id_empresa"  id="id_empresa" value="<?php echo $this->dados['id_registro']?>">
		<fieldset id="fieldset-clientesfiles" class="form-horizontal">
		<div class="row-fluid formSep">
		<?php if($this->dadosnf['logotipodanfe'] <> ''){ ?>
		<div class="span4"><img src="/default/arquivos/get-logo-danfe/id/<?php echo $this->dadosnf['id_registro']?>"></div>
		<?php } ?>
		<div class="span3">
		<label for="arquivo" class="optional">Selecione o Documento:</label>
		<input type="hidden" name="MAX_FILE_SIZE" value="104857600" id="MAX_FILE_SIZE">
		<input type="file" name="arquivo" id="arquivo"  class="uni_style">
		</div>
		</div>
		</fieldset>
		<fieldset id="fieldset-botoes">
		<div style="text-align:right">
		<input type="reset" name="limparoutros" id="limparoutros" value="Limpar" class="btn btn-large btn-warning">
		<input type="submit" name="submitoutros" id="submitoutros" value="Salvar" class="btn btn-large btn-primary">
		</div>
		</fieldset>
		</form>	
		
				
		</div>
		<div class="tab-pane " id="tab_l4">
			<form id="clientesfiles" name="clientesfiles" enctype="multipart/form-data" class="form-horizontal" method="post" action="/sistema/empresas/salva-arquivo">
		<input type="hidden" name="tipofile" value="empresas" id="tipofile">
		<input type="hidden" name="idreg" value="<?php echo $this->dados['id_registro'] ?>" id="idreg">
		
		<fieldset id="fieldset-clientesfiles" class="form-horizontal">
		<div class="row-fluid formSep">
		
		<div class="span3">
		<label for="nomeamigavel" class="optional">Nome Amigavel:</label>
		<input type="text" name="nomeamigavel" id="nomeamigavel">
		</div>
		
		<div class="span3">
		<label for="arquivo" class="tags">Tags:</label>
		<input type="text" name="tags" id="tags">
		</div>
		
		<div class="span3">
		<label for="arquivo" class="optional">Selecione o Documento:</label>
		<input type="hidden" name="MAX_FILE_SIZE" value="104857600" id="MAX_FILE_SIZE">
		<input type="file" name="arquivo" id="arquivo"  class="uni_style">
		</div>
		
		</div>
		</fieldset>
		
		<fieldset id="fieldset-grupo20">
		<div class="row-fluid formSep">
		<div class="span11">
		<label for="obsfile" class="optional">Observações do Arquivo:</label>
		<textarea name="obsfile" id="obsfile" rows="5" style="width:100%" cols="80"></textarea>
		</div>
		</div>
		</fieldset>
		
		<fieldset id="fieldset-botoes">
		<div style="text-align:right">
		<input type="reset" name="limparoutros" id="limparoutros" value="Limpar" class="btn btn-large btn-warning">
		<input type="submit" name="submitoutros" id="submitoutros" value="Salvar" class="btn btn-large btn-primary">
		</div>
		</fieldset>
		</form>
		
		
	
		 <div class="row-fluid">
                        <div class="span12">
                            <h3 class="heading">Arquivos do Cadastro:</h3>
                            
                          	<table id="table-arquivos"  class="table table-striped table-bordered table-condensed">
		<thead>
		<tr>
			<th>Tipo:</th>
			<th>Nome</th>
			<th>Tags</th>
			<th>Opções</th>
			</tr>
		</thead>
		<tbody>
		<?php 
		if($this->arquivos){
		foreach($this->arquivos as $arquivo){?>
		<tr>
		<td><?php echo $arquivo['filetype'] ?></td>
		<td><?php echo $arquivo['nomeamigavel'] ?></td>
		<td><?php echo $arquivo['tags'] ?></td>
		<td><span class="pull-center"><a href="/system/files/get-file/id/<?php echo $arquivo['id_registro'] ?>" target="_blank" alt="Download do Arquivo" title="Download do Arquivo"><i class="splashy-folder_modernist_down"></i></a>  
		<a href="/system/files/render/id/<?php echo $arquivo['id_registro'] ?>" target="_blank" alt="Visualizar Arquivo" title="Visualizar  Arquivo"><i class="splashy-document_a4_marked"></i></a> 
		<i class="splashy-folder_modernist_remove removearquivo" idarquivo="<?php echo $arquivo['id_registro'] ?>" style="cursor:pointer"></i>
		</span></td>
		</tr>
		
		<?php  
		}
		}
		?>
		</tbody>
		
		</table>
                           </div>
                           </div>
		</div>
		
   </div>
   
   <script>
	$().ready(function(){
		$("#table-arquivos").dataTable({
		       "sPaginationType": "bootstrap_alt",
		       "oLanguage": {
					"sUrl": "/js/datatable_ptbr.txt"
				}
		    });
			

		});
   </script>