<div class="row-fluid">
<div class="span12">
<h3 class="heading">Lista de Empresas</h3>
<table id="listaclientes" class="table table-striped table-bordered">
<thead>
<tr>
<th width="5%"><i class="splashy-star_empty"></i></th>
<th width="5%">ID</th>
<th width="30%">Razao Social</th>
<th width="20%">CNPJ</th>
<th width="30%">Nome Fantasia</th>
<th width="5%">Opções</th>
</tr>
</thead>
<tbody>
<tr>
<td class="dataTables_empty" colspan="6">Não existem dados nessa consulta!</td>
</tr>
</tbody>
</table>
</div>
</div>
<script>
$().ready(function(){

	$('#listaclientes').dataTable({
		"oLanguage": {
		"sUrl": "/js/datatable_ptbr.txt"
		},
		 "aaSorting": [[1,'asc']],
		"sPaginationType": "bootstrap",
		"bProcessing": true,
		"bServerSide": true,
		"sAjaxSource": "/system/datatables/empresas"


	});

	$('.enpstar').live('click', function(){
		$('.splashy-star_full').toggleClass('splashy-star_empty');
		$(this).toggleClass('splashy-star_empty splashy-star_full');
		
		idmessage =  $(this).attr('idemp');
		 $.ajax({ 
				type: "GET", 
				url: "/sistema/empresas/setdefaultenp", 
				data: "id="+idmessage ,
				beforeSend: function() {
										
		 		}, 
				success: function(txt) { 
					$('#listaclientes').dataTable().fnDraw();
																											
				}, 
				error: function(txt) { 
					$.sticky("Um erro ocorreu.", { type: 'st-error' });
				} 
			}); 
		
	});
	
});


	</script>