<div class="row-fluid">
<div class="span12">
<h3 class="heading">Perfil de Faturamento NFe
<span class="pull-right"><a href="/system/faturamento/novo-perfil-faturamento/" class="btn btn-gebo">Novo Perfil</a></span></h3>
<table id="listaclientes" class="table table-striped table-bordered">
<thead>
<tr>
<th width="5%">ID</th>
<th width="30%">Nome</th>
<th width="15%">CFOP</th>
<th width="45%">Natureza Operação</th>
<th width="5%">Opções</th>
</tr>
</thead>
<tbody>
<?php foreach($this->dados as $dado){ 	?>
<tr>
<td width="5%"><?php echo $dado->id_registro ?></td>
<td><?php echo $dado->nomedoperfil ?></td>
<td><?php echo $dado->cfop ?></td>
<td><?php echo $dado->naturezaoperacao ?></td>
<td width="5%">
<a href="/system/faturamento/edita-perfil-faturamento/id/<?php echo $dado->id_registro ?>"><i class="splashy-hcards_edit" style="cursor:pointer" ></i></a> 
<i class="splashy-hcards_remove removereg" idreg="<?php echo $dado->id_registro ?>" style="cursor:pointer" ></i></span></td>
</tr>
<?php }; ?>
</tbody>
</table>
</div>
</div>