<!DOCTYPE html>
<html lang="en" class="login_page">
    <head>
        <meta charset="utf-8">
        <meta name="viewport" content="width=device-width, initial-scale=1.0" />
        <title><?php echo $this->SysName ?> - Login </title>
    
        <!-- Bootstrap framework -->
            <link rel="stylesheet" href="/bootstrap/css/bootstrap.min.css" />
            <link rel="stylesheet" href="/bootstrap/css/bootstrap-responsive.min.css" />
        <!-- theme color-->
            <link rel="stylesheet" href="/css/blue.css" />
        <!-- tooltip -->    
			<link rel="stylesheet" href="/lib/qtip2/jquery.qtip.min.css" />
        <!-- main styles -->
            <link rel="stylesheet" href="/css/style.css" />
    
        <!-- Favicon -->
            <link rel="shortcut icon" href="/favicon.ico" />
    
        <link href='http://fonts.googleapis.com/css?family=PT+Sans' rel='stylesheet' type='text/css'>
    
        <!--[if lte IE 8]>
            <script src="js/ie/html5.js"></script>
			<script src="js/ie/respond.min.js"></script>
        <![endif]-->
		
    </head>
    <body>

		<div class="login_box">
			
			<form action="/default/index/index" method="post" id="login_form">
				<div class="top_b"><?php echo $this->SysName ?></div>    
				<?php if($this->LoginError){ ?>
				<div class="alert alert-error alert-login">
					Usuário ou senha inválidos!
				</div>
				<?php } ?>
				<div class="cnt_b">
					<div class="formRow">
						<div class="input-prepend">
							<span class="add-on"><i class="icon-user"></i></span><input type="text" id="username" name="username" placeholder="Usuário" value="" />
						</div>
					</div>
					<div class="formRow">
						<div class="input-prepend">
							<span class="add-on"><i class="icon-lock"></i></span><input type="password" id="password" name="password" placeholder="Senha" value="" />
						</div>
					</div>
					<div class="formRow clearfix">
					</div>
				</div>
				<div class="btm_b clearfix">
					<button class="btn btn-inverse pull-right" type="submit">Entrar >></button>
				</div>  
			</form>
			
			<form action="default/index/forgotpass" method="post" id="pass_form" style="display:none">
				<div class="top_b">Esqueceu sua senha?</div>    
					<div class="alert alert-info alert-login">
					Entre com o seu email e enviaremos uma senha temporária a você!
				</div>
				<div class="cnt_b">
					<div class="formRow clearfix">
						<div class="input-prepend">
							<span class="add-on">@</span><input type="text" placeholder="Digite o seu email" />
						</div>
					</div>
				</div>
				<div class="btm_b tac">
					<button class="btn btn-inverse" type="submit">Solicitar nova senha</button>
				</div>  
			</form>
			
		
			
			<div class="links_b links_btm clearfix">
				<span class="linkform"><a href="#pass_form">Esqueceu sua senha?</a></span>
				<span class="linkform" style="display:none">Não se preocupe, <a href="#login_form">retornar a tela de login!</a></span>
			</div>
		</div>
		
		<div class="modal hide fade" id="myModal2"><img src="/img/msg-acesso-negado.jpg" width='100%'></div>
		
        <script src="/js/jquery.min.js"></script>
        <script src="/js/jquery.actual.min.js"></script>
        <script src="/lib/validation/jquery.validate.min.js"></script>
		<script src="/bootstrap/js/bootstrap.min.js"></script>
        <script>
            $(document).ready(function(){
            	$('#myModal2').modal('show')
                
				//* boxes animation
				form_wrapper = $('.login_box');
				function boxHeight() {
					form_wrapper.animate({ marginTop : ( - ( form_wrapper.height() / 2) - 24) },400);	
				};
				form_wrapper.css({ marginTop : ( - ( form_wrapper.height() / 2) - 24) });
                $('.linkform a,.link_reg a').on('click',function(e){
					var target	= $(this).attr('href'),
						target_height = $(target).actual('height');
					$(form_wrapper).css({
						'height'		: form_wrapper.height()
					});	
					$(form_wrapper.find('form:visible')).fadeOut(400,function(){
						form_wrapper.stop().animate({
                            height	 : target_height,
							marginTop: ( - (target_height/2) - 24)
                        },500,function(){
                            $(target).fadeIn(400);
                            $('.links_btm .linkform').toggle();
							$(form_wrapper).css({
								'height'		: ''
							});	
                        });
					});
					e.preventDefault();
				});
				
				//* validation
				$('#login_form').validate({
					onkeyup: false,
					errorClass: 'error',
					validClass: 'valid',
					rules: {
						username: { required: true, minlength: 3 },
						password: { required: true, minlength: 3 }
					},
					highlight: function(element) {
						$(element).closest('div').addClass("f_error");
						setTimeout(function() {
							boxHeight()
						}, 200)
					},
					unhighlight: function(element) {
						$(element).closest('div').removeClass("f_error");
						setTimeout(function() {
							boxHeight()
						}, 200)
					},
					errorPlacement: function(error, element) {
						$(element).closest('div').append(error);
					}
				});
            });
        </script>
    </body>
</html>

