<?php 
$configs = Zend_Registry::get('configs');
	   
?>
<!DOCTYPE html>
<html lang="pt-BR">
    <head>
        <meta charset="utf-8" />
        <meta name="viewport" content="width=device-width, initial-scale=1.0" />
        <title><?php echo $configs->Leader->SysName ?></title>
    
        <!-- Bootstrap framework -->
            <link rel="stylesheet" href="/bootstrap/css/bootstrap.min.css" />
            <link rel="stylesheet" href="/bootstrap/css/bootstrap-responsive.min.css" />
              <link rel="stylesheet" href="http://code.jquery.com/ui/1.9.0/themes/base/jquery-ui.css" />
        <!-- gebo blue theme-->
            <link rel="stylesheet" href="/css/blue.css" id="link_theme" />
        <!-- breadcrumbs-->
            <link rel="stylesheet" href="/lib/jBreadcrumbs/css/BreadCrumb.css" />
        <!-- tooltips-->
            <link rel="stylesheet" href="/lib/qtip2/jquery.qtip.min.css" />
        <!-- colorbox -->
            <link rel="stylesheet" href="/lib/colorbox/colorbox.css" />    
        <!-- code prettify -->
            <link rel="stylesheet" href="/lib/google-code-prettify/prettify.css" />    
        <!-- notifications -->
            <link rel="stylesheet" href="/lib/sticky/sticky.css" />    
        <!-- splashy icons -->
            <link rel="stylesheet" href="/img/splashy/splashy.css" />
		<!-- flags -->
            <link rel="stylesheet" href="/img/flags/flags.css" />	
		<!-- calendar -->
            <link rel="stylesheet" href="/lib/fullcalendar/fullcalendar_gebo.css" />
            
            
            
          <!-- datepicker -->
            <link rel="stylesheet" href="/lib/datepicker/datepicker.css" />
        <!-- tag handler -->
            <link rel="stylesheet" href="/lib/tag_handler/css/jquery.taghandler.css" />
        <!-- nice form elements -->
            <link rel="stylesheet" href="/lib/uniform/Aristo/uniform.aristo.css" />
		<!-- 2col multiselect -->
            <link rel="stylesheet" href="/lib/multiselect/css/multi-select.css" />
		<!-- enhanced select -->
            <link rel="stylesheet" href="/lib/chosen/chosen.css" />
        <!-- upload -->
            <link rel="stylesheet" href="/lib/plupload/js/jquery.plupload.queue/css/plupload-gebo.css" />
		<!-- colorbox -->
            <link rel="stylesheet" href="/lib/colorbox/colorbox.css" />
		<!-- colorpicker -->
            <link rel="stylesheet" href="/lib/colorpicker/css/colorpicker.css" />	  
            <link rel="stylesheet" href="/lib/tag_handler/css/jquery.taghandler.css" />
            
            
            
        <!-- main styles -->
            <link rel="stylesheet" href="/css/style.css" />
			
            <link rel="stylesheet" href="http://fonts.googleapis.com/css?family=PT+Sans" />
	
        <!-- Favicon -->
            <link rel="shortcut icon" href="/favicon.ico" />
		
        <!--[if lte IE 8]>
            <link rel="stylesheet" href="css/ie.css" />
            <script src="/js/ie/html5.js"></script>
			<script src="/js/ie/respond.min.js"></script>
			<script src="/lib/flot/excanvas.min.js"></script>
        <![endif]-->
		
		<script>
			//* hide all elements & show preloader
			document.documentElement.className += 'js';
		</script>
		
		<!-- JAVASCRIPT -->
		 <script src="/js/jquery.min.js"></script>
			<!-- smart resize event -->
			<script src="/js/jquery.debouncedresize.min.js"></script>
			<!-- hidden elements width/height -->
			<script src="/js/jquery.actual.min.js"></script>
			<!-- js cookie plugin -->
			<script src="/js/jquery.cookie.min.js"></script>
			<!-- main bootstrap js -->
			<script src="/bootstrap/js/bootstrap.min.js"></script>
			<!-- tooltips -->
			<script src="/lib/qtip2/jquery.qtip.min.js"></script>
			<!-- jBreadcrumbs -->
			<script src="/lib/jBreadcrumbs/js/jquery.jBreadCrumb.1.1.min.js"></script>
			<!-- lightbox -->
            <script src="/lib/colorbox/jquery.colorbox.min.js"></script>
            <!-- fix for ios orientation change -->
			<script src="/js/ios-orientationchange-fix.js"></script>
			<!-- scrollbar -->
			<script src="/lib/antiscroll/antiscroll.js"></script>
			<script src="/lib/antiscroll/jquery-mousewheel.js"></script>
			<!-- to top -->
			<script src="/lib/UItoTop/jquery.ui.totop.min.js"></script>
			 <script src="/js/selectNav.js"></script>
			<!-- common functions -->
			
			
			<script src="/lib/jquery-ui/jquery-ui-1.8.23.custom.min.js"></script>
            <!-- touch events for jquery ui-->
            <script src="/js/forms/jquery.ui.touch-punch.min.js"></script>
            <!-- multi-column layout -->
            <script src="/js/jquery.imagesloaded.min.js"></script>
            <script src="/js/jquery.wookmark.js"></script>
            <!-- responsive table -->
            <script src="/js/jquery.mediaTable.min.js"></script>
            <!-- small charts -->
            <script src="/js/jquery.peity.min.js"></script>
            <!-- charts -->
            <script src="/lib/flot/jquery.flot.min.js"></script>
            <script src="/lib/flot/jquery.flot.resize.min.js"></script>
            <script src="/lib/flot/jquery.flot.pie.min.js"></script>
            <!-- calendar -->
            <script src="/lib/fullcalendar/fullcalendar.min.js"></script>
            <!-- sortable/filterable list -->
            <script src="/lib/list_js/list.min.js"></script>
            <script src="/lib/list_js/plugins/paging/list.paging.min.js"></script>
            <script src="/lib/sticky/sticky.min.js"></script>
             <script src="/lib/validation/jquery.validate.min.js"></script>
             
               <!-- masked inputs -->
            <script src="/js/forms/jquery.inputmask.min.js"></script>
            <!-- autosize textareas -->
            <script src="/js/forms/jquery.autosize.min.js"></script>
            <!-- textarea limiter/counter -->
            <script src="/js/forms/jquery.counter.min.js"></script>
            <!-- datepicker -->
            <script src="/lib/datepicker/bootstrap-datepicker.min.js"></script>
            <!-- timepicker -->
            <script src="/lib/datepicker/bootstrap-timepicker.min.js"></script>
            <!-- tag handler -->
            <script src="/lib/tag_handler/jquery.taghandler.min.js"></script>
            <!-- input spinners -->
            <script src="/js/forms/jquery.spinners.min.js"></script>
            <!-- styled form elements -->
            <script src="/lib/uniform/jquery.uniform.min.js"></script>
            <!-- animated progressbars -->
            <script src="/js/forms/jquery.progressbar.anim.js"></script>
            <!-- multiselect -->
            <script src="/lib/multiselect/js/jquery.multi-select.min.js"></script>
            <!-- enhanced select (chosen) -->
            <script src="/lib/chosen/chosen.jquery.min.js"></script>
            <!-- TinyMce WYSIWG editor -->
            <script src="/lib/tiny_mce/jquery.tinymce.js"></script>
			<!-- plupload and all it's runtimes and the jQuery queue widget (attachments) -->
			<script type="text/javascript" src="/lib/plupload/js/plupload.full.js"></script>
			<script type="text/javascript" src="/lib/plupload/js/jquery.plupload.queue/jquery.plupload.queue.full.js"></script>
            <!-- colorpicker -->
			<script src="/lib/colorpicker/bootstrap-colorpicker.js"></script>
			<!-- password strength checker -->
			<script src="/lib/complexify/jquery.complexify.min.js"></script>
			 <script src="/lib/datepicker/locales/bootstrap-datepicker.br.js"></script>
			  <script src="/js/jquery.form.js"></script>
			              <script src="/lib/datatables/jquery.dataTables.min.js"></script>
            <script src="/lib/datatables/extras/Scroller/media/js/Scroller.min.js"></script>
        
            <!-- dashboard functions -->
            <script src="/js/gebo_common.js"></script>
   
            
    </head>
    <body>
		<div id="loading_layer" style="display:none"><img src="/img/ajax_loader.gif" alt="" /></div>
		
		
		<div id="maincontainer" class="clearfix">
			<!-- header -->
            <header>
                <div class="navbar navbar-fixed-top">
                    <div class="navbar-inner">
                        <div class="container-fluid">
                            <a class="brand" href="javascript:void(0)"><i class="icon-home icon-white"></i> <?php echo $configs->Leader->SysName ?></a>
                          	<a data-target=".nav-collapse" data-toggle="collapse" class="btn_menu">
								<span class="icon-align-justify icon-white"></span>
							</a>
                      
                        </div>
                    </div>
                </div>
                 
               
            </header>
                <!-- main content -->
            <div id="contentwrapper">
                <div class="main_content">
                
                     <?php if ($this->DebugEnable){ ?>
                               <div class="alert">
                               <a class="close" data-dismiss="alert">x</a>
                               <strong>O Debug do Sistema está ativo, todas as mensagens de erro serão exibidas</strong>
                               </div>
                               
                                <?php 
								}
								
								if($this->AlertMessage){
									foreach($this->AlertMessage as $message){
									echo $message;
									}
								};



                                ?>
               
                      <?php
                            echo $this->layout()->content 
             ?>
                
                </div>
             </div>
            
            
		           
           
    
			<script>
				$(document).ready(function() {
					//* show all elements & remove preloader
					setTimeout('$("html").removeClass("js")',1000);
				});

				
			</script>
		
		</div>
	</body>
</html>