<script src="/js/gebo_dashboard.js"></script>
<style>
#spin1, #spin2, #spin3 {
        width:200px; height:160px;
		display: inline-block;
      }
</style>
<div id="contentwrapper">
                <div class="main_content">
                    
					
					<div class="row-fluid">
					 <div class="span6">
							<div class="heading clearfix">
								<h3 class="pull-left">Últimas Novidades <small>(32.DLL)</small></h3>
								<span class="pull-right label label-info ttip_t" title="Informações da 32.DLL">Informações</span>
							</div>
							sdfsdfsdf
							</div>
							
							 <div class="span6">
							<div class="heading clearfix">
								<h3 class="pull-left">Avisos do Sistema<small>(32.DLL)</small></h3>
								<span class="pull-right label label-important ttip_t" title="Informações Importantes sobre o sistema">Importante</span>
							</div>
							<?php if($this->UserInfo->recoverpass == 1){ ?>
							<div class="alert alert-block alert-error fade in">
								<h4 class="alert-heading">Usuário Bloqueado</h4>
								<p>Foi solicitada uma troca de senha através da recuperação de dados pelo seu usuário, ou seu cadastro é novo no sistema<br>
								Recomendamos que você troque a sua senha agora!</p>
								<p><a href="/dashboard/user/profile/" class="btn btn-inverse"> <i class="splashy-check"></i> Trocar Senha </a></p>								
							</div>
							<?php } 
							
							if($this->AlertSysMessage){
									foreach($this->AlertSysMessage as $message){
									echo $message;
									}
								};
								?>
							
						</div>
							</div>

							
							<div class="row-fluid">
 							<div class="span6">
							<div id="vendasfunil" width="100%"></div>
							</div>
							
							 <div class="span6">
							<div id="receitasdespesas" width="100%"></div>
							</div>


</div>

<div class="row-fluid">
 <div class="span6">
							<div class="heading clearfix">
								<h3 class="pull-left">Contas a Receber <small>X</small></h3>
								<span class="pull-right label label-info ttip_t" title="Here is a sample info tooltip">X</span>
							</div>
							sdfsdfsdf
							</div>
							
							 <div class="span6">
							<div class="heading clearfix">
								<h3 class="pull-left">Contas a Pagar <small>X</small></h3>
								<span class="pull-right label label-important ttip_t" title="Here is a sample info tooltip">X</span>
							</div>
							sdfsdfsdf
							</div>


</div>

<div class="row-fluid">
 <div class="span6">
 <div class="heading clearfix">
								<h3 class="pull-left">Produção</h3>
								
							</div>
							<div id="spin1"></div>
							<div id="spin2"></div>
							<div id="spin3"></div>
							</div>
							
							 <div class="span6">
							 	<div class="heading clearfix">
								<h3 class="pull-left">Produtos em Aleta: <small>Quantidade menor que a mínima</small></h3>
								<span class="pull-right label label-important ttip_t" title="Quantidade menor que a minima!"><?php echo Cadastros_Model_Produtos::countProdutosAlerta() ?></span>
							</div>
							<table id="produtosalerta" class="table table-striped table-bordered">
<thead>
<tr>

<th width="5%">Cod</th>
<th width="45%">Produto</th>
<th width="15%">Referência</th>
<th width="5%">Estoque</th>
<th width="5%">Minimio</th>

</tr>
</thead>
<tbody>
<?php 
$produtosalerta = Cadastros_Model_Produtos::getProdutosAlerta();
foreach($produtosalerta as $prodale){ 
?>
<tr>
<td width="5%"><?php echo $prodale['codigointerno'] ?></td>
<td width="45%"><?php echo $prodale['nomeproduto'] ?></td>
<td width="15%"><?php echo $prodale['referenciaproduto'] ?></td>
<td width="5%"><?php echo number_format($prodale['estoqueatual'],3,',','') ?></td>
<td width="5%"><?php echo number_format($prodale['estoqueminimo'],3,',','') ?></td>
</tr>
<?php  } ?>
</tbody>
</table>
							
							</div>
 
 </div>
							
</div></div>


<script src="/lib/highcharts/js/highcharts.js"></script>
<script src="/lib/highcharts/js/modules/funnel.js"></script>
<script src="/lib/highcharts/js/modules/exporting.src.js"></script>


 <script>
$().ready(function(){

	$('#produtosalerta').dataTable({
		"sPaginationType": "bootstrap",
		"oLanguage": {
			"sUrl": "/js/datatable_ptbr.txt"
		}
                    
    });

	 var g1 = new JustGage({
         id: "spin1", 
         value: <?php echo Erp_Model_Producao_Registros::GetSomaOPs(implode(',', Erp_Model_Producao_Basicos::getItensProducao()),'','0')?>, 
         min: 0,
         max: <?php echo Erp_Model_Producao_Basicos::getTotalProducao() ?>,
         title: "Itens em Produção",
         levelColorsGradient: false,
         label: "Produzidos"
       });

	 var g2 = new JustGage({
         id: "spin2", 
         value: 75, 
         min: 50,
         max: <?php echo Erp_Model_Producao_Basicos::getTotalProducao() ?>,
         title: "Produção em Dia",
         label: "Itens em dia"
       });

	 var g3 = new JustGage({
         id: "spin3", 
         value: 90, 
         min: 50,
         max: <?php echo Erp_Model_Producao_Basicos::getTotalProducao() ?>,
         title: "Produção Atrasada",
         label: "Itens em Atraso"
       });
     
    
	   $('#vendasfunil').highcharts({
	        chart: {
	            type: 'funnel',
	            marginRight: 100
	        },
	        title: {
	            text: 'Funil de Vendas',
	            x: -50
	        },
	        plotOptions: {
	            series: {
	                dataLabels: {
	                    enabled: true,
	                    format: '<b>{point.name}</b>({point.y:,.0f})',
	                    color: 'black',
	                    softConnector: true
	                },
	                neckWidth: '30%',
	                neckHeight: '25%'
	            }
	        },
	        legend: {
	            enabled: false
	        },
	        series: [{
	            name: 'Processos Gerais',
	            data: [
	                ['Novos Prospects',6757],
	                ['Orçamentos Emitidos',4064],
	                ['Orçamentos Aprovados',3987],
	                ['Vendas Emitidas',976],
	                ['Vendas Faturadas',7985]
	            ]
	        }]
	    });


	   $('#receitasdespesas').highcharts({
           chart: {
               type: 'line',
               marginRight: 130,
               marginBottom: 25
           },
           title: {
               text: 'Receitas e Despesas',
               x: -20 //center
           },
           subtitle: {
               text: '(Realizado e Previsto)',
               x: -20
           },
           xAxis: {
               categories: [<?php echo implode(',',Functions_Datas::getMonthsGraprh()) ?>]
           },
           yAxis: {
               title: {
                   text: 'Valores (R$)'
               },
               plotLines: [{
                   value: 0,
                   width: 1,
                   color: '#808080'
               }]
           },
           tooltip: {
               valuePreffix: 'R$'
           },
           legend: {
               layout: 'vertical',
               align: 'right',
               verticalAlign: 'top',
               x: -10,
               y: 100,
               borderWidth: 0
           },
           series: [{
               name: 'Receitas Realizadas',
               data: [<?php echo $this->recRealizadoGrafico ?>]
           }, {
               name: 'Despesas Realizadas',
               data: [<?php echo $this->pagRealizadoGrafico ?>]
           }, {
               name: 'Receitas Previstas',
               data: [<?php echo $this->recPrevistoGrafico ?>],
               marker: {
                   enabled: false
               },
               color: 'blue',
               dashStyle: 'shortdot'
           }, {
               name: 'Despesas Previstas',
               data: [<?php echo $this->pagPrevistoGrafico ?>],
               marker: {
                   enabled: false
               },
               color: 'red',
               dashStyle: 'shortdot'
           }]
       });

});


</script>