<div class="row-fluid">
<div class="span12">
<h3 class="heading">Lista de Pessoas</h3>
<table id="listaclientes" class="table table-striped table-bordered">
<thead>
<tr>
<th width="5%">ID</th>
<th width="5%">Empresa</th>
<th width="30%">Razão Social</th>
<th width="10%">CNPJ</th>
<th width="25%">Nome Fantasia</th>
<th width="5%">Alterações</th>
<th width="5%">Opções</th>
</tr>
</thead>
<tbody>
<tr>
<td class="dataTables_empty" colspan="6">Não existem dados nessa consulta!</td>
</tr>
</tbody>
</table>
</div>
</div>
<script>
$().ready(function(){

	$('#listaclientes').dataTable({
		"oLanguage": {
			"sUrl": "/js/datatable_ptbr.txt"
		},
		"sPaginationType": "bootstrap",
        "bProcessing": true,
		"bServerSide": true,
        "sAjaxSource": "/system/datatables/pessoas/type/<?php echo $this->cadType ?>"
               	
                    
    });


});


</script>