<div class="row-fluid">
<div class="span12">
<h3 class="heading">Contas Bancárias
<span class="pull-right"><a data-toggle="modal" href="/system/financeiro/nova-conta" data-target="#EditLancModal"><i style="cursor:pointer" class="splashy-document_a4_new newdepto ttip_b" title="Nova Conta"></i></a></span></h3>
<table id="listaclientes" class="table table-striped table-bordered">
<thead>
<tr>
<th width="5%">ID</th>
<th width="85%">Nun:</th>
<th width="85%">Banco:</th>
<th width="85%">Agência:</th>
<th width="85%">Conta:</th>
<th width="5%">Opções</th>
</tr>
</thead>
<tbody>
<?php foreach($this->dados as $dado){ ?>
<tr>
<td width="5%"><?php echo $dado->id_registro ?></td>
<td width="10%"><?php echo $dado->numerobanco ?></td>
<td width="35%"><?php echo $dado->nomebanco ?></td>
<td width="15%"><?php echo $dado->agencia ?></td>
<td width="15%"><?php echo $dado->conta ?></td>
<td width="5%">
<a data-toggle="modal" href="/system/financeiro/nova-conta/id/<?php echo $dado->id_registro ?>" data-target="#EditLancModal">
<i class="splashy-hcards_edit editdepto" idreg="<?php echo  $dado->id_registro ?>" style="cursor:pointer" ></i></a>
 <a data-toggle="modal" href="/system/financeiro/deleta-conta/id/<?php echo $dado->id_registro ?>" data-target="#CancelModal">
 <i class="splashy-hcards_remove removedepto"  idreg="<?php echo $dado->id_registro ?>" style="cursor:pointer" ></i></a>
 </td>
</tr>
<?php }; ?>
</tbody>
</table>
</div>
</div>

<div class="modal hide fade" id="EditLancModal">
 <form id="editaLancamento" name="editaLancamento" method="post" action="/system/financeiro/nova-conta">
 <div class="modal-header">
   <button class="close" data-dismiss="modal">×</button>
   <h3>Conta Corrente:</h3>
   </div>
 <div class="modal-body"></div>
  <div class="modal-footer">
<input type="submit" name="submit" id="submiteditnote" value="Salvar" class="btn btn-large btn-primary">
</div>
</form>
 </div>
 
 
  <div class="modal hide fade" id="CancelModal">
 <form id="cancelalancamento" name="cancelalancamento" method="post" action="/system/financeiro/deleta-conta">
 <div class="modal-header">
   <button class="close" data-dismiss="modal">×</button>
   <h3>Confirmar Cancelamento:</h3>
   </div>
 <div class="modal-body">

 </div>
  <div class="modal-footer">
<input type="submit" name="submit" id="submiteditnote" value="CONFIRMAR" class="btn btn-large btn-primary">
</div>
</form>
 </div>
	<div id="ModelPre"><?php 
 $captcha = new Zend_Service_ReCaptcha('6Ldk6-ISAAAAALqcpxh2182Y0Yd8ZqHr2p_QIGoO','6Ldk6-ISAAAAAHpOarrRAqW6S9uvJEdERs2MgP6h');
 echo $captcha->getHTML() ?></div>
<div id="ajaxrequest"></div>

<script>
$().ready(function(){
	$("#ModelPre").hide();
	
	$('#listaclientes').dataTable({
		"oLanguage": {
			"sUrl": "/js/datatable_ptbr.txt"
		},
		"sPaginationType": "bootstrap"
                     	
                    
    });



  

    $("a[data-target=#EditLancModal]").live('click',function(ev) {
	    ev.preventDefault();
	    var target = $(this).attr("href");

	    // load the url and show modal on success
	    $("#EditLancModal .modal-body").load(target, function() { 
	         $("#EditLancModal").modal("show"); 
	    });
	});	

	

    $("a[data-target=#CancelModal]").live('click',function(ev) {
	    ev.preventDefault();
	    var target = $(this).attr("href");
	    $("#CancelModal .modal-body").load(target, function() {
	         showRecaptcha('captchadiv');
	         $("#CancelModal").modal("show"); 
	         showRecaptcha('captchadiv');
	    });
	});	


    $('#cancelalancamento').validate({
		onkeyup: false,
		errorClass: 'error',
		validClass: 'valid',
		highlight: function(element) {
			$(element).closest('div').addClass("f_error");
		},
		unhighlight: function(element) {
			$(element).closest('div').removeClass("f_error");
		},
  errorPlacement: function(error, element) {
      $(element).closest('div').append(error);
  },

  invalidHandler: function(form, validator) {
			$.sticky("Existem campos obrigatórios não preenchidos no formulário, corrija estes erros e tente novamente.", {autoclose : 5000, position: "top-right", type: "st-error" });
		},
		submitHandler: function(form) {
			jQuery(form).ajaxSubmit({
				target: "#ajaxrequest",
				beforeSubmit:   function(){ 
					$.sticky("Validando Solicitação.", {autoclose : 5000, position: "top-right", type: "st-info" });
					
				}, 
			error: function(txt) { 
				$.sticky("Ocorreu um erro com sua solicitação: "+ txt, {autoclose : 5000, position: "top-right", type: "st-error" });
				$("#ajaxrequest").html("Erro" + txt);
				//reloadtable();
				
			},
			success: function(txt){
				if(txt == "ERRO"){
					$.sticky("CARACTERES INCORRETOS TENTE NOVAMENTE.", {autoclose : 10000, position: "top-right", type: "st-error" });
					showRecaptcha('captchadiv');
					$("#ajaxrequest").html('');
				}else{
				$.sticky("CONTA EXCLUÍDA COM SUCESSO.", {autoclose : 5000, position: "top-right", type: "st-success" });
				$("#CancelModal").modal('hide');  
			//	reloadtable();
				
				$("#ajaxrequest").html('');

				location.reload(); 
				}
				
				
		
			},
		        clearForm: true
				
			});
		}
});


$('#editaLancamento').validate({
	onkeyup: false,
	errorClass: 'error',
	validClass: 'valid',
	highlight: function(element) {
		$(element).closest('div').addClass("f_error");
	},
	unhighlight: function(element) {
		$(element).closest('div').removeClass("f_error");
	},
errorPlacement: function(error, element) {
  $(element).closest('div').append(error);
},

invalidHandler: function(form, validator) {
		$.sticky("Existem campos obrigatórios não preenchidos no formulário, corrija estes erros e tente novamente.", {autoclose : 5000, position: "top-right", type: "st-error" });
	},
	submitHandler: function(form) {
		jQuery(form).ajaxSubmit({
			target: "#ajaxrequest",
			beforeSubmit:   function(){ 
				$.sticky("Validando Solicitação.", {autoclose : 5000, position: "top-right", type: "st-info" });
				
			}, 
		error: function(txt) { 
			$.sticky("Ocorreu um erro com sua solicitação: "+ txt, {autoclose : 5000, position: "top-right", type: "st-error" });
			$("#ajaxrequest").html("Erro" + txt);
			//reloadtable();
			
		},
		success: function(txt){
		
				$.sticky(txt, {autoclose : 5000, position: "top-right", type: "st-success" });
				$("#EditLancModal").modal('hide');  
				//reloadtable();
				location.reload(); 
				$("#ajaxrequest").html('');
			
			
	
		},
	        clearForm: true
			
		});
	}
});


});

function showRecaptcha(element) {
    Recaptcha.create("6Ldk6-ISAAAAALqcpxh2182Y0Yd8ZqHr2p_QIGoO", element, {
      theme: "red",
      callback: Recaptcha.focus_response_field});
  }


</script>
