<?php echo $this->form->id_registro ?>
 <div class="row-fluid">
 <div class="span4">
 <?php echo $this->form->numerobanco ?>
 </div>
 <div class="span8">
 <?php echo $this->form->nomebanco ?>
 </div>
 </div>
 <div class="row-fluid formSep">
 <div class="span4">
 <?php echo $this->form->agencia ?>
 </div>
 <div class="span8">
 <?php echo $this->form->conta ?>
 </div>
 </div>
 <div class="row-fluid">
 <div class="span12">
 <h3 class="heading">Emissão de Boleto:</h3>
 </div>
  </div>
     <div class="row-fluid">
     <div class="span6">
 <?php echo $this->form->carteirapadrao ?>
 </div>
 <div class="span6">
 <?php echo $this->form->valoremissaoboleto ?>
 </div>
   
   </div>
   
   <div class="row-fluid">
     <div class="span4">
 <?php echo $this->form->convenio ?>
 </div>
 <div class="span4">
 <?php echo $this->form->variacaocarteira ?>
 </div>
 <div class="span4">
 <?php echo $this->form->codigocliente ?>
 </div>
  
   </div>
     <div class="row-fluid">
     <div class="span12">
     <?php echo $this->form->msgboleto_l1 ?>
     </div>
     </div>
     
     <div class="row-fluid">
     <div class="span12">
     <?php echo $this->form->msgboleto_l2 ?>
     </div>
     </div>
     
     <div class="row-fluid">
     <div class="span12">
     <?php echo $this->form->msgboleto_l3 ?>
     </div>
     </div>
     
     <div class="row-fluid">
     <div class="span12">
     <?php echo $this->form->msgboleto_l4 ?>
     </div>
     </div>
     
      <div class="row-fluid">
     <div class="span12">
     <?php echo $this->form->localpagamento_l1 ?>
     </div>
     </div>
     
     <div class="row-fluid">
     <div class="span12">
     <?php echo $this->form->localpagamento_l2 ?>
     </div>
     </div>
     
     <div class="row-fluid">
     <div class="span12">
     <?php echo $this->form->localpagamento_l3 ?>
     </div>
     </div>