<div class="row-fluid">
<div class="span12">
<h3 class="heading">Perfil de Pagamento / Parcelamento
<span class="pull-right"><i style="cursor:pointer" class="splashy-document_a4_new newdepto ttip_b" title="Novo Perfil"></i></span></h3>
<table id="listaclientes" class="table table-striped table-bordered">
<thead>
<tr>
<th width="5%">ID</th>
<th width="30%">Nome</th>
<th width="15%">Tipo Perfil</th>
<th width="15%">Parcelas</th>
<th width="15%">Intervalo</th>
<th width="15%">Tipo Intervalo</th>
<th width="5%">Opções</th>
</tr>
</thead>
<tbody>
<?php foreach($this->dados as $dado){ 
if($dado->tipoperfil == '0'){
$tipoperfil = "Primeira a Vista";
}else{
$tipoperfil = "Primeira em Parcela";
}
	?>
<tr>
<td width="5%"><?php echo $dado->id_registro ?></td>
<td><?php echo $dado->nomeperfil ?></td>
<td><?php echo $tipoperfil ?></td>
<td><?php echo number_format($dado->quantidadeparcelas,0) ?></td>
<td><?php echo number_format($dado->intervalorparcelas,0) ?></td>
<td><?php echo $dado->tipointervalo ?></td>
<td width="5%">
<a data-toggle="modal" href="/system/financeiro/edita-perfil/id/<?php echo $dado->id_registro ?>" data-target="#EditarMod"><i class="splashy-hcards_edit editreg" idreg="<?php echo  $dado->id_registro ?>" style="cursor:pointer" ></i></a> 
<i class="splashy-hcards_remove removereg" idreg="<?php echo $dado->id_registro ?>" style="cursor:pointer" ></i></span></td>
</tr>
<?php }; ?>
</tbody>
</table>
</div>
</div>

<div class="modal hide fade" id="NovoPerfil">
 <form id="editaLancamento" name="editaLancamento" method="post" action="">
 <input type="hidden" id="id_registro" name="id_registro"  value="0"/>
 <input type="hidden" id="tiporegistro" name="tiporegistro"  value="novo"/>
 <div class="modal-header">
   <button class="close" data-dismiss="modal">×</button>
   <h3>Perfil de Pagamento:</h3>
   </div>
 <div class="modal-body">
<div class="row-fluid formSep">
<div class="span6">
<label  for="nomeperfil">Nome do Perfil</legend>
<input type="text" name="nomeperfil" id="nomeperfil" class="span12" >
</div>
<div class="span6">
<label  for="tipoperfil">Tipo de Perfil</legend>
<select name="tipoperfil" id="tipoperfil">
<option value="0">Primeira a Vista</option>
<option value="1">Primeira Parcelado</option>
</select>
</div>
</div>
<div class="row-fluid">
<div class="span3">
<label  for="quantidadeparcelas">Qtd de Parcelas</legend>
 <input type="text" id="quantidadeparcelas" name="quantidadeparcelas" class="span4" value="1"/>
</div>
<div class="span3">
<label  for="intervalorparcelas">Intervalo Parcela</legend>
<input type="text" id="intervalorparcelas" name="intervalorparcelas" class="span4" value="0"/>
</div>
<div class="span6">
<label  for="tipointervalo">Tipo Intervalo</legend>
<select name="tipointervalo" id="tipointervalo">
<option value="Diario">Diario</option>
<option value="Mensal">Mensal</option>
<option value="Anual">Anual</option>
</select>
</div>
</div>


 
 </div>
  <div class="modal-footer">
<input type="submit" name="submit" id="submiteditnote" value="Salvar" class="btn btn-large btn-primary">
</div>
</form>
 </div>


 
 
<div class="modal hide fade" id="DeletaModal">
 <form id="cancelalancamento" name="cancelalancamento" method="post" action="">
 <div class="modal-header">
   <button class="close" data-dismiss="modal">×</button>
   <h3>Confirmar Cancelamento:</h3>
   </div>
 <div class="modal-body">
 
 <div class="alert alert-error"><strong>Para excluir o perfil de pagamento digite as palavras na caixa abaixo:</strong></div>
 
 <input type="hidden" name="tiporegistro" id="tiporegistro_deleta" value="delete">
  <input type="hidden" name="id_registro" id="iddeleta" value="">
 	<div id="ModelPre"><?php 
 $captcha = new Zend_Service_ReCaptcha('6Ldk6-ISAAAAALqcpxh2182Y0Yd8ZqHr2p_QIGoO','6Ldk6-ISAAAAAHpOarrRAqW6S9uvJEdERs2MgP6h');
 echo $captcha->getHTML() ?></div>
 

 </div>
  <div class="modal-footer">
<input type="submit" name="submit" id="submiteditnote" value="CONFIRMAR" class="btn btn-large btn-primary">
</div>
</form>
 </div>

 
  <div class="modal hide fade" id="editaModal">
 <form id="cancelalancamento" name="cancelalancamento" method="post" action="">
 <div class="modal-header">
   <button class="close" data-dismiss="modal">×</button>
   <h3>Editar Perfil</h3>
   </div>
 <div class="modal-body">
 
 <input type="hidden" id="id_registro" name="id_registro"  value=""/>
 <input type="hidden" id="tiporegistro" name="tiporegistro"  value="update"/>
<div class="row-fluid formSep">
<div class="span6">
<label  for="nomeperfil">Nome do Perfil</legend>
<input type="text" name="nomeperfil" id="nomeperfil" class="span12" value="" >
</div>
<div class="span6">
<label  for="tipoperfil">Tipo de Perfil</legend>
<select name="tipoperfil" id="tipoperfil_1">
<option value="0" >Primeira a Vista</option>
<option value="1" >Primeira Parcelado</option>
</select>
</div>
</div>
<div class="row-fluid">
<div class="span3">
<label  for="quantidadeparcelas">Qtd de Parcelas</legend>
 <input type="text" id="quantidadeparcelas_1" name="quantidadeparcelas" class="span4" value=""/>
</div>
<div class="span3">
<label  for="intervalorparcelas">Intervalo Parcela</legend>
<input type="text" id="intervalorparcelas_1" name="intervalorparcelas" class="span4" value=""/>
</div>
<div class="span6">
<label  for="tipointervalo">Tipo Intervalo</legend>
<select name="tipointervalo" id="tipointervalo_1">
<option value="Diario">Diario</option>
<option value="Mensal">Mensal</option>
<option value="Anual" >Anual</option>
</select>
</div>
</div>
 
 </div>
  <div class="modal-footer">
<input type="submit" name="submit" id="submiteditnote" value="CONFIRMAR" class="btn btn-large btn-primary">
</div>
</form>
 </div>
 

<script>
$().ready(function(){

	$('#listaclientes').dataTable({
		"oLanguage": {
			"sUrl": "/js/datatable_ptbr.txt"
		},
		"sPaginationType": "bootstrap"
                     	
                    
    });
    

	$("#tipointervalo").chosen();
	$("#tipoperfil").chosen();

	$("#quantidadeparcelas").spinner();
	$("#intervalorparcelas").spinner();

	$("#tipointervalo_1").chosen();
	$("#tipoperfil_1").chosen();

	$("#quantidadeparcelas_1").spinner();
	$("#intervalorparcelas_1").spinner();
	

	 $(".newdepto").click(function(){

		    $("#id_registro").val('0');
		    $("#tiporegistro").val('novo');
	       	$("submiteditnote").val('Salvar');
		    $("#NovoPerfil").modal('show');    
			
	    });


	 $(".removereg").click(function(){
			id= $(this).attr('idreg');
					
			$("#iddeleta").val(id);
			 showRecaptcha('ModelPre');
			$("#DeletaModal").modal('show');
			
			
		});


	 $("a[data-target=#EditarMod]").live('click',function(ev) {
		    ev.preventDefault();
		    var target = $(this).attr("href");

		    // load the url and show modal on success
		    $("#editaModal .modal-body").load(target, function() { 
		         $("#editaModal").modal("show"); 
		    });
		});	
    

})


function showRecaptcha(element) {
	    Recaptcha.create("6Ldk6-ISAAAAALqcpxh2182Y0Yd8ZqHr2p_QIGoO", element, {
	      theme: "red",
	      callback: Recaptcha.focus_response_field});
	  }


</script>