<div class="row-fluid">
<div class="span12">
<h3 class="heading">Tipos de Documentos
<span class="pull-right"><i style="cursor:pointer" class="splashy-document_a4_new newdepto ttip_b" title="Novo Status"></i></span></h3>
<table id="listaclientes" class="table table-striped table-bordered">
<thead>
<tr>
<th width="5%">ID</th>
<th width="85%">Nome</th>
<th width="5%">Opções</th>
</tr>
</thead>
<tbody>
<?php foreach($this->data as $dado){ ?>
<tr>
<td width="5%"><?php echo $dado->id_registro ?></td>
<td width="85%"><?php echo $dado->nomedocumento ?></td>
<td width="5%"><i class="splashy-hcards_edit editdepto" nomecat="<?php echo $dado->nomedocumento ?>" idreg="<?php echo  $dado->id_registro ?>" style="cursor:pointer" ></i> <i class="splashy-hcards_remove removedepto" nomecat="<?php echo $dado->nomedocumento ?>" idreg="<?php echo $dado->id_registro ?>" style="cursor:pointer" ></i></span></td>
</tr>
<?php }; ?>
</tbody>
</table>
</div>
</div>

<div class="modal hide fade" id="NewDepto">
   <div class="modal-header">
   <button class="close" data-dismiss="modal">×</button>
   <h3>Tipo de Documento:</h3>
   </div>
<form id="newreply" name="newreply" enctype="id_note" class="form-horizontal" method="post" action="">
<input type="hidden" name="action" value="new" id="action">
<input type="hidden" name="id_registro" value="0" id="id_registro">
<div class="modal-body">
<div class="row-fluid formSep">
		<div class="span12">
		<label for="assuntoticket" class="optional">Nome:</label>
		<input type="text" name="nomecategoria" id="nomecategoria" class="span12" >
		</div>
		</div>
		  
</div>
<div class="modal-footer">
<div style="text-align:right">
<a href="javascript:void(0)" class="btn btn-large btn-warning" data-dismiss="modal">Cancelar</a>
<input type="submit" name="submit" id="submiteditnote" value="Salvar" class="btn btn-large btn-primary">
</div>		
</form>
</div>
</div>

<script>
$().ready(function(){

	$('#listaclientes').dataTable({
		"oLanguage": {
			"sUrl": "/js/datatable_ptbr.txt"
		},
		"sPaginationType": "bootstrap"
                     	
                    
    });

    $(".newdepto").click(function(){
    	$("#id_registro").val('0');
    	$("#nomecategoria").val('');
    	$("#action").val('new');
    	$("submiteditnote").val('Salvar');
	    $("#NewDepto").modal('show');    
		
    });

    $(".editdepto").click(function(){
        id = $(this).attr('idreg');
       	nomecat = $(this).attr('nomecat');
		$("#id_registro").val(id);
		$("#nomecategoria").val(nomecat);
		$("#action").val('update');
    	$("submiteditnote").val('Editar');
		$("#NewDepto").modal('show');  	

    });

    $(".removedepto").click(function(){
  	  id = $(this).attr('idreg');
   	nomecat = $(this).attr('nomecat');
	$("#id_registro").val(id);
	$("#nomecategoria").val(nomecat);
	$("#action").val('delete');
	$("submiteditnote").val('Remover');
	$("#NewDepto").modal('show');  	
  	  

    });

    


});


</script>
