<h3 class="heading">Ticket: <span class="pull-right">Protocolo: <?php echo $this->dadosticket->protocolo ?></span></h3>
<div class="tabbable tabs-left">
	 	<ul class="nav nav-tabs">
			<li class="active"><a href="#tab_l1" data-toggle="tab">Básicos <span class="pull-right label label-success"><?php echo $this->interacoes ?></span></a></li>
			<li><a href="#tab_l2" data-toggle="tab">Notas <span class="pull-right label label-success"><?php echo $this->anotacoes ?></span></a></li>
			<li><a href="#tab_l3" data-toggle="tab">Documentos</a></li>
			<li><a href="#tab_l4" data-toggle="tab">Opções</a></li>
			<li><a href="#tab_l5" data-toggle="tab">Histórico</a></li>
		</ul>
	<div class="tab-content">
		<div class="tab-pane active" id="tab_l1">
		
		<div class="well">
		<p class="f_legend"><?php echo $this->dadosticket->nomesolicitante ?>  <span class="pull-right"><small><?php echo Functions_Datas::MyDateTime($this->dadosticket->dateopen,true) ?> </small></span> 
		<span class="pull-right label label-info ttip_t" title="Here is a sample info tooltip"> <?php echo Crm_Model_TicketsTipos::getNomeTipo($this->dadosticket->tipoticket)?> </span>
		</p>
		<p class="formSep"><strong>Assunto:</strong> <?= $this->dadosticket->assuntoticket ?></p>
		<p> <?php echo nl2br($this->dadosticket->dadosticket)?>
		</div>
		<p class="pull-right"><i class="splashy-mail_light_left openreply" style="cursor:pointer" title="Responder" alt="Responder"></i> </p>
		<div class="formSep"></div>
		
		
		<div id="replyticket">
		
		<p class="f_legend">Responder Ticket:</p>
		<form id="newreply" name="newreply" enctype="multipart/form-data" class="form-horizontal" method="post" action="/crm/tickets/reply">
		<input type="hidden" name="id_ticket" value="<?php echo $this->dadosticket->id_registro ?>" id="id_ticket">
		
		<div class="row-fluid formSep">
		<div class="span12">
		<label for="assuntoticket" class="optional">Assunto Resposta</label>
		<input type="text" name="assuntoticket" id="assuntoticket" class="span12" >
		</div>
		</div>
				
		<div class="row-fluid formSep">
		<div class="span12">
		<label for="dadosticket" class="optional">Informações Resposta:</label>
		<textarea name="dadosticket" id="dadosticket" class="span12" rows="8"></textarea>
		</div>
		</div>
		
		<fieldset>
		<legend>Opções da Resposta </legend>
		<div class="row-fluid formSep">
		<div class="span2">
		<label><input type="checkbox" name="sendemail" value="1" class="uni_style" checked="checked"> Enviar Email</label>
		</div>
		<div class="span2">
		<label><input type="checkbox" name="sendsms" value="1" class="uni_style"> Enviar SMS</label>
		</div>
		<div class="span2">
		<label><input type="checkbox" name="acompanhar" value="1" class="uni_style" checked="checked"> Acompanhar</label>
		</div>
		<div class="span2">
		<label><input type="checkbox" name="alertagerente" value="1" class="uni_style"> Alerta Gerência</label>
		</div>
		<div class="span2">
		<label><input type="checkbox" name="closeafter" value="1" class="uni_style"> Encerrar após envio</label>
		</div>
		</div>
		</fieldset>
		
		<fieldset id="fieldset-botoes"><div style="text-align:right">
		<input type="reset" name="cancelar" id="cancelar" value="Cancelar" class="btn btn-large btn-warning">
		<input type="submit" name="submit" id="submit" value="Salvar" class="btn btn-large btn-primary"></div>
		</fieldset>
		
		</form>
		</div>
	
		<p class="f_legend">Interações do Ticket:</p>
		<?php foreach($this->dadosreplys as $reply){?>
		<div class="well">
		<p class="f_legend"><?php if($reply->staffreply <> 0){ echo "<i class=\"splashy-contact_blue\"></i>"; }; ?> <?php echo $reply->nomereply ?>  <span class="pull-right"><small><?php echo Functions_Datas::MyDateTime($reply->replydate,true) ?> </small></span>
		<p class="formSep"><strong>Assunto:</strong> <?= $reply->assuntoreply ?></p>
		<p> <?php echo nl2br($reply->textreply )?>
		<p class="pull-right"><?php if($reply->staffreply == Zend_Auth::getInstance()->getStorage()->read()->id_registro){ 
			echo "<a data-toggle=\"modal\" data-backdrop=\"static\" href=\"#EditReply\" onclick=\"getreplyedit({$reply->id_registro})\"><i class=\"splashy-tag_edit\"></i></a><i style=\"cursor:pointer\" class=\"splashy-tag_remove\" onclick=\"removereply({$reply->id_registro})\"></i>"; }; ?></p>
		</div>
		<?php };?>
		
		</div>
		<div class="tab-pane " id="tab_l2">
		
		<div id="noteform">
		<p class="f_legend">Notas Ticket:</p>
		<form id="newreply" name="newreply" enctype="multipart/form-data" class="form-horizontal" method="post" action="/crm/tickets/save-note">
		<input type="hidden" name="id_ticket" value="<?php echo $this->dadosticket->id_registro ?>" id="id_ticket">
		
		<div class="row-fluid formSep">
		<div class="span12">
		<label for="assuntoticket" class="optional">Assunto Nota</label>
		<input type="text" name="assuntoticket" id="assuntoticket" class="span12" >
		</div>
		</div>
				
		<div class="row-fluid formSep">
		<div class="span12">
		<label for="dadosticket" class="optional">Informações Nota:</label>
		<textarea name="dadosticket" id="dadosticket" class="span12" rows="8"></textarea>
		</div>
		</div>
		
		<fieldset>
		<legend>Opções da Nota </legend>
		<div class="row-fluid formSep">
		<div class="span4">
		<label><input type="checkbox" name="privatenote" value="1" class="uni_style"> Tornar Privada (Só você poderá ver)</label>
		</div>
		
		</div>
		</fieldset>
		
		<fieldset id="fieldset-botoes"><div style="text-align:right">
		<input type="reset" name="limpar" id="limparnotas" value="Cancelar" class="btn btn-large btn-warning">
		<input type="submit" name="submit" id="submit" value="Salvar" class="btn btn-large btn-primary"></div>
		</fieldset>
		</form>
		</div>
		
		<p class="f_legend">Notas Privadas: <span class="pull-right"><i class="splashy-document_letter_new newnote" alt="Nova nota" title="Nova nota"></i></span></p>
		<?php foreach($this->dadosprivatenotes as $reply){	?>
		<div class="well">
		<p class="f_legend"><?php if($reply->id_user <> 0){ echo "<i class=\"splashy-contact_blue\"></i>"; }; ?> <?php echo System_Model_Users::whoIs($reply->id_user) ?>  <span class="pull-right"><small><?php echo Functions_Datas::MyDateTime($reply->datanote,true) ?> </small></span>
		<p class="formSep"><strong>Assunto:</strong> <?= $reply->assuntonote ?></p>
		<p> <?php echo nl2br($reply->textonote )?>
		<p class="pull-right"><?php if($reply->id_user == Zend_Auth::getInstance()->getStorage()->read()->id_registro){ 
			echo "<a data-toggle=\"modal\" data-backdrop=\"static\" href=\"#EditNote\" onclick=\"getnoteedit({$reply->id_registro})\"><i class=\"splashy-tag_edit\"></i></a><i style=\"cursor:pointer\" class=\"splashy-tag_remove\" onclick=\"removenote({$reply->id_registro})\"></i>"; }; ?></p>
		</div>
		<?php } ?>
		
		<p class="f_legend">Notas Públicas: <span class="pull-right"><i class="splashy-document_letter_new newnote" alt="Nova nota" title="Nova nota"></i></span></p>
		<?php foreach($this->dadosnotes as $reply){	?>
		<div class="well">
		<p class="f_legend"><?php if($reply->id_user <> 0){ echo "<i class=\"splashy-contact_blue\"></i>"; }; ?> <?php echo System_Model_Users::whoIs($reply->id_user) ?>  <span class="pull-right"><small><?php echo Functions_Datas::MyDateTime($reply->datanote,true) ?> </small></span>
		<p class="formSep"><strong>Assunto:</strong> <?= $reply->assuntonote ?></p>
		<p> <?php echo nl2br($reply->textonote )?>
		<p class="pull-right"><?php if($reply->id_user == Zend_Auth::getInstance()->getStorage()->read()->id_registro){ 
			echo "<a data-toggle=\"modal\" data-backdrop=\"static\" href=\"#EditNote\" onclick=\"getnoteedit({$reply->id_registro})\"><i class=\"splashy-tag_edit\"></i></a><i style=\"cursor:pointer\" class=\"splashy-tag_remove\" onclick=\"removenote({$reply->id_registro})\"></i>"; }; ?></p>
		</div>
		<?php } ?>
		
		
		
		
		
		
		</div>
		<div class="tab-pane " id="tab_l3">
		<form id="clientesfiles" name="clientesfiles" enctype="multipart/form-data" class="form-horizontal" method="post" action="/crm/tickets/save-file">
		<input type="hidden" name="tipofile" value="tickets" id="tipofile">
		<input type="hidden" name="idreg" value="<?php echo $this->dadosticket['id_registro'] ?>" id="idreg">
		
		<fieldset id="fieldset-clientesfiles" class="form-horizontal">
		<div class="row-fluid formSep">
		
		<div class="span3">
		<label for="nomeamigavel" class="optional">Nome Amigavel:</label>
		<input type="text" name="nomeamigavel" id="nomeamigavel">
		</div>
		
		<div class="span3">
		<label for="arquivo" class="tags">Tags:</label>
		<input type="text" name="tags" id="tags">
		</div>
		
		<div class="span3">
		<label for="arquivo" class="optional">Selecione o Documento:</label>
		<input type="hidden" name="MAX_FILE_SIZE" value="104857600" id="MAX_FILE_SIZE">
		<input type="file" name="arquivo" id="arquivo"  class="uni_style">
		</div>
		
		</div>
		</fieldset>
		
		<fieldset id="fieldset-grupo20">
		<div class="row-fluid formSep">
		<div class="span11">
		<label for="obsfile" class="optional">Observações do Arquivo:</label>
		<textarea name="obsfile" id="obsfile" rows="5" style="width:100%" cols="80"></textarea>
		</div>
		</div>
		</fieldset>
		
		<fieldset id="fieldset-botoes">
		<div style="text-align:right">
		<input type="reset" name="limparoutros" id="limparoutros" value="Limpar" class="btn btn-large btn-warning">
		<input type="submit" name="submitoutros" id="submitoutros" value="Salvar" class="btn btn-large btn-primary">
		</div>
		</fieldset>
		</form>
		
		
	
		 <div class="row-fluid">
                        <div class="span12">
                            <h3 class="heading">Arquivos do Ticket:</h3>
                            
                          	<table id="table-arquivos"  class="table table-striped table-bordered table-condensed">
		<thead>
		<tr>
			<th>Tipo:</th>
			<th>Nome</th>
			<th>Tags</th>
			<th>Opções</th>
			</tr>
		</thead>
		<tbody>
		<?php 
		if($this->arquivos){
		foreach($this->arquivos as $arquivo){?>
		<tr>
		<td><?php echo $arquivo['filetype'] ?></td>
		<td><?php echo $arquivo['nomeamigavel'] ?></td>
		<td><?php echo $arquivo['tags'] ?></td>
		<td><span class="pull-center"><a href="/system/files/get-file/id/<?php echo $arquivo['id_registro'] ?>" target="_blank" alt="Download do Arquivo" title="Download do Arquivo"><i class="splashy-folder_modernist_down"></i></a>  
		<a href="/system/files/render/id/<?php echo $arquivo['id_registro'] ?>" target="_blank" alt="Visualizar Arquivo" title="Visualizar  Arquivo"><i class="splashy-document_a4_marked"></i></a> 
		<i class="splashy-folder_modernist_remove removearquivo" idarquivo="<?php echo $arquivo['id_registro'] ?>" style="cursor:pointer"></i>
		</span></td>
		</tr>
		
		<?php  
		}
		}
		?>
		</tbody>
		
		</table>
		</div>
		</div>
		</div>
		<!-- OPCOES -->
		<div class="tab-pane " id="tab_l4">
		<form id="newticket" name="newticket" enctype="multipart/form-data" class="form-horizontal" method="post" action="/crm/tickets/edit-ticket">
		<input type="hidden" name="id_ticket" value="<?php echo $this->dadosticket->id_registro ?>" id="id_ticket">
		
			
		<fieldset>
		<div class="row-fluid formSep">
		<div class="span4">
		<label for="statusticket" class="optional">Status Ticket</label>
		<select name="statusticket" id="statusticket">
		<?php
		$empresas = Crm_Model_TicketsStatus::renderCombo();
		foreach($empresas as $key=>$value){
			if($key == $this->dadosticket->statusticket){
				$sel = "selected";
			}else{
				$sel = '';
			}
		echo "<option value=\"$key\" $sel> $value </otion>";
		}
		?>
		</select>
		
		</div>
		<div class="span8">
		<label for="assuntoticket" class="optional">Assunto Ticket</label>
		<input type="text" name="assuntoticket" id="assuntoticket" value="<?php echo $this->dadosticket->assuntoticket ?>" class="span12" >
		</div>
		
		</div>
		</fieldset>
			
		<fieldset id="fieldset-clientesfiles" class="form-horizontal">
		<div class="row-fluid formSep">
		
		<div class="span3">
		<label for="empresa" class="optional">Empresa</label>
		<select name="empresa" id="empresa">
		<?php
		$empresas = System_Model_Empresas::renderCombo();
		foreach($empresas as $key=>$value){
			if($key == $this->dadosticket->id_empresa){
				$sel = "selected";
			}else{
				$sel = '';
			}
		echo "<option value=\"$key\" $sel> $value </otion>";
		}
		?>
		</select>
			</div>
		
		<div class="span3">
		<label for="departamento" class="optional">Departamento</label>
		<select name="departamento" class="span10" id="departamento">
		<?php
		$deptos = Crm_Model_TicketsDeptos::renderCombo();
		foreach($deptos as $key=>$value){if($key == $this->dadosticket->departamento){
	$sel = "selected";
}else{
	$sel = '';
}
echo "<option value=\"$key\" $sel> $value </otion>";
		}
		?>
		</select>
		</div>
		
		<div class="span3">
		<label for="tipoticket" class="optional">Tipo de Tickets</label>
		<select name="tipoticket" class="span10" id="tipoticket">
		<?php
		$deptos = Crm_Model_TicketsTipos::renderCombo();
		foreach($deptos as $key=>$value){
if($key == $this->dadosticket->tipoticket){
	$sel = "selected";
}else{
	$sel = '';
}
echo "<option value=\"$key\" $sel> $value </otion>";
		}
		?>
		</select>
		</div>
		
		<div class="span3">
		<label for="prioridadeticket" class="optional">Prioridade</label>
		<select name="prioridadeticket"  class="span10" id="prioridadeticket">
		<?php
		$deptos = Crm_Model_TicketsPrioridades::renderCombo();
		foreach($deptos as $key=>$value){
if($key == $this->dadosticket->prioridadeticket){
	$sel = "selected";
}else{
	$sel = '';
}
echo "<option value=\"$key\" $sel> $value </otion>";
		}
		?>
		</select>
		</div>
		
		</div>
		</fieldset>
		
			<fieldset>
		<div class="row-fluid formSep">
		<div class="span8">
		<label for="tags" class="tags">Tags</label>
		<input type="text" class="span12" name="tags" id="tags" value="<?php echo $this->dadosticket->tags ?>"  placeholder="Digite palavras separadas por virgula para auxiliar a busca deste ticket" >
		</div>
		<div class="span4">
		<label for="atribuidoa" class="optional">Atribuir a:</label>
		<select name="atribuidoa" class="span12" id="atribuidoa">
		<?php
		$deptos = System_Model_Users::renderCombo();
		foreach($deptos as $key=>$value){if($key == $this->dadosticket->atribuidoa){
	$sel = "selected";
}else{
	$sel = '';
}
echo "<option value=\"$key\" $sel> $value </otion>";
		}
		?>
		</select>
		</div>
		</div>
		</fieldset>
		<fieldset id="fieldset-botoes"><div style="text-align:right">

<input type="reset" name="limpar" id="limpar" value="Limpar" class="btn btn-large btn-warning">

<input type="submit" name="submit" id="submit" value="Salvar" class="btn btn-large btn-primary"></div></fieldset>
		
		</form>
		
		
		
		
		</div>
		<div class="tab-pane " id="tab_l5">
		<h3 class="heading">Histórico do Solicitante </h3>
<table id="listaclientes" class="table table-striped table-bordered">
<thead>
<tr>
<th width="5%"><i style="cursor:pointer" class="splashy-star_empty" ></i></th>
<th width="5%">ID</th>
<th width="10%">Protocolo</th>
<th width="10%">Departamento</th>
<th width="30%">Solicitante</th>
<th width="10%">Aberto a </th>
<th width="10%">Ult. Resp</th>
<th width="10%">Status</th>
<th width="10%">Opções</th>
</tr>
</thead>
<tbody>
<tr>
<td class="dataTables_empty" colspan="6">Não existem dados nessa consulta!</td>
</tr>
</tbody>
</table>

</div>
		</div>
		</div>
		
	
<div class="modal hide fade" id="EditReply">
<div class="modal-body">  

<form id="newreply" name="newreply" enctype="multipart/form-data" class="form-horizontal" method="post" action="/crm/tickets/editreply">
		<input type="hidden" name="id_reply" value="" id="id_reply">
		
		<div class="row-fluid formSep">
		<div class="span12">
		<label for="assuntoticket" class="optional">Assunto Resposta</label>
		<input type="text" name="assuntoticket" id="assuntoticketeditreply" class="span12" >
		</div>
		</div>
				
		<div class="row-fluid formSep">
		<div class="span12">
		<label for="dadosticket" class="optional">Informações Resposta:</label>
		<textarea name="dadosticket" id="dadosticketeditreply" class="span12" rows="8"></textarea>
		</div>

		</div>
		<div class="modal-footer">  
		<div style="text-align:right">
		<a href="javascript:void(0)" class="btn btn-large btn-warning" data-dismiss="modal">Cancelar</a>
		<input type="submit" name="submit" id="submiteditreply" value="Salvar" class="btn btn-large btn-primary">
		</div>		
		</div>
		
</form>
</div>
</div>


<div class="modal hide fade" id="EditNote">
<div class="modal-body">  

<form id="newreply" name="newreply" enctype="id_note" class="form-horizontal" method="post" action="/crm/tickets/editnote">
		<input type="hidden" name="id_note" value="" id="id_note">
		
		<div class="row-fluid formSep">
		<div class="span12">
		<label for="assuntoticket" class="optional">Assunto Resposta</label>
		<input type="text" name="assuntoticket" id="assuntoticketeditnote" class="span12" >
		</div>
		</div>
				
		<div class="row-fluid formSep">
		<div class="span12">
		<label for="dadosticket" class="optional">Informações Resposta:</label>
		<textarea name="dadosticket" id="dadosticketeditnote" class="span12" rows="8"></textarea>
		</div>

		</div>
		<div class="modal-footer">  
		<div style="text-align:right">
		<a href="javascript:void(0)" class="btn btn-large btn-warning" data-dismiss="modal">Cancelar</a>
		<input type="submit" name="submit" id="submiteditnote" value="Salvar" class="btn btn-large btn-primary">
		</div>		
		</div>
		
</form>
</div>
</div>
	

<script>
$().ready(function(){

	$("#atribuidoa").chosen();
	$("#prioridadeticket").chosen();
	$("#tipoticket").chosen();
	$("#departamento").chosen();
	$("#empresa").chosen();
	$("#statusticket").chosen();
	 $(".uni_style").uniform();

		$("#replyticket").hide();
		$("#noteform").hide();

		$(".openreply").click(function(){
			$("#replyticket").toggle();
		});

		$(".newnote").click(function(){
			$("#noteform").toggle();
		});

		$("#limparnotas").click(function(){
			$("#noteform").toggle();
		});

		$("#cancelar").click(function(){
			$("#replyticket").toggle();
		});

		$('#table-arquivos').dataTable({
		       "sPaginationType": "bootstrap_alt",
		       "oLanguage": {
					"sUrl": "/js/datatable_ptbr.txt"
				}
		    });

	

			$('#listaclientes').dataTable({
				"oLanguage": {
					"sUrl": "/js/datatable_ptbr.txt"
				},
				"sPaginationType": "bootstrap",
		        "bProcessing": true,
				"bServerSide": true,
				 "sAjaxSource": "/system/datatables/tickets-historico/thisticket/<?php echo $this->dadosticket->id_registro ?>"
		               	
		                    
		    });


		
			    

	
});

function getreplyedit(id){
	 $.ajax({ 
			type: "GET", 
			url: "/crm/tickets/getreplydata", 
			data: "id="+ id,
			beforeSend: function() {
								
	 		}, 
			success: function(txt) {
			
				var retorno = jQuery.parseJSON(txt);	
				$("#id_reply").val(retorno.id_registro);
				$("#assuntoticketeditreply").val(retorno.assuntoreply);
				$("#dadosticketeditreply").val(retorno.textreply);
						

														
			}, 
			error: function(txt) { 
				$.sticky("UM ERRO DE SISTEMA OCORREU.", { type: 'st-error' });
			} 
		}); 
}

function removereply(id){
	if(confirm("Deseja Realmente remover esta resposta?")){
		document.location.href="/crm/tickets/remove-reply/id/"+id;
	}
}


function getnoteedit(id){
	 $.ajax({ 
			type: "GET", 
			url: "/crm/tickets/getnotedata", 
			data: "id="+ id,
			beforeSend: function() {
								
	 		}, 
			success: function(txt) {
			
				var retorno = jQuery.parseJSON(txt);	
				$("#id_note").val(retorno.id_registro);
				$("#assuntoticketeditnote").val(retorno.assuntonote);
				$("#dadosticketeditnote").val(retorno.textonote);
						

														
			}, 
			error: function(txt) { 
				$.sticky("UM ERRO DE SISTEMA OCORREU.", { type: 'st-error' });
			} 
		}); 
}

function removenote(id){
	if(confirm("Deseja Realmente remover esta anotação?")){
		document.location.href="/crm/tickets/remove-note/id/"+id;
	}
}

function agrupartickets(id,id2,protocolo){

	if(confirm("Deseja Realmente Agrupar estes tickets?\n\nO Ticket aberto assumira o protocolo do ticket: "+protocolo)){
		document.location.href="/crm/tickets/agupar-ticket/id/"+id2+"/idnovo/"+id;
	}
	
}

</script>