<script src="http://code.highcharts.com/highcharts.js"></script>
<script src="http://code.highcharts.com/modules/exporting.js"></script>
<div class="row-fluid">
					 <div class="span12">
							<div class="heading clearfix">
								<h3 class="pull-left">Estatísticas dos tickets <small>30 Dias</small></h3>
								</div>
							<div id="container" style="width: 100%; height: 400px; margin: 0 auto"></div>
							</div>
							
</div>	


<div class="row-fluid">
					 <div class="span4">
							<div class="heading clearfix">
								<h3 class="pull-left">Tickets por canais <small>30 Dias</small></h3><br><br>
									<?php foreach($this->ticketsPorCanal as $canal){
										$total = number_format(($canal['total']/$this->totalTickets) * 100,0);		
																
									?>
									<?php echo Crm_Model_TicketsTipos::getNomeTipo($canal['tipoticket'])." $total%" ?> 
									<div class="progress progress-info progress-striped">
										<div class="bar" style="width: <?php echo $total ?>%"></div>
									</div>
								
									<?php } ?>
								</div>
						
							</div>
							
							<div class="span4">
							<div class="heading clearfix">
								<h3 class="pull-left">Dados de Comparação <small>Global</small></h3>
								</div>
							sdfsdfsdf
							</div>
							
								<div class="span4">
							<div class="heading clearfix">
								<h3 class="pull-left">Tempo da Primeira Resposta <small>Média</small></h3>
								</div>
							sdfsdfsdf
							</div>
														
							
</div>	


<div class="row-fluid">
					 <div class="span4">
							<div class="heading clearfix">
								<h3 class="pull-left">Principais Usuarios <small>Global</small></h3>
								</div>
						
									<?php foreach($this->TicketsPorStaff as $canal){
										$total = number_format(($canal['total']/$this->totalTickets) * 100,0);		
																
									?>
									<?php echo System_Model_Users::whoIs($canal['staffopen'])." $total%" ?> 
									<div class="progress progress-info progress-striped">
										<div class="bar" style="width: <?php echo $total ?>%"></div>
									</div>
								
									<?php } ?>
							</div>
							
							<div class="span4">
							<div class="heading clearfix">
								<h3 class="pull-left">Pricipais Departamentos <small>Global</small></h3>
								</div>
								<?php foreach($this->TicketsPorDepto as $canal){
										$total = number_format(($canal['total']/$this->totalTickets) * 100,0);		
																
									?>
									<?php echo Crm_Model_TicketsDeptos::getNomeDepto($canal['departamento'])." $total%" ?> 
									<div class="progress progress-info progress-striped">
										<div class="bar" style="width: <?php echo $total ?>%"></div>
									</div>
								
									<?php } ?>
							</div>
							
								<div class="span4">
							<div class="heading clearfix">
								<h3 class="pull-left">Principais clientes <small>Média</small></h3>
								</div>
							sdfsdfsdf
							</div>
														
							
</div>		

<?php print_r($this->tickesLastMonth)?>
<script>
$(function () {
    var chart;
    $(document).ready(function() {
        chart = new Highcharts.Chart({
            chart: {
                renderTo: 'container',
                type: 'line',
                marginRight: 130,
                marginBottom: 25
            },
            title: {
                text: '',
                x: -20 //center
            },
            subtitle: {
                text: '',
                x: -20
            },
            xAxis: {
                categories: ['1', '2', '3', '4', '5', '6',
                    '7', '8', '9', '10', '11', '12','13','14','15','16','17','18','19','20','21','22','23','24','25','26','27','28','29','30']
            },
            yAxis: {
                title: {
                    text: 'Quantidade De Tickets'
                },
                plotLines: [{
                    value: 0,
                    width: 1,
                    color: '#808080'
                }]
            },
            tooltip: {
                formatter: function() {
                        return '<b>'+ this.series.name +'</b><br/>'+
                        this.x +': '+ this.y +'';
                }
            },
            legend: {
                layout: 'vertical',
                align: 'right',
                verticalAlign: 'top',
                x: -10,
                y: 100,
                borderWidth: 0
            },
            series: [{
                name: 'Abertos',
                data: [3.9, 4.2, 5.7, 8.5, 11.9, 15.2, 17.0, 16.6, 14.2, 10.3, 6.6, 4.8]
            }]
        });
    });
    
});
									</script>