<div class="row-fluid">
<div class="span12">
<h3 class="heading">Cadastro de ISS (Imposto sobre Serviço)
<span class="pull-right"><i style="cursor:pointer" class="splashy-document_a4_new newdepto ttip_b" title="Novo ISS"></i></span></h3>
<table id="listaclientes" class="table table-striped table-bordered">
<thead>
<tr>
<th width="5%"></th>
<th width="5%">ID</th>
<th width="10%">Codigo</th>
<th width="51%">Descrição</th>
<th width="8%">Valor ISS</th>
<th width="8%">Valor PIS</th>
<th width="8%">Valor COFINS</th>
<th width="5%">Opções</th>
</tr>
</thead>
<tbody>
<?php foreach($this->dados as $dado){ ?>
<tr>
<td width="5%"><i style="cursor:pointer" class="<?php if($dado->isdefault == 1){  echo "splashy-star_full"; }else{  echo "splashy-star_empty"; }?>"></i></td>
<td width="5%"><?php echo $dado->id_registro ?></td>
<td width="10%"><?php echo $dado->codigoiss ?></td>
<td width="51%"><?php echo $dado->descricaoiss ?></td>
<td width="8%"><?php echo number_format($dado->valoriss,2,',','') ?></td>
<td width="8%"><?php echo number_format($dado->valorpis,2,',','') ?></td>
<td width="8%"><?php echo number_format($dado->valorcofins,2,',','') ?></td>
<td width="5%"><i class="splashy-hcards_edit editdepto"  idreg="<?php echo  $dado->id_registro ?>" style="cursor:pointer" ></i> <i class="splashy-hcards_remove removedepto" idreg="<?php echo $dado->id_registro ?>" style="cursor:pointer" ></i></span></td>
</tr>
<?php }; ?>
</tbody>
</table>
</div>
</div>

<div class="modal hide fade" id="NewDepto">
   <div class="modal-header">
   <button class="close" data-dismiss="modal">×</button>
   <h3>ISS:</h3>
   </div>
<form id="newreply" name="newreply" enctype="id_note" class="form-horizontal" method="post" action="/system/servicos/novo-iss">
<input type="hidden" name="id_registro" value="0" id="id_registro">
<div class="modal-body">
<div class="row-fluid formSep">
<div class="span4">
<label for="assuntoticket" class="optional">Codigo ISS:</label>
<input type="text" name="codigoiss" id="codigoiss" class="span12" >
</div>
<div class="span8">
<label for="assuntoticket" class="optional">Descrição ISS:</label>
<input type="text" name="descricaoiss" id="descricaoiss" class="span12" >
</div>
</div>

<div class="row-fluid formSep">
<div class="span4">
		<label for="assuntoticket" class="optional">Valor ISS (%):</label>
		<input type="text" name="valoriss" id="valoriss" class="span12" >
		</div>
		<div class="span4">
		<label for="assuntoticket" class="optional">Valor PIS (%):</label>
		<input type="text" name="valorpis" id="valorpis" class="span12" >
		</div>
		<div class="span4">
		<label for="assuntoticket" class="optional">Valor Cofins (%):</label>
		<input type="text" name="valorcofins" id="valorcofins" class="span12" >
		</div>
</div>
		  
</div>
<div class="modal-footer">
<div style="text-align:right">
<a href="javascript:void(0)" class="btn btn-large btn-warning" data-dismiss="modal">Cancelar</a>
<input type="submit" name="submit" id="submiteditnote" value="Salvar" class="btn btn-large btn-primary">
</div>		
</form>
</div>
</div>

<script>
$().ready(function(){

	$('#listaclientes').dataTable({
		"oLanguage": {
			"sUrl": "/js/datatable_ptbr.txt"
		},
		"sPaginationType": "bootstrap"
                     	
                    
    });

    $(".newdepto").click(function(){
	    $("#NewDepto").modal('show');    
		
    });

    $(".editdepto").click(function(){
        id = $(this).attr('idreg');

   	 $.ajax({ 
			type: "GET", 
			url: "/system/servicos/getissdata/id/"+ id , 
			data: "undo="+ id,
			beforeSend: function() {
								
	 		}, 
			success: function(txt) {
			
				var retorno = jQuery.parseJSON(txt);	
				$("#id_registro").val(retorno.id_registro);
				$("#codigoiss").val(retorno.codigoiss);
				$("#descricaoiss").val(retorno.descricaoiss);
				$("#valoriss").val(retorno.valoriss);
				$("#valorpis").val(retorno.valorpis);
				$("#valorcofins").val(retorno.valorcofins);
				$("#NewDepto").modal('show');  	

														
			}, 
			error: function(txt) { 
				$.sticky("UM ERRO DE SISTEMA OCORREU.", { type: 'st-error' });
			} 
		}); 

    });

    $(".removedepto").click(function(){
  	  	id = $(this).attr('idreg');
  	  	if(confirm("Deseja Realmente excluir este ISS?")){
    	 document.location.href="/system/servicos/removeiss/id/"+id;
  	  	}
  	  

    });

    


});


</script>
