 <?php if($this->prospect->atribuidoa == 0 || $this->prospect->atribuidoa ==  '' ){ ?>
 <div class="row-fluid">
<div class="span12">
<div class="alert alert-block alert-error fade in">
<h4 class="alert-heading">Prospect Não Atribuido</h4>
								<p>Este Prospect Não esta atribuido a nenhum usuário</p>
								<p> Deseja Atribuir este prospect a você?</p>
							<p><a href="/crm/prospects/atribuir/id/<?php echo $this->prospect->id_registro ?>" class="btn btn-inverse"> <i class="splashy-check"></i> Atribuir ao meu Usuário </a></p>	
							</div>
						</div>
						</div>

<?php }else{
	$cadastrobloqueado = false;
} ?>

<h3 class="heading">Prospect <?php echo $this->prospect->nomeempresa ?>: <span class="pull-right">Protocolo: <?php echo $this->prospect->protocolo ?></span></h3>
<div class="tabbable tabs-left">
	 	<ul class="nav nav-tabs">
			<li class="active"><a href="#tab_l1" data-toggle="tab">Básicos <span class="pull-right label label-success"><?php echo $this->interacoes ?></span></a></li>
			<li><a href="#tab_l6" data-toggle="tab">Check-list <span class="pull-right label label-success"><?php echo Crm_Model_Prospects_ChecklistItens::countetapas($this->prospect->id_registro) ?></span></a></li>
			<li><a href="#tab_l2" data-toggle="tab">Notas <span class="pull-right label label-success"><?php echo $this->anotacoes ?></span></a></li>
			<li><a href="#tab_l3" data-toggle="tab">Documentos&nbsp;&nbsp;&nbsp;&nbsp;</a></li>
			<li><a href="#tab_l4" data-toggle="tab">Orçamentos</a></li>
			<li><a href="#tab_l5" data-toggle="tab">Estágios</a></li>
		</ul>
	<div class="tab-content">
		<div class="tab-pane active" id="tab_l1">
		<div class="well">
		<p class="f_legend"><?php echo $this->prospect->nomesolicitante ?>  
		<?php if($this->prospect->readtimes > 0){ ?> <span class="pull-right label label-success ttip_t" title="Lido <?php echo $this->prospect->readtimes?> Vez(es):">  <i class="splashy-mail_light_stuffed"></i> </span>    <?php }else{ ?>  <span class="pull-right label label-error ttip_t" title="Não Lido:">  <i class="splashy-mail_light"></i> </span>  <?php };?>
		
		<span class="pull-right label label-info ttip_t" title="Atribuido à:"> <?php echo System_Model_Users::whoIs($this->prospect->atribuidoa)?> </span> 
		
		<span class="pull-right"><small>&nbsp;&nbsp;<?php echo Functions_Datas::MyDateTime($this->prospect->dateopen,true) ?>&nbsp;&nbsp; </small></span> 
		</p>
		<div class="row-fluid formSep">
		<div class="span1">
		<strong>Tipo:</strong><br>
		<?php echo Crm_Model_Prospects_TiposNegocios::getNomeDepto($this->prospect->tiponegocio)?>
		</div>
		<div class="span2">
		<strong>Estágio Atual:</strong>
		<br>
		<span class="label label-warning"><?php echo Crm_Model_Prospects_EstagioProposta::getNomeDepto($this->prospect->estagioproposta)?></span>
		</div>
		<div class="span2">
		<strong>Fonte:</strong>
		<br>
		<?php echo Crm_Model_Prospects_FontesPropostas::getNomeDepto($this->prospect->fonteproposta)?>
		</div>
		<div class="span2">
		<strong>Campanha:</strong>
		<br>
		<?php echo Crm_Model_Marketing_Campanhas::getNomeDepto($this->prospect->campanhaproposta)?>
		</div>
		<div class="span2">
		<strong>Probabilidade:</strong>
		<br> <?php echo number_format($this->prospect->probabilidadeproposta,2,',','') ?> %
		</div>
		<div class="span1">
		<strong>Dt Limite:</strong>
		<br> <?php echo Functions_Datas::MyDateTime($this->prospect->datalimite)?>
		</div>
		
		<div class="span2">
		<strong>Valor:</strong>
			<br> R$ <?php echo number_format($this->prospect->valorproposta,2,',','') ?>
		</div>
		
		</div>
		<div class="row-fluid">
		<div class="span12">
		<?php echo nl2br($this->prospect->descritivoproposta)?>
		</div>
		</div>
		</div>
		<p class="pull-right"><i class="splashy-mail_light_left openreply" style="cursor:pointer" title="Responder" alt="Responder"></i> </p>
		<div class="formSep"></div>
		
			<div id="FormUpdateProspect">
		
		<p class="f_legend">Atualizar Prospect:</p>
		<form id="newreply" name="newreply" enctype="multipart/form-data" class="form-horizontal" method="post" action="/crm/prospects/reply">
		<input type="hidden" name="id_prospect" value="<?php echo $this->prospect->id_registro ?>" id="id_ticket">
		
			<fieldset id="fieldset-clientesfiles" class="form-horizontal">
		<div class="row-fluid formSep">
		
		<div class="span4">
		<label for="estagioproposta" class="optional">Estágio Proposta:</label>
		<select name="estagioproposta" id="estagioproposta"  class="span12" >
		<?php
		$empresas = Crm_Model_Prospects_EstagioProposta::renderCombo();
		foreach($empresas as $key=>$value){
		 	if($key == $this->prospect->estagioproposta){
				 $option = 'selected';
			}else{
				 $option = '';
			}	 

		echo "<option value=\"$key\" $option> $value </otion>";
		}
		?>
		</select>
			</div>
			
		
		<div class="span2">
		<label for="probabilidadeproposta" class="optional">Probabilidade Proposta</label>
		<input type="text" class="span12" name="probabilidadeproposta" id="probabilidadeproposta" placeholder="0.00" value="<?php echo str_replace('.',',',number_format($this->prospect->probabilidadeproposta,2,',','')) ?>" >
		</div>
		
		<div class="span2">
		<label for="datalimite" class="optional">Data Limite</label>
		<input type="text" class="span12" name="datalimite" id="datalimite" placeholder="dd/mm/aaaa" value="<?php echo Functions_Datas::MyDateTime($this->prospect->datalimite)?>" >
		</div>
		
		<div class="span2 input-append">
		<label for="valorproposta" class="optional">Valor</label>
		<input type="text" class="span10" name="valorproposta" id="valorproposta" placeholder="0.00" value="<?php echo number_format($this->prospect->valorproposta,2,',','') ?>" ><span class="add-on"><i class="icon-briefcase"></i>
		</div>
		
	
		
		</div>
		</fieldset>
		
		
		<div class="row-fluid formSep">
		<div class="span12">
		<label for="dadosticket" class="optional">Informações Resposta:</label>
		<textarea name="informacoesresposta" id="informacoesresposta" class="span12" rows="8"></textarea>
		</div>
		</div>
				
		<fieldset id="fieldset-botoes"><div style="text-align:right">
		<input type="reset" name="cancelar" id="cancelar" value="Cancelar" class="btn btn-large btn-warning">
		<input type="submit" name="submit" id="submit" value="Salvar" class="btn btn-large btn-primary"></div>
		</fieldset>
		
		</form>
	
	</div>
	
	<?php foreach($this->dadosreply as $reply){?>
	
		<div class="well">
		<p class="f_legend"><?php if($reply->id_user <> 0){ echo "<i class=\"splashy-contact_blue ttip_t\" title=\"Usuário do Sistema\"></i>"; }; ?> <?php echo $reply->nomeresposta ?>
		<?php if($reply->timesread > 0){ ?> <span class="pull-right label label-success ttip_t" title="Lido <?php echo $reply->timesread?> Vez(es):">  <i class="splashy-mail_light_stuffed"></i> </span>    <?php }else{ ?>  <span class="pull-right label label-alert ttip_t" title="Não Lido:">  <i class="splashy-mail_light"></i> </span>  <?php };?>
		 
		<span class="pull-right label label-info ttip_t" title="Atribuido à:"> <?php echo System_Model_Users::whoIs($this->prospect->atribuidoa)?> </span>
		<span class="pull-right"><small>&nbsp;&nbsp;<?php echo Functions_Datas::MyDateTime($reply->dataresposta,true) ?>&nbsp;&nbsp; </small></span> 
		</p>
		<div class="row-fluid formSep">
		<div class="span2">
		<strong>Estágio Informado:</strong>
		<br>
		<span class="label label-warning"><?php echo Crm_Model_Prospects_EstagioProposta::getNomeDepto($reply->estagioproposta)?></span>
		</div>
		<div class="span2">
		<strong>Probabilidade:</strong>
		<br> <?php echo number_format($reply->probabilidadeproposta,2,',','') ?> %
		</div>
		<div class="span1">
		<strong>Dt Limite:</strong>
		<br> <?php echo Functions_Datas::MyDateTime($reply->datalimite)?>
		</div>
		
		<div class="span2">
		<strong>Valor:</strong>
			<br> R$ <?php echo number_format($reply->valorproposta,2,',','') ?>
		</div>
		
		</div>
		<div class="row-fluid">
		<div class="span12">
		<?php echo nl2br($reply->informacoesresposta)?>
		</div>
		</div>
		</div>
	
	<?php } ?>
	</div>
	

	
		<div class="tab-pane" id="tab_l2">
		<div id="noteform">
		<p class="f_legend">Notas Prospect:</p>
		<form id="newreply" name="newreply" enctype="multipart/form-data" class="form-horizontal" method="post" action="/crm/prospects/save-note">
		<input type="hidden" name="id_prospect" value="<?php echo $this->prospect->id_registro ?>" id="id_prospect">
		
		<div class="row-fluid formSep">
		<div class="span12">
		<label for="assuntoticket" class="optional">Assunto Nota</label>
		<input type="text" name="assuntoticket" id="assuntoticket" class="span12" >
		</div>
		</div>
				
		<div class="row-fluid formSep">
		<div class="span12">
		<label for="dadosticket" class="optional">Informações Nota:</label>
		<textarea name="dadosticket" id="dadosticket" class="span12" rows="8"></textarea>
		</div>
		</div>
		
		<fieldset>
		<legend>Opções da Nota </legend>
		<div class="row-fluid formSep">
		<div class="span4">
		<label><input type="checkbox" name="privatenote" value="1" class="uni_style"> Tornar Privada (Só você poderá ver)</label>
		</div>
		
		</div>
		</fieldset>
		
		<fieldset id="fieldset-botoes"><div style="text-align:right">
		<input type="reset" name="limpar" id="limparnotas" value="Cancelar" class="btn btn-large btn-warning">
		<input type="submit" name="submit" id="submit" value="Salvar" class="btn btn-large btn-primary"></div>
		</fieldset>
		</form>
		</div>
		
		<p class="f_legend">Notas Privadas: <span class="pull-right"><i class="splashy-document_letter_new newnote ttip_t" alt="Nova nota" title="Nova nota"></i></span></p>
		<?php foreach($this->dadosprivatenotes as $reply){	?>
		<div class="well">
		<p class="f_legend"><?php if($reply->id_user <> 0){ echo "<i class=\"splashy-contact_blue\"></i>"; }; ?> <?php echo System_Model_Users::whoIs($reply->id_user) ?>  <span class="pull-right"><small><?php echo Functions_Datas::MyDateTime($reply->datanote,true) ?> </small></span>
		<p class="formSep"><strong>Assunto:</strong> <?= $reply->assuntonote ?></p>
		<p> <?php echo nl2br($reply->textonote )?>
		<p class="pull-right"><?php if($reply->id_user == Zend_Auth::getInstance()->getStorage()->read()->id_registro){ 
			echo "<a data-toggle=\"modal\" data-backdrop=\"static\" href=\"#EditNote\" onclick=\"getnoteedit({$reply->id_registro})\"><i class=\"splashy-tag_edit\"></i></a><i style=\"cursor:pointer\" class=\"splashy-tag_remove\" onclick=\"removenote({$reply->id_registro})\"></i>"; }; ?></p>
		</div>
		<?php } ?>
		
		<p class="f_legend">Notas Públicas: </p>
		<?php foreach($this->dadosnotes as $reply){	?>
		<div class="well">
		<p class="f_legend"><?php if($reply->id_user <> 0){ echo "<i class=\"splashy-contact_blue\"></i>"; }; ?> <?php echo System_Model_Users::whoIs($reply->id_user) ?>  <span class="pull-right"><small><?php echo Functions_Datas::MyDateTime($reply->datanote,true) ?> </small></span>
		<p class="formSep"><strong>Assunto:</strong> <?= $reply->assuntonote ?></p>
		<p> <?php echo nl2br($reply->textonote )?>
		<p class="pull-right"><?php if($reply->id_user == Zend_Auth::getInstance()->getStorage()->read()->id_registro){ 
			echo "<a data-toggle=\"modal\" data-backdrop=\"static\" href=\"#EditNote\" onclick=\"getnoteedit({$reply->id_registro})\"><i class=\"splashy-tag_edit\"></i></a><i style=\"cursor:pointer\" class=\"splashy-tag_remove\" onclick=\"removenote({$reply->id_registro})\"></i>"; }; ?></p>
		</div>
		<?php } ?>
		
		</div>
		
		<div class="tab-pane" id="tab_l3">
		<div id="FormFiles">
		<form id="clientesfiles" name="clientesfiles" enctype="multipart/form-data" class="form-horizontal" method="post" action="/crm/prospects/save-file">
		<input type="hidden" name="tipofile" value="prospects" id="tipofile">
		<input type="hidden" name="idreg" value="<?php echo $this->prospect->id_registro ?>" id="idreg"> 
		
		<fieldset id="fieldset-clientesfiles" class="form-horizontal">
		<div class="row-fluid formSep">
		
		<div class="span3">
		<label for="nomeamigavel" class="optional">Nome Amigavel:</label>
		<input type="text" name="nomeamigavel" id="nomeamigavel">
		</div>
		
		<div class="span3">
		<label for="arquivo" class="tags">Tags:</label>
		<input type="text" name="tags" id="tags">
		</div>
		
		<div class="span3">
		<label for="arquivo" class="optional">Selecione o Documento:</label>
		<input type="hidden" name="MAX_FILE_SIZE" value="104857600" id="MAX_FILE_SIZE">
		<input type="file" name="arquivo" id="arquivo"  class="uni_style">
		</div>
		
		</div>
		</fieldset>
		
		<fieldset id="fieldset-grupo20">
		<div class="row-fluid formSep">
		<div class="span11">
		<label for="obsfile" class="optional">Observações do Arquivo:</label>
		<textarea name="obsfile" id="obsfile" rows="5" style="width:100%" cols="80"></textarea>
		</div>
		</div>
		</fieldset>
		
		<fieldset id="fieldset-botoes">
		<div style="text-align:right">
		<input type="reset" name="limparoutros" id="limparoutros" value="Limpar" class="btn btn-large btn-warning">
		<input type="submit" name="submitoutros" id="submitoutros" value="Salvar" class="btn btn-large btn-primary">
		</div>
		</fieldset>
		</form>
		</div>
		
	
		 <div class="row-fluid">
                        <div class="span12">
                            <h3 class="heading">Arquivos do Prospect: <span class="pull-right"><i class="splashy-document_letter_new newfile ttip_t" alt="Nova nota" title="Adicionar Arquivo"></i></span></h3>
                            
                          	<table id="table-arquivos"  class="table table-striped table-bordered table-condensed">
		<thead>
		<tr>
			<th>Tipo:</th>
			<th>Nome</th>
			<th>Tags</th>
			<th>Opções</th>
			</tr>
		</thead>
		<tbody>
		<?php 
		if($this->arquivos){
		foreach($this->arquivos as $arquivo){?>
		<tr>
		<td><?php echo $arquivo['filetype'] ?></td>
		<td><?php echo $arquivo['nomeamigavel'] ?></td>
		<td><?php echo $arquivo['tags'] ?></td>
		<td><span class="pull-center"><a href="/system/files/get-file/id/<?php echo $arquivo['id_registro'] ?>" target="_blank" alt="Download do Arquivo" title="Download do Arquivo"><i class="splashy-folder_modernist_down"></i></a>  
		<a href="/system/files/render/id/<?php echo $arquivo['id_registro'] ?>" target="_blank" alt="Visualizar Arquivo" title="Visualizar  Arquivo"><i class="splashy-document_a4_marked"></i></a> 
		<i class="splashy-folder_modernist_remove removearquivo" idarquivo="<?php echo $arquivo['id_registro'] ?>" style="cursor:pointer"></i>
		</span></td>
		</tr>
		
		<?php  
		}
		}
		?>
		</tbody>
		
		</table>
		</div>
		</div>
		</div>
		<div class="tab-pane" id="tab_l4"></div>
		<div class="tab-pane" id="tab_l5">
			<p class="f_legend">Estágios desta Proposta
			<span class="pull-right"><small>(DE/PARA) </small></span> 
			</p>
				<table id="tableetapas"  class="table table-striped table-bordered table-condensed">
		<thead>
		<tr>
			<th>Data:</th>
			<th>Usuário</th>
			<th>Estagio</th>
			<th>Probabilidade</th>
			<th>Data Limite</th>
			<th>Valor Proposta</th>
			
			</tr>
		</thead>
		<tbody>
		
		<?php foreach($this->dadosestagios as $estagio){?>
		<tr>
		<td><?php echo Functions_Datas::MyDateTime($estagio->dataatualizacao,true)?></td>
		<td><?php echo System_Model_Users::whoIs($estagio->user_id)?></td>
		<td><?php echo number_format($estagio->wprobabilidadeproposta,2,',','') ?> % / <?php echo number_format($estagio->iprobabilidadeproposta,2,',','') ?> %</td>
		<td><?php echo Crm_Model_Prospects_EstagioProposta::getNomeDepto($estagio->westagioproposta)?> / <?php echo Crm_Model_Prospects_EstagioProposta::getNomeDepto($estagio->iestagioproposta)?></td>
		<td><?php echo Functions_Datas::MyDateTime($estagio->wdatalimite)?> / <?php echo Functions_Datas::MyDateTime($estagio->idatalimite)?></td>
		<td>R$ <?php echo number_format($estagio->wvalorproposta,2,',','') ?> / R$ <?php echo number_format($estagio->ivalorproposta,2,',','') ?></td>
		</tr>
		<?php } ?>
		</tbody>
		</table>
		
		</div>
		
	<div class="tab-pane" id="tab_l6">
			<div id="checklistadd">
			<p class="f_legend">Check-List
			<span class="pull-right"><i style="cursor:pointer" class="splashy-document_a4_new newchecklist ttip_b" title="Criar Checklist"></i> <i style="cursor:pointer" class="splashy-document_a4_download importchecklist ttip_b" title="Importar Checklist" ></i></span> 
			</p>
			</div>
			
			<div id="checklistdata">
			<p class="f_legend" id="NomeCheckList"><?php echo System_Model_ChecklistBasicos::getnome($this->checklists->id_checklist) ?></p>
			<table id="checklistdatatable" class="table table-striped table-bordered table-condensed">
				<thead>
		<tr>
			<th></th>
			<th>Etapa:</th>
			<th>Vencimento:</th>
		</tr>
		</thead>
		<tbody>
		<?php foreach($this->itenschecklist as $item ){
			$datadobanco = Functions_Datas::MyDateTime($item->datedue);
			$datehoje = strtotime(date('Y-m-d'));
			$datecompar = strtotime($item->datedue);
			
			if( $datecompar <  $datehoje){
				$rowdate = "<span class=\"label label-important ttip_t\" title=\"Atrasado\">$datadobanco</span>";
			}else{
				$rowdate = "<span class=\"label label-success ttip_t\" title=\"Em Dia\">$datadobanco</span>";
			}
			 
		
			?>
		<tr>
		<?php if($item->statusitem == '0'){ ?>
		<td><i class="splashy-close checklistitem" idreg="<?php echo $item->id_item ?>"></i></td>
		<?php }else{ ?>
		<td><i class="splashy-check checklistitem pop_over"  data-content="Este item foi finalizado em: <?php echo Functions_Datas::MyDateTime($item->dateitem,true) ?> por: <?php echo System_Model_Users::whoIs($item->userid) ?>. Você pode voltar o item ao status anterior clicando no item" data-original-title="Item Finalizado" data-placement="right" idreg="<?php echo $item->id_item ?>"></i></td>
		<?php } ?>
        <td><?php echo System_Model_ChecklistEtapas::getnome($item->id_item)?></td>
        <td><?= $rowdate ?></td>
        </tr>
		<?php }?>
		
	</tbody>
					
			
			</table>
			
			</div>
			</div>

	
	</div>
	
	
	<div class="modal hide fade" id="EditNote">
<div class="modal-body">  

<form id="newreply" name="newreply" enctype="id_note" class="form-horizontal" method="post" action="/crm/prospects/editnote">
		<input type="hidden" name="id_note" value="" id="id_note">
		
		<div class="row-fluid formSep">
		<div class="span12">
		<label for="assuntoticket" class="optional">Assunto Resposta</label>
		<input type="text" name="assuntoticket" id="assuntoticketeditnote" class="span12" >
		</div>
		</div>
				
		<div class="row-fluid formSep">
		<div class="span12">
		<label for="dadosticket" class="optional">Informações Resposta:</label>
		<textarea name="dadosticket" id="dadosticketeditnote" class="span12" rows="8"></textarea>
		</div>

		</div>
		<div class="modal-footer">  
		<div style="text-align:right">
		<a href="javascript:void(0)" class="btn btn-large btn-warning" data-dismiss="modal">Cancelar</a>
		<input type="submit" name="submit" id="submiteditnote" value="Salvar" class="btn btn-large btn-primary">
		</div>		
		</div>
		
</form>
</div>
</div>
<div class="modal hide fade" id="ImportChecklist">
<form id="newchecklist" name="newchecklist" class="form-horizontal" method="post" action="/system/checklist/new">
<div class="modal-body">  
<div class="row-fluid formSep">
		<div class="span8">
		<label for="nomechecklist" class="optional">Nome Checklist</label>
		<select name="tiponegocio" id="id_checklistimport">
		<?php
		$empresas = System_Model_ChecklistBasicos::renderCombo('2');
		foreach($empresas as $key=>$value){
		echo "<option value=\"$key\"> $value </otion>";
		}
		?>
		</select>
		</div>
</div>
</div>


<div class="modal-footer">  
<div style="text-align:right">

<input type="button" id="importtasks" value="Importar" onclick="importchecklist()" class="btn btn-large btn-primary">
</div>		
</div>
</form>

</div>

<div class="modal hide fade" id="NewChecklist">
<form id="newchecklist" name="newchecklist" class="form-horizontal" method="post" action="/system/checklist/new">
<div class="modal-body">  
<div class="row-fluid formSep">
		<div class="span8">
		<label for="nomechecklist" class="optional">Nome Checklist</label>
		<input type="text" name="nomechecklist" id="nomechecklist" class="span12 required" >
		</div>
		<div class="span4">
		<label for="tipochecklist" class="optional">Tipo Checklist</label>
			<select name="tipochecklist" id="tipochecklist"  class="span12" >
			 <option value="1"> Tickets </otion>
			 <option value="2" selected> Prospects </otion>
			 <option value="3"> Orçamentos </otion>
			 <option value="4"> Ordens de Serviço </otion>
		</select>
		</div>
		</div>
		
		<div class="row-fluid formSep">
		<table id="tableaddchecklist"  class="table table-striped table-bordered table-condensed">
		<thead>
		<tr>
			<th width="85%">Nome Etapa:</th>
			<th width="10%">Dias</th>
			<th width="5%"><i class="splashy-add ttip_b addetapachecklist" title="Adicionar Etapa"></i></th>
		</tr>
		</thead>
		<tbody>
		<tr>
		<td><input type="text" name="nomeetapa[]" id="assuntoticketeditnote" class="span12 required" ></td>
		<td><input type="text" name="diasestapa[]" id="assuntoticketeditnote" class="span12 required" ></td>
		<td><i class="splashy-remove_minus_sign removetrchecklist"></i></td>
		</tr>
		</tbody>
		</table>
	</div>
</div>
<div class="modal-footer">  
<div style="text-align:right">
<a href="javascript:void(0)" class="btn btn-large btn-warning" data-dismiss="modal">Cancelar</a>
<input type="submit" name="submit" id="submiteditnote" value="Salvar" class="btn btn-large btn-primary">
</div>		
</div>
</form>
</div>

<div id="ajaxforms"></div>
	
	<script>
		$().ready(function(){
			<?php if($this->haschecklist){ ?>
			$("#checklistdata").show();
			$("#checklistadd").hide();
			
			<?php }else{ ?>
			$("#checklistdata").hide();
			<?php } ?>
			
			$("#FormUpdateProspect").hide();
			$("#FormFiles").hide();
			$("#noteform").hide();
			$(".openreply").click(function(){
				$("#FormUpdateProspect").toggle();
			});

			$(".newfile").click(function(){
				$("#FormFiles").toggle();
			});

			$(".newchecklist").click(function(){
				$("#NewChecklist").modal('show');
			});

			$(".importchecklist").click(function(){
				$("#ImportChecklist").modal('show');
			})

			$(".newnote").click(function(){
				$("#noteform").toggle();
			});

			$('#table-arquivos').dataTable({
			       "sPaginationType": "bootstrap_alt",
			       "oLanguage": {
						"sUrl": "/js/datatable_ptbr.txt"
					}
			    });
			
			 $('.addetapachecklist').live('click',function () {
			        $('#tableaddchecklist > tbody:last').append('<tr><td><input type="text" name="nomeetapa[]" id="assuntoticketeditnote" class="span12" ></td><td><input type="text" name="diasestapa[]" id="assuntoticketeditnote" class="span12" ></td><td><i class="splashy-remove_minus_sign removetrchecklist"></i></td></tr>');
			    });

			 $('.removetrchecklist').live('click',function () {
				 $(this).parents("tr").remove();
			    });

			  $('.checklistitem').live('click',function(){

				  if(confirm("Esta etapa foi finalizada?")){
					  idetapa =  $(this).attr('idreg');

					  $.ajax({ 
							type: "GET", 
							url: "/crm/prospects/checklistok/prospect/<?php echo $this->prospect->id_registro ?>/iditem/"+idetapa, 
							beforeSend: function() {
												
					 		}, 
							success: function(txt) {
								$.sticky("Etapa Finalizada!", { type: 'st-success' });
								$(this).toggleClass("splashy-close splashy-check");
							}, 
							error: function(txt) { 
								$.sticky("UM ERRO DE SISTEMA OCORREU.", { type: 'st-error' });
							} 
						}); 
					  
					  
					  
				  }

			  });


			 $('#newchecklist').validate({
					onkeyup: false,
					errorClass: 'error',
					validClass: 'valid',
					highlight: function(element) {
						$(element).closest('div').addClass("f_error");
					},
					unhighlight: function(element) {
						$(element).closest('div').removeClass("f_error");
					},
				    errorPlacement: function(error, element) {
				        $(element).closest('div').append(error);
				    },
				  
				    invalidHandler: function(form, validator) {
						$.sticky("Existem campos obrigatórios não preenchidos no formulário, corrija estes erros e tente novamente.", {autoclose : 5000, position: "top-right", type: "st-error" });
					},
					submitHandler: function(form) {
						jQuery(form).ajaxSubmit({
							target: "#ajaxforms",
							beforeSubmit:   function(){ 
								$.sticky("Salvando outros dados.", {autoclose : 5000, position: "top-right", type: "st-info" });
								
							}, 
						error: function(txt) { 
							$.sticky("Erro: "+ txt, {autoclose : 5000, position: "top-right", type: "st-error" });
							$("#ajaxforms").html('');

							},
						success: function(txt){
							var id_prospect = txt;
							$("#NewChecklist").modal('hide');
							$("#ajaxforms").html('');
							//$("#tableaddchecklist").empty();
							$.sticky("Dados Salvos com sucesso.", {autoclose : 5000, position: "top-right", type: "st-success" });

							 $.ajax({ 
									type: "GET", 
									url: "/system/checklist/get/tipo/prospect/idreg/<?php echo $this->prospect->id_registro ?>/id/"+id_prospect, 
									beforeSend: function() {
														
							 		}, 
									success: function(txt) {
										var retorno = jQuery.parseJSON(txt);
										$('#NomeCheckList').html(retorno.info.nomechecklist);
										$.each(retorno.itens, function(i,item){
													datatable = "<tr>";
													datatable += '<td><i class="splashy-close checklistitem" idreg="'+item.id_registro+'"></i></td>';
													datatable += "<td>"+item.nomeetapa+"</td>";
													datatable += "<td>"+item.duein+"</td>";
													datatable +=  "</tr>";
											
											  $('#checklistdatatable > tbody:last').append(datatable);

									    	
							    	    });
										$("#checklistadd").hide();
										$("#checklistdata").show();
									}, 
									error: function(txt) { 
										$.sticky("UM ERRO DE SISTEMA OCORREU.", { type: 'st-error' });
									} 
								}); 
									
					
						},
					        clearForm: true
							
						});
					}
				});

		});

		function getnoteedit(id){
			 $.ajax({ 
					type: "GET", 
					url: "/crm/prospects/getnotedata", 
					data: "id="+ id,
					beforeSend: function() {
										
			 		}, 
					success: function(txt) {
					
						var retorno = jQuery.parseJSON(txt);	
						$("#id_note").val(retorno.id_registro);
						$("#assuntoticketeditnote").val(retorno.assuntonote);
						$("#dadosticketeditnote").val(retorno.textonote);
								

																
					}, 
					error: function(txt) { 
						$.sticky("UM ERRO DE SISTEMA OCORREU.", { type: 'st-error' });
					} 
				}); 
		}

		function removenote(id){
			if(confirm("Deseja Realmente remover esta anotação?")){
				document.location.href="/crm/prospects/remove-note/id/"+id;
			}
		}
		

	function importchecklist(){
		 $.ajax({ 
				type: "GET", 
				url: "/system/checklist/get/tipo/prospect/idreg/<?php echo $this->prospect->id_registro ?>/id/"+$("#id_checklistimport").val(), 
				beforeSend: function() {
					$.sticky("Localizando e importando Checklist.", { type: 'st-info' });				
		 		}, 
				success: function(txt) {
					var retorno = jQuery.parseJSON(txt);
					$('#NomeCheckList').html(retorno.info.nomechecklist);
					$.each(retorno.itens, function(i,item){
								datatable = "<tr>";
								datatable += '<td><i class="splashy-close checklistitem" idreg="'+item.id_registro+'"></i></td>';
								datatable += "<td>"+item.nomeetapa+"</td>";
								datatable += "<td>"+item.duein+"</td>";
								datatable +=  "</tr>";
						
						  $('#checklistdatatable > tbody:last').append(datatable);

				    	
		    	    });
					$("#checklistadd").hide();
					$("#checklistdata").show();
				}, 
				error: function(txt) { 
					$.sticky("UM ERRO DE SISTEMA OCORREU.", { type: 'st-error' });
				} 
			}); 

		 $("#ImportChecklist").modal('hide');

	}
		

	</script>
	