<div class="tabbable tabs-left">
	 	<ul class="nav nav-tabs">
			<li class="active"><a href="#tab_l1" data-toggle="tab" class="pop_over" data-content="Todos os prospects atribuídos a você que estão ativos" data-original-title="Meus Prospects" data-placement="right">Meus Prospects <span class="pull-right label label-success"><?php echo $this->countNaoResolvidos ?></span></a></li>
			<li><a href="#tab_l2" data-toggle="tab" class="pop_over" data-content="Todos os prospects do sistema não atribuidos a ninguem" data-original-title="Não Atribuídos" data-placement="right">Não Atribuidos&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;<span class="pull-right label label-success"><?php echo $this->countNaoAtribuidos ?></span></a></li>
			<li><a href="#tab_l3" data-toggle="tab" class="pop_over" data-content="Todos os Prospects atribudos a você e suspensos" data-original-title="Suspensos" data-placement="right">Suspensos <span class="pull-right label label-success"><?php echo $this->countSuspended ?></span></a></li>
			<li><a href="#tab_l4" data-toggle="tab" class="pop_over" data-content="Totod os prospects atrinudos a você e pendentes" data-original-title="Pendentes" data-placement="right">Pendentes <span class="pull-right label label-success"><?php echo $this->countPendent ?></a></li>
			<li><a href="#tab_l5" data-toggle="tab" class="pop_over" data-content="Prospects Atribuidos a você atualizados nas últimas 48 horas" data-original-title="Atualizados Recentemente" data-placement="right">Atualizados Recentemente&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; <span class="pull-right label label-success"><?php echo $this->countAtualizadoRecente ?></span></a></li>
			<li><a href="#tab_l6" data-toggle="tab" class="pop_over" data-content="Prospects atribuidos a voce encerrados nas ultimas 48 horas" data-original-title="Encerrados Recentemente" data-placement="right">Encerrados Recentemente <span class="pull-right label label-success"><?php echo $this->countResolvidoRecente ?></span></a></li>
			<li><a href="#tab_l7" data-toggle="tab" class="pop_over" data-content="Todos os seus prospects encerrados" data-original-title="Encerrados" data-placement="right">Encerrados <span class="pull-right label label-success"><?php echo $this->countClosed ?></span></a></li>
			<li><a href="#tab_l8" data-toggle="tab" class="pop_over" data-content="Todos os Prospects do Sistema" data-original-title="Geral" data-placement="right">Geral <span class="pull-right label label-success"><?php echo $this->countGeral ?></span></a></li>
			</ul>
	<div class="tab-content">
		<div class="tab-pane active" id="tab_l1">
			<table id="table-1"  class="table table-striped table-bordered table-condensed">
		<thead>
		<tr>
			<th>Protocolo</th>
			<th>Cliente</th>
			<th>Estágio</th>
			<th>Prob</th>
			<th>Valor</th>
			<th>Dt Limite</th>
			<th>Opções</th>
			</tr>
		</thead>
		<tbody>
		</tbody>
		</table>
		</div>
		<div class="tab-pane" id="tab_l2">
			<table id="table-2"  class="table table-striped table-bordered table-condensed">
		<thead>
		<tr>
			<th>Protocolo</th>
			<th>Cliente</th>
			<th>Estágio</th>
			<th>Prob</th>
			<th>Valor</th>
			<th>Dt Limite</th>
			<th>Opções</th>
			</tr>
		</thead>
		<tbody>
		</tbody>
		</table>
		 </div>
		<div class="tab-pane" id="tab_l3">
		<table id="table-3"  class="table table-striped table-bordered table-condensed">
		<thead>
		<tr>
			<th>Protocolo</th>
			<th>Cliente</th>
			<th>Estágio</th>
			<th>Prob</th>
			<th>Valor</th>
			<th>Dt Limite</th>
			<th>Opções</th>
			</tr>
		</thead>
		<tbody>
		</tbody>
		</table>
		 </div>
		<div class="tab-pane" id="tab_l4">
		<table id="table-4"  class="table table-striped table-bordered table-condensed">
		<thead>
		<tr>
			<th>Protocolo</th>
			<th>Cliente</th>
			<th>Estágio</th>
			<th>Prob</th>
			<th>Valor</th>
			<th>Dt Limite</th>
			<th>Opções</th>
			</tr>
		</thead>
		<tbody>
		</tbody>
		</table>
		 </div>
		<div class="tab-pane" id="tab_l5">
		<table id="table-5"  class="table table-striped table-bordered table-condensed">
		<thead>
		<tr>
			<th>Protocolo</th>
			<th>Cliente</th>
			<th>Estágio</th>
			<th>Prob</th>
			<th>Valor</th>
			<th>Dt Limite</th>
			<th>Opções</th>
			</tr>
		</thead>
		<tbody>
		</tbody>
		</table>
		 </div>
		<div class="tab-pane" id="tab_l6">
		
		<table id="table-6"  class="table table-striped table-bordered table-condensed">
		<thead>
		<tr>
			<th>Protocolo</th>
			<th>Cliente</th>
			<th>Estágio</th>
			<th>Prob</th>
			<th>Valor</th>
			<th>Dt Limite</th>
			<th>Opções</th>
			</tr>
		</thead>
		<tbody>
		</tbody>
		</table>
		 </div>
		<div class="tab-pane" id="tab_l7">
		
		<table id="table-7"  class="table table-striped table-bordered table-condensed">
		<thead>
		<tr>
			<th>Protocolo</th>
			<th>Cliente</th>
			<th>Estágio</th>
			<th>Prob</th>
			<th>Valor</th>
			<th>Dt Limite</th>
			<th>Opções</th>
			</tr>
		</thead>
		<tbody>
		</tbody>
		</table>
		 </div>
		<div class="tab-pane" id="tab_l8">
		
		<table id="table-8"  class="table table-striped table-bordered table-condensed">
		<thead>
		<tr>
			<th>Protocolo</th>
			<th>Cliente</th>
			<th>Estágio</th>
			<th>Prob</th>
			<th>Valor</th>
			<th>Dt Limite</th>
			<th>Opções</th>
			</tr>
		</thead>
		<tbody>
		</tbody>
		</table>
		 </div>
		</div>
		</div>
		
		<script>
$().ready(function(){
	$('#table-1').dataTable({
		"oLanguage": {
			"sUrl": "/js/datatable_ptbr.txt"
		},
		"sPaginationType": "bootstrap",
        "bProcessing": true,
		"bServerSide": true,
		 "sAjaxSource": "/crm/lista-prospects/ativos"
               	
                    
    });

	$('#table-2').dataTable({
		"oLanguage": {
			"sUrl": "/js/datatable_ptbr.txt"
		},
		"sPaginationType": "bootstrap",
        "bProcessing": true,
		"bServerSide": true,
		 "sAjaxSource": "/crm/lista-prospects/naoatribuidos"
               	
                    
    });

	$('#table-3').dataTable({
		"oLanguage": {
			"sUrl": "/js/datatable_ptbr.txt"
		},
		"sPaginationType": "bootstrap",
        "bProcessing": true,
		"bServerSide": true,
		 "sAjaxSource": "/crm/lista-prospects/suspensos"
               	
                    
    });

	$('#table-4').dataTable({
		"oLanguage": {
			"sUrl": "/js/datatable_ptbr.txt"
		},
		"sPaginationType": "bootstrap",
        "bProcessing": true,
		"bServerSide": true,
		 "sAjaxSource": "/crm/lista-prospects/pendentes"
               	
                    
    });

	$('#table-5').dataTable({
		"oLanguage": {
			"sUrl": "/js/datatable_ptbr.txt"
		},
		"sPaginationType": "bootstrap",
        "bProcessing": true,
		"bServerSide": true,
		 "sAjaxSource": "/crm/lista-prospects/atualizadosrecente"
               	
                    
    });

	$('#table-6').dataTable({
		"oLanguage": {
			"sUrl": "/js/datatable_ptbr.txt"
		},
		"sPaginationType": "bootstrap",
        "bProcessing": true,
		"bServerSide": true,
		 "sAjaxSource": "/crm/lista-prospects/encerradosrecente"
               	
                    
    });

	$('#table-7').dataTable({
		"oLanguage": {
			"sUrl": "/js/datatable_ptbr.txt"
		},
		"sPaginationType": "bootstrap",
        "bProcessing": true,
		"bServerSide": true,
		 "sAjaxSource": "/crm/lista-prospects/encerrados"
               	
                    
    });

	$('#table-8').dataTable({
		"oLanguage": {
			"sUrl": "/js/datatable_ptbr.txt"
		},
		"sPaginationType": "bootstrap",
        "bProcessing": true,
		"bServerSide": true,
		 "sAjaxSource": "/crm/lista-prospects/geral"
               	
                    
    });
});

</script>
		
		
