<div class="row-fluid">
<div class="span12">
<h3 class="heading">Produção de Pedido <span class="pull-right"> <small><?php echo $this->basicosData['nomepessoa']?> <strong>Número: <?php echo $this->basicosData['id_registro']?></strong> </small></span></h3>
</div>
</div>
<div id="ajaxrequest"></div>

	
	<table id="table-1"  class="table table-striped table-bordered table-condensed">
	<thead>
		<tr>
			<th width="20%">Produto:</th>
			<th width="5%">Qtd</th>
			<th width="5%">Vl Unit.</th>
			<th width="5%">Vl Total:</th>
			<th width="10%">Adicional:</th>
			<th width="7%">Adicional:</th>
			<th width="7%">Observações:</th>
			<th width="5%"></th>
			</tr>
		</thead>
		<tbody>
		</tbody>
	
	</table>
	


<script>
$().ready(function(){



	

	$('#table-1').dataTable({
		"oLanguage": {
			"sUrl": "/js/datatable_ptbr.txt"
		},
		
		"sPaginationType": "bootstrap",
        "bProcessing": true,
		"bServerSide": true,
		 "sAjaxSource": "/system/datatables/produtos-pedido-producao/pedido/<?php echo $this->basicosData['id_registro']?>/blockpedido/<?php echo $this->basicosData['liberaprod'] ?>"
               	
                    
    });


	    

});

function reloadtable(){
	$("#table-1").dataTable().fnDraw(); 
}

</script>