<style>
.modal > form {
    margin-bottom: 0;
}
</style>
<div class="row-fluid">
<div class="span12">
<h3 class="heading">Consulta Programaçao:</h3>
</div>
</div>
<div id="ajaxrequest"></div>

	
	<table id="table-1"  class="table table-striped table-bordered table-condensed">
	<thead>
		<tr>
			<th width="5%">Ped:</th>
			<th width="30%">Cliente:</th>
			<th width="30%">Produto:</th>
			<th width="5%">Qtd</th>
			<th width="5%">OP</th>
			<th width="8%">Concluido</th>
			<th width="8%">Resta</th>
			<th width="9%"></th>
			</tr>
		</thead>
		<tbody>
		</tbody>
	
	</table>
	
<div class="modal hide fade" id="CancelModal">
 <form id="cancelalancamento" name="cancelalancamento" method="post" action="/erp/producao/cancela-programacao">
 <div class="modal-header">
   <button class="close" data-dismiss="modal">×</button>
   <h3>Confirmar Cancelamento da <span id="id_do_lancamento"></span>:</h3>
   </div>
 <div class="modal-body">
 <div class="alert alert-warning">REPITA OS CARACTERES DA IMAGEM NA CAIXA ABAIXO E CLIQUE EM CONFIRMAR PARA CANCELAR ESSA PROGRAMAÇÃO</div>
 <input type='hidden' name="id_prog_cancel" id="id_prog_cancel" value="0">
 <div id="captcha">
 <?php 
 $captcha = new Zend_Service_ReCaptcha('6Ldk6-ISAAAAALqcpxh2182Y0Yd8ZqHr2p_QIGoO','6Ldk6-ISAAAAAHpOarrRAqW6S9uvJEdERs2MgP6h');
 echo $captcha->getHTML() ?>
 </div>
 </div>
  <div class="modal-footer">
<input type="submit" name="submit" id="submiteditnote" value="CONFIRMAR" class="btn btn-large btn-primary">
</div>
</form>
 </div>
	
  <div class="modal hide fade" id="LancarModal">
 <form id="lancamentoproducao" name="lancamentoproducao" method="post" action="/erp/producao/salvar-lancamento-modal">
 <div class="modal-header">
   <button class="close" data-dismiss="modal">×</button>
   <h3>Efetuar Lançamento</h3>
   </div>
 <div class="modal-body">

 </div>
  <div class="modal-footer">
<input type="submit" name="submit" id="submiteditnote" value="CONFIRMAR" class="btn btn-large btn-primary">
</div>
</form>
 </div>
 
 
 
   <div class="modal hide fade" id="ConsultaModal">
 <form id="lancamentoproducao" name="lancamentoproducao" method="post" action="">
 <div class="modal-header">
   <button class="close" data-dismiss="modal">×</button>
   <h3>Consulta de Produção OP:</h3>
   </div>
 <div class="modal-body">

 </div>
  <div class="modal-footer">
<input type="button" name="button" id="CloseConsultaModal" value="FECHAR" class="btn btn-large btn-primary">
</div>
</form>
 </div>
 
 
 
 	

	
	<script>
$().ready(function(){
	$("#ModelPre").hide();

	$("#CloseConsultaModal").live('click',function(){
		
		 $("#ConsultaModal").modal("hide"); 
	});

	$("a[data-target=#LancarModal]").live('click',function(ev) {
		    ev.preventDefault();
		    var target = $(this).attr("href");

		    // load the url and show modal on success
		    $("#LancarModal .modal-body").load(target, function() { 
		         $("#LancarModal").modal("show"); 
		    });
		});	

	 $("a[data-target=#ConsultaModal]").live('click',function(ev) {
		    ev.preventDefault();
		    var target = $(this).attr("href");

		    // load the url and show modal on success
		    $("#ConsultaModal .modal-body").load(target, function() { 
		         $("#ConsultaModal").modal("show"); 
		    });
		});	


	 $(".cancelprod").live('click',function(){
		 id_lancamento = $(this).attr('id_lancamento');
		 showRecaptcha('captcha');
		 $("#id_prog_cancel").val(id_lancamento);
		 $("#id_do_lancamento").html("OP "+id_lancamento);
		 $("#CancelModal").modal("show"); 
		 
		 
	 });
	

	$('#table-1').dataTable({
		"oLanguage": {
			"sUrl": "/js/datatable_ptbr.txt"
		},
		
		"sPaginationType": "bootstrap",
        "bProcessing": true,
		"bServerSide": true,
		 "sAjaxSource": "/system/datatables/produtos-em-producao/"
               	
                    
    });


	$('#lancamentoproducao').validate({
		onkeyup: false,
		errorClass: 'error',
		validClass: 'valid',
		highlight: function(element) {
			$(element).closest('div').addClass("f_error");
		},
		unhighlight: function(element) {
			$(element).closest('div').removeClass("f_error");
		},
  errorPlacement: function(error, element) {
      $(element).closest('div').append(error);
  },

  invalidHandler: function(form, validator) {
			$.sticky("Existem campos obrigatórios não preenchidos no formulário, corrija estes erros e tente novamente.", {autoclose : 5000, position: "top-right", type: "st-error" });
		},
		submitHandler: function(form) {
			jQuery(form).ajaxSubmit({
				target: "#ajaxrequest",
				beforeSubmit:   function(){ 
					$.sticky("Salvando informações.", {autoclose : 5000, position: "top-right", type: "st-info" });
					
				}, 
			error: function(txt) { 
				$.sticky("Ocorreu um erro com sua solicitação: "+ txt, {autoclose : 5000, position: "top-right", type: "st-error" });
				$("#ajaxrequest").html("Erro" + txt);
				//reloadtable();
				
			},
			success: function(txt){
				if(txt == "ERRO"){
					$.sticky("CARACTERES INCORRETOS TENTE NOVAMENTE.", {autoclose : 10000, position: "top-right", type: "st-error" });
					$("#ajaxrequest").html('');
				}else{
				$.sticky("Lançamento baixado com sucesso.", {autoclose : 5000, position: "top-right", type: "st-success" });
				$("#LancarModal").modal('hide');  
				reloadtable();
				$("#ajaxrequest").html('');
				}
				
				
		
			},
		        clearForm: true
				
			});
		}
});

	$('#cancelalancamento').validate({
		onkeyup: false,
		errorClass: 'error',
		validClass: 'valid',
		highlight: function(element) {
			$(element).closest('div').addClass("f_error");
		},
		unhighlight: function(element) {
			$(element).closest('div').removeClass("f_error");
		},
  errorPlacement: function(error, element) {
      $(element).closest('div').append(error);
  },

  invalidHandler: function(form, validator) {
			$.sticky("Existem campos obrigatórios não preenchidos no formulário, corrija estes erros e tente novamente.", {autoclose : 5000, position: "top-right", type: "st-error" });
		},
		submitHandler: function(form) {
			jQuery(form).ajaxSubmit({
				target: "#ajaxrequest",
				beforeSubmit:   function(){ 
					$.sticky("Solicitando Cancelamento.", {autoclose : 5000, position: "top-right", type: "st-info" });
					
				}, 
			error: function(txt) { 
				$.sticky("Ocorreu um erro com sua solicitação: "+ txt, {autoclose : 5000, position: "top-right", type: "st-error" });
				$("#ajaxrequest").html("Erro" + txt);
				//reloadtable();
				
			},
			success: function(txt){
				if(txt == "ERRO"){
					$.sticky("CARACTERES INCORRETOS TENTE NOVAMENTE.", {autoclose : 10000, position: "top-right", type: "st-error" });
					$("#ajaxrequest").html('');
				}else{
				$.sticky("OP cancelada com sucesso.", {autoclose : 5000, position: "top-right", type: "st-success" });
				$("#CancelModal").modal('hide');  
				reloadtable();
				$("#ajaxrequest").html('');
				}
				
				
		
			},
		        clearForm: true
				
			});
		}
});
	    

});

function showRecaptcha(element) {
    Recaptcha.create("6Ldk6-ISAAAAALqcpxh2182Y0Yd8ZqHr2p_QIGoO", element, {
      theme: "red",
      callback: Recaptcha.focus_response_field});
  }

function reloadtable(){
	$("#table-1").dataTable().fnDraw(); 
}

</script>
	