<div class="row-fluid">
<div class="span12">
<h3 class="heading">Produção de Pedido <span class="pull-right"> <small><?php echo Cadastros_Model_Pessoas::getNomeEmpresa($this->dadosVenda->id_pessoa) ?> <strong>Número: <?php echo $this->dadosVenda['id_registro']?></strong> </small></span></h3>
</div>
</div>
<div id="ajaxrequest"></div>
<div class="row-fluid">
<div class="span6">
<strong>Produto:</strong>
</div>
<div class="span2">
<strong>Quantidade:</strong>
</div>
<div class="span4">
<strong>Agenda de Entrega:</strong>
</div>
</div>
<div class="row-fluid">
<div class="span6">
<?php echo "({$this->dadosProduto['codigointerno']}){$this->dadosProduto['nomeproduto']}" ?>
</div>
<div class="span2">
<?php echo number_format($this->dadosProduto['quantidade'],2,',','') ?>
</div>
<div class="span4">
<?php if($this->dadosVenda['agendamento_entrega'] <> ''){
			echo Functions_Datas::MyDateTime($this->dadosVenda['agendamento_entrega']);
		}else{
			echo "Entrega sem Agendamento";
		} ?>
</div>
</div>
<div class="row-fluid">
<div class="span12">
<h3 class="heading">Vefificação de Estoques:</h3>
<table class="table table-striped table-bordered">
<thead>
<tr>
<th width="25%">Produto:</th>
<th width="25%">Necessário:</th>
<th width="25%">Estoque Atual:</th>
<th width="25%">Status:</th>
</tr>
</thead>
<tbody>
<?php $produtoemfalta = '';
foreach($this->compostos as $composto){ 
if($composto['quantidade'] < $composto['estoqueatual']){
$statusprod = '<i class="splashy-check ttip_r" title="Produto OK"></i>';
}elseif($composto['quantidade'] > $composto['estoqueatual']){
if(!$produtoemfalta){
$produtoemfalta = true;
}
$statusprod = '<i class="splashy-error_do_not  ttip_r" title="Produto em Falta"></i>';
}
?>
<tr>
<td><?php echo $composto['produto']?></td>
<td><?php echo number_format($composto['quantidade'],2,',','')?></td>
<td><?php echo number_format($composto['estoqueatual'] ,2,',','')?> </td>
<td><?php echo $statusprod ?></td>
</tr>
<?php } ?>
</tbody>
<tfoot>
<tr>
<td colspan="2">
<?php if($produtoemfalta && System_Model_SysConfigs::getConfig('TravaProducaoEstoque') == 1){ 
$dados = array('id_venda'=>$this->dadosVenda['id_registro'],
				'produtos'=>serialize($this->compostos)
);
	?>


<div class="alert alert-block alert-error fade in">
<h4 class="alert-heading">Impossivel Continuar !!</h4>
								<p>O estoque não é sufienciente para continuar essa programação</p>
								<p>Efetue uma solicitação de Compras ao departamento responsável</p>
<p><a class="btn btn-inverse" href='/erp/compras/solicita-producao/produtos/<?php echo serialize($dados) ?>'><i class="splashy-check"></i>
       Solicitar Compra
    </a>
       ou
    <a class="btn" href='/erp/producao/abrir-pedido/id/<?php echo $this->dadosVenda['id_registro'] ?>'><i class="splashy-error_small"></i>
       Cancelar
    </a></p>
						</div>
						

<?php }else{ ?>

<div class="alert alert-block alert-success fade in">
<h4 class="alert-heading">Confirmar Produção</h4>
								<p>Ao clicar no botão de cofirmação este produto estará bloqueado até o final da produção</p>
								<p>Por Favor Confirme para continuar</p>
								<p><a class="btn btn-inverse" href="/erp/producao/confirma-producao/id/<?php echo $this->dadosProduto['id_registro']?>"><i class="splashy-check"></i>
       Confirmar
    </a>
       ou
    <a class="btn" href="/erp/producao/abrir-pedido/id/<?php echo $this->dadosVenda['id_registro'] ?>"><i class="splashy-error_small"></i>
       Cancelar
    </a></p>
				
						</div>

<?php } ?>
<td colspan="2">
<?php if($produtoemfalta && System_Model_SysConfigs::getConfig('TravaProducaoEstoque') == 0){ ?> 
<div class="alert alert-block alert-error fade in">
<h4 class="alert-heading">ESTOQUE INSUFICIENTE!!</h4>
								<p>O estoque não é sufienciente para continuar essa programação mas as configurações permitem que você continue<br>Efetue uma solicitação de Compras ao departamento responsável</p>
<p><a class="btn btn-inverse" href='/erp/compras/solicita-producao/produtos/<?php echo serialize($dados) ?>' target="_blank"><i class="splashy-check"></i>
       Solicitar Compra
    </a>
       ou
    <a class="btn" href='/erp/producao/abrir-pedido/id/<?php echo $this->dadosVenda['id_registro'] ?>'><i class="splashy-error_small"></i>
       Cancelar
    </a></p></div>
						<?php } ?>
						</td>
						

</tr>


</tfoot>
</table>
</div>
</div>

