<div class="row-fluid">
<div class="span12">
<h3 class="heading">Processo De Emissao de NFe: <span class="pull-right"><small>N: <?php echo $this->dadosVenda->id_registro ?></small></span></h3>
</div>
</div>

<?php if($this->StatusRet){ 
		//print_r($this->respostas);

	foreach($this->respostas as $resp){

			if($resp['aProt'][0]['cStat'] <> '100'){
				$tipoalert = 'error';
				$icons = "<p><span class=\"pull-right\"><a href=\"/erp/faturamento/get-xml/id/{$this->idProcesso}\" target=\"_blank\" class=\"btn btn-inverse\">
						  <i class=\"splashy-document_a4\"></i> Visualizar Arquivo XML</a> Ou 
                         <a href=\"/erp/faturamento/\" class=\"btn btn-inverse\"><i class=\"splashy-check\"></i> Voltar ao Inicio </a></span></p>";
			}else{
				$tipoalert = 'success';
				$icons = "<p><span class=\"pull-right\"><a href=\"/erp/faturamento/get-xml/id/{$this->idProcesso}\" target=\"_blank\" class=\"btn btn-inverse\">
				<i class=\"splashy-document_a4\"></i> Visualizar Arquivo XML</a> Ou 
				<span class=\"pull-right\"><a href=\"/erp/faturamento/imprimir-danfe/id/{$this->idProcesso}\" target=\"_blank\" class=\"btn btn-inverse\">
				<i class=\"splashy-document_a4\"></i> Visualizar Arquivo PDF (DANFE)</a></span></p>";
			}


	?>

<div class="row-fluid">
<div class="span12">
<div class="alert alert-block alert-<?echo $tipoalert ?> fade in">
                                <a href="#" data-dismiss="alert" class="close">×</a>
                                <h4 class="alert-heading"><?php echo $resp['xMotivo']?></h4>
                                <ul>
                                    <li>Código de Status: <?php echo $resp['aProt'][0]['cStat']?> </li>
                                     <li>Protocolo: <?php echo $resp['aProt'][0]['nProt']?> </li>
                                    <li><strong><?php echo $resp['aProt'][0]['xMotivo']?></strong></li>
                                    <li>Processo efetuado em: <?php echo $resp['aProt'][0]['dhRecbto']?></li>
                                </ul>
                                <p> O que você gostaria de fazer agora? </p>
                                <?php echo $icons ?>
                                <br>
                                <br>
                            </div>
</div></div>
	
	
<?php
}
 }else{ 

$icons = "<p><a href=\"/erp/faturamento/\" class=\"btn btn-inverse\"><i class=\"splashy-check\"></i> Voltar ao Inicio </a></span></p>";
?>
 
 <div class="row-fluid">
<div class="span12">
<div class="alert alert-block alert-error fade in">
                                <a href="#" data-dismiss="alert" class="close">×</a>
                                <h4 class="alert-heading">Não Houve Retorno do serviço</h4>
                                <ul>
                                    <?php foreach($this->erros as $erro){?>
                                    <li><?php echo $erro ?></li>
                                    <?php } ?>
                                </ul>
                                <p> O que você gostaria de fazer agora? </p>
                                <?php echo $icons ?>
                                <br>
                                <br>
                            </div>
</div></div>
 
 <?php } ?>

