<div class="row-fluid">
<div class="span12">
<h3 class="heading">Inutilização de NFes<span class="pull-right"><button class="btn btn-warning" id="InutilizarFaixa">Inutilizar Faixa </button></span></h3>
</div>
</div>

<div class="row-fluid">
<div class="span12">
<table id="listalancamentos" class="table table-striped table-bordered">
<thead>
<tr>
<th width="10%">Empresa</th>
<th width="5%">Inicio</th>
<th width="5%">Final</th>
<th width="25%">Motivo</th>
<th width="25%">Status</th>
<th width="10%">Data:</th>
<th width="15%">Usuário:</th>
</tr>
</thead>
<tbody>
<tr>
<td class="dataTables_empty" colspan="9">Não existem dados nessa consulta!</td>
</tr>
</tbody>
</table>
</div>
</div>

<div class="modal hide fade" id="InutilizarModal">
 <form id="CCe" name="CCe" method="post" action="/erp/faturamento/inutiliza-faixa">
 <div class="modal-header">
   <button class="close" data-dismiss="modal">×</button>
   <h3>Inutilizar Faixa de Numeração NFe</h3>
   </div>
 <div class="modal-body">
 <div class="row-fluid">
 <div class="span4">
 <label>Empresa:</label>
										<select name="id_empresa" id="empresa" class="span12">
		<?php
		$empresas = System_Model_Empresas::renderCombo();
		foreach($empresas as $key=>$value){
		if($key == System_Model_Empresas::getEmpresaPadrao()){
			$selected = 'selected="selected"';
		}else{
			$selected = '';
		}

		echo "<option value=\"$key\" $selected> $value </otion>";
		}
		?>
		</select>
 
 </div>
  <div class="span2">
  <label>Série:</label>
  <input type="text" name="nSerie" class="span12" value="" placeholder="000">
  </div>
 
  <div class="span3">
  <label>NFe Inicial</label>
  <input type="text" name="nIni" class="span12" value="" placeholder="000000000">
 
 </div>
  <div class="span3">
  <label>NFe Inicial</label>
  <input type="text" name="nFim" class="span12" value="" placeholder="000000000">
 
 </div>
 
 </div>
  <div class="row-fluid">
    <div class="span12">
    <label>Justificativa</label>
    <textarea style="width:97%" name="xJust"></textarea> 
 </div>
  </div>
 </div>
  <div class="modal-footer">
<input type="submit" name="submit" id="submiteditnote" value="Processar" class="btn btn-large btn-primary">
</div>
</form>
 </div>
 
 


<script>
$().ready(function(){
	$('#listalancamentos').dataTable({
		"oLanguage": {
			"sUrl": "/js/datatable_ptbr.txt"
		},
		"sPaginationType": "bootstrap",
        "bProcessing": true,
		"bServerSide": true,
		 "sAjaxSource": "/system/datatables-faturamento/listar-inutilizadas"
               	
                    
    });

	 $("#InutilizarFaixa").live('click',function(){
		 $("#InutilizarModal").modal('show');
	 })
	 
	 
	
	 $("#MotivoInut").counter({
			goal: 255
		});


	
});



</script>
