<div class="row-fluid">
<div class="span12">
<h3 class="heading">Processo De Emissao Carta de Correção de NFe: <span class="pull-right"><small>N: <?php echo $this->dadosVenda->id_registro ?></small></span></h3>
</div>
</div>

<?php if($this->Success){ 
			
				$tipoalert = 'success';
				$icons = "<a href=\"/erp/faturamento/inutilizar\" class=\"btn btn-inverse\"><i class=\"splashy-check\"></i> Voltar </a></span></p>";

}else{	
			
				$tipoalert = 'error';
				$icons = "<a href=\"/erp/faturamento/inutilizar\" class=\"btn btn-inverse\"><i class=\"splashy-check\"></i> Voltar </a></span></p>";
			}


	?>

<div class="row-fluid">
<div class="span12">
<div class="alert alert-block alert-<?echo $tipoalert ?> fade in">
                                <a href="#" data-dismiss="alert" class="close">×</a>
                                <h4 class="alert-heading">Inutilização de NFe</h4>
                                <ul>
                                    <li>Código de Status: <?php echo $this->dados['cStat']?> </li>
                                     <li>Protocolo:  </li>
                                    <li><strong><?php echo $this->dados['xMotivo']?></strong></li>
                                    <li>Processo efetuado em: <?php echo Functions_Datas::MyDateTime($this->dados['datasolicitacao'],true)?></li>
                                </ul>
                                <p> O que você gostaria de fazer agora? </p>
                                <?php echo $icons ?>
                                <br>
                                <br>
                            </div>
</div></div>
	
<div class="row-fluid">
<div class="span12">
<label>XML do Processo</label>
<textarea rows="" cols="" style="width: 100%'"><?php echo $this->xml ?></textarea>
</div>
</div>

