<div class="row-fluid">
<div class="span12">
<h3 class="heading">NFe Recebidas <small>( <?php echo Erp_Model_Faturamento_NFe_Status::getStatus($this->tipo) ?> )</small> <button class="btn btn-warning" id="ImportarNFe">Importar NFe </button> <span class="pull-right">

<div class="btn-group">
                                        <button data-toggle="dropdown" class="btn dropdown-toggle">Selecione <span class="caret"></span></button>
                                        <ul class="dropdown-menu">
                                        <?php $tipos = Erp_Model_Faturamento_NFe_Status::getCombo();
											  foreach($tipos as $key=>$value){
                                        ?>
                                            <li><a href="/erp/faturamento/listar-entrada/type/<?php echo $key ?>"><?php echo $value?></a></li>
                                        <?php }; ?>
                                        </ul>
                                    </div></span></h3>
</div>
</div>

<div class="row-fluid">
<div class="span12">
<table id="listalancamentos" class="table table-striped table-bordered">
<thead>
<tr>
<th width="10%">Empresa</th>
<th width="10%">NFe</th>
<th width="25%">Remetente</th>
<th width="5%">Emissão</th>
<th width="5%">Saída</th>
<th width="25%">Natureza:</th>
<th width="5%">Total:</th>
<th width="10%">Opções:</th>
</tr>
</thead>
<tbody>
<tr>
<td class="dataTables_empty" colspan="9">Não existem dados nessa consulta!</td>
</tr>
</tbody>
</table>
</div>
</div>

  <div class="modal hide fade modal-large" id="ImportarNFeModal">
   <form id="CCe" name="CCe"  enctype="multipart/form-data" method="post" action="/erp/faturamento/importar-nfe">
 <div class="modal-header">
   <button class="close" data-dismiss="modal">×</button>
   <h3>Eventos da NFe:</h3>
   </div>
 <div class="modal-body">
 <div class="row-fluid">
 <div class="span12">
<label for="arquivo" class="optional">Selecione o Documento XML:</label>
		<input type="hidden" name="MAX_FILE_SIZE" value="104857600" id="MAX_FILE_SIZE">
		<input type="file" name="arquivo" id="arquivo"  class="uni_style">
 
 </div>
 </div>
  </div>
  <div class="modal-footer">
<input type="submit" name="submit" id="submiteditnote" value="Importar XML >>" class="btn btn-large btn-primary">
</div>
</form>
 </div>


<div class="modal hide fade modal-large" id="CCeModal">
 <form id="CCe" name="CCe" method="post" action="/erp/faturamento/emitir-cce">
 <input type="hidden" name="CCeID" id="CCeID" value="" class="required"> 
 <div class="modal-header">
   <button class="close" data-dismiss="modal">×</button>
   <h3>Carta de Correção Eletrônica (CCe):</h3>
   </div>
 <div class="modal-body">
 <div class="row-fluid">
 <div class="span12">
 <?php echo Functions_Messages::renderAlert("<strong>A Carta de Correcao e disciplinada pelo paragrafo 1o-A do art. 7o do Convenio S/N, de 15 de dezembro de 1970 e pode ser utilizada para regularizacao de erro ocorrido na emissao de documento fiscal, desde que o erro nao esteja relacionado com: I - as variaveis que determinam o valor do imposto tais como: base de calculo, aliquota, diferenca de preco, quantidade, valor da operacao ou da prestacao; II - a correcao de dados cadastrais que implique mudanca do remetente ou do destinatario; III - a data de emissao ou de saida.</strong>")?>
 <label>Descrição da Correção:</label>
 <textarea rows="7" cols="" style="width:100%" name="CCe_Dados" id="CCe_Dados" class="span10"></textarea>
 </div>
 </div>
 
 </div>
  <div class="modal-footer">
<input type="submit" name="submit" id="submiteditnote" value="Enviar CCe" class="btn btn-large btn-primary">
</div>
</form>
 </div>
 
 
 <div class="modal hide fade modal-large" id="CancelamentoModal">
 <form id="CCe" name="CCe" method="post" action="/erp/faturamento/cancelar-nfe">
 <input type="hidden" name="NFeID" id="NFeID" value="" class="required"> 
 <div class="modal-header">
   <button class="close" data-dismiss="modal">×</button>
   <h3>Cancelamento de NFe:</h3>
   </div>
 <div class="modal-body">
 <div class="row-fluid">
 <div class="span12">
 <?php echo Functions_Messages::renderAlert("<strong>Digite um motivo para o cancelamento com no mínimo 15 caracteres</strong>")?>
 <label>Motivo do Cancelamento:</label>
 <textarea rows="7" cols="" style="width:100%" name="Cancelamento_Dados" id="Cancelamento_Dados" class="span10"></textarea>
 </div>
 </div>
 
 </div>
  <div class="modal-footer">
<input type="submit" name="submit" id="submiteditnote" value="Cancelar NFe" class="btn btn-large btn-primary">
</div>
</form>
 </div>
 
 
  <div class="modal hide fade modal-large" id="EventosModal">
 <div class="modal-header">
   <button class="close" data-dismiss="modal">×</button>
   <h3>Eventos da NFe:</h3>
   </div>
 <div class="modal-body">
  </div>
  <div class="modal-footer">

</div>
 </div>
 



<script>
$().ready(function(){
	$('#listalancamentos').dataTable({
		"oLanguage": {
			"sUrl": "/js/datatable_ptbr.txt"
		},
		"sPaginationType": "bootstrap",
        "bProcessing": true,
		"bServerSide": true,
		 "sAjaxSource": "/system/datatables-faturamento/listar-nfe-recebida/type/<?php echo $this->tipo ?>"
               	
                    
    });

	 $(".EmitirCCe").live('click',function(){
		 $('.modal-large').css('width', '700px');
		
		 idNfe = $(this).attr('idNFe');
		 $("#CCeID").val(idNfe);
		 $("#CCeModal").modal('show');
		 

	 })
	 
	 
	 $("#ImportarNFe").live('click',function(){
		  $("#ImportarNFeModal").modal('show');
		 

	 })
	 
	 
	  $(".CancelarNFe").live('click',function(){
		 $('.modal-large').css('width', '700px');
		
		 idNfe = $(this).attr('idNFe');
		 $("#NFeID").val(idNfe);
		 $("#CancelamentoModal").modal('show');
		 

	 })

	 $("#CCe_Dados").counter({
			goal: 1000
		});

	 $("#Cancelamento_Dados").counter({
			goal: 1000
		});


	 $("a[data-target=#EventosModal]").live('click',function(ev) {
		    ev.preventDefault();
		    var target = $(this).attr("href");
		    $('.modal-large').css('width', '700px');
		    // load the url and show modal on success
		    $("#EventosModal .modal-body").load(target, function() { 
		         $("#EventosModal").modal("show"); 
		    });
		});	
});



</script>
