<div class="row-fluid">
<div class="span12">
<h3 class="heading">Processo De Emissao de NFe: <span class="pull-right"><small>N: <?php echo $this->dadosVenda->id_registro ?></small></span></h3>
</div>
</div>

<?php if ($this->ProcessoOK){ ?>
<div class="row-fluid">
<div class="span12">
<div class="alert alert-block alert-success fade in">
                                <a href="#" data-dismiss="alert" class="close">×</a>
                                <h4 class="alert-heading">Processo Conclúído nas estapas:</h4>
                                <ul>
                                    <li>Criação do XML</li>
                                    <li>Assinatura do Arquivo</li>
                                    <li>Validação dos Dados</li>
                                </ul>
                                <p> O que você gostaria de fazer agora? </p>
                                <p><span class="pull-right"><a href="/erp/faturamento/pre-visualiza/id/<?php echo $this->idProcesso?>" target="_blank" class="btn btn-inverse"><i class="splashy-document_a4"></i> Pré-Visualizar NFe</a> Ou <a href="/erp/faturamento/emitir-nfe/id/<?php echo $this->idProcesso?>" class="btn btn-inverse"><i class="splashy-check"></i> Prosseguir com a Emissao </a></span></p>
                                <br>
                                <br>
                            </div>
</div></div>



<?php }else{ ?>

<div class="row-fluid">
<div class="span12">
<div class="alert alert-block alert-error fade in">
                                <a href="#" data-dismiss="alert" class="close">×</a>
                                <h4 class="alert-heading">Erro no processo de <?php echo $this->error ?></h4>
                                <ul>
                                <?php foreach($this->ErrorMessages as $erro){?>
                                    <li><?php echo print_r($erro)?></li>
                               <?php }?>
                                </ul>
                                <p><a href="javascript:(window.history.back(-2))" class="btn btn-inverse"><i class="splashy-check"></i> Tente Novamente</a></p>
                            </div>
</div></div>

<div class="row-fluid">
<div class="span12">
<h4 class="heading">Arquivo XML:</h4>
<textarea rows="10" style="width:100%"><?php echo $this->ArquivoXML ?></textarea>
</div></div>

<?php } ?>