<div class="row-fluid">
<div class="span12">
<h3 class="heading">Selecionar Pedido:</h3>
<table id="listaclientes" class="table table-striped table-bordered">
<thead>
<tr>
<th width="5%">Ped</th>
<th width="5%">Tipo</th>
<th width="15%">Cliente:</th>
<th width="8%">CNPJ</th>
<th width="8%">Ped. Cliente</th>
<th width="8%">Agendamento:</th>
<th width="8%">Valor:</th>
<th width="5%">Alterações</th>
<th width="5%">Opções</th>
</tr>
</thead>
<tbody>
<tr>
<td class="dataTables_empty" colspan="8">Não existem dados nessa consulta!</td>
</tr>
</tbody>
</table>
</div>
</div>
<script>

$().ready(function(){

	$('#listaclientes').dataTable({
		"oLanguage": {
			"sUrl": "/js/datatable_ptbr.txt"
		},
		"sPaginationType": "bootstrap",
        "bProcessing": true,
		"bServerSide": true,
		 "sAjaxSource": "/system/datatables/pedidos-vendas-a-fat"
               	
                    
    });



})
</script>