<div class="row-fluid">
<div class="span12">
<h3 class="heading">Emissao de NFe </h3>
</div>
</div>
<div class="row-fluid">
<div class="span12">
 <div class="alert alert-block alert-error fade in">
                                <a href="#" data-dismiss="alert" class="close">×</a>
                                <h4 class="alert-heading">Erros Ocorreram no processo de emissão da NFe!</h4>
                                <ul>
                                    <li><?php echo $this->errMessage ?></li>
                                </ul>
                                <p><a href="/erp/faturamento/abrir-pedido/id/<?php echo $this->idPedido ?>" class="btn btn-inverse"><i class="splashy-check"></i>Voltar ao Pedido</a></p>
                            </div>
</div>
</div>
